### ISSUE TITLE
BUILD ERROR: QWidget: Must construct a QApplication before a QWidget （已解决）

### ISSUE THREAD

**Issue by HUSTERGS** [lhy0403/Qv2ray#100]
**写了一半解决了。。。但是还是写下来了**

似乎是build的时候使用了conda默认的python导致build有点问题，把默认Python换成了`/usr/bin/python`( [参考](https://stackoverflow.com/questions/24664435/use-default-python-rather-than-anaconda-installation-when-called-from-the-termin) )之后再重新编译一次就好了，**但是感觉aur的PKGBUILD应该也要考虑到这种情况**？

**简单描述这个 bug：**
Manjaro-deepin无法正常运行qv2ray
使用命令行运行`/usr/bin/qv2ray` 或是 `/opt/Qv2ray/bin/Qv2ray` (分别对应dev和stable)，显示:
```
[LICENCE]: 
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.

Qv2ray Current Developer Copyright (C) 2019 Leroy.H.Y (@lhy0403)
Hv2ray Initial Designs & gRPC implementation Copyright (C) 2019 Hork (@aliyuchang33)
Hv2ray/Qv2ray HTTP Request Helper (partial) Copyright 2019 (C) SOneWinstone (@SoneWinstone)
Qv2ray ArtWork Done By ArielAxionL (@axionl)
Qv2ray Russian Translations By TheBadGateway (@thebadgateway)

Qv2ray v1.99.99.3 running on Manjaro Linux x86_64

[UI]: FAILED to find any translations, THIS IS A BUILD ERROR.
QWidget: Must construct a QApplication before a QWidget
[1]    20996 abort (core dumped)  qv2ray
```

**如何复现这个bug：**
1. 通过aur安装`qv2ray`或是`qv2ray-dev-git`
2. 直接通过`.desktop`文件无法打开
3. 命令行输入`/usr/bin/qv2ray` 或是 `/opt/Qv2ray/bin/Qv2ray` (分别对应dev和stable)显示错误日志

**Comment by lhy0403** [comment]
首先很高兴能看到您解决了问题
但是，我不知道这个 issue 为什么会与 Python 的安装位置有关，
不过这个 
```
[UI]: FAILED to find any translations, THIS IS A BUILD ERROR.
``` 
报错确实我们 @aliyuchang33  在之前进行 CI 测试的时候频繁出现，主要的原因是旧版 Qt 缺少了 [lrelease.prf](https://github.com/lhy0403/Qv2ray/blob/master/libs/lrelease.prf) 这个文件。
详细请看：
https://github.com/lhy0403/Qv2ray/blob/b3ef3ad9763d5b86ae45113c6d322843ca388e4c/.travis.yml#L20-L28
的 21 与 28 行

**Comment by lhy0403** [comment]
两个小时前在 `master` 分支上出现了误操作，有人把 `dev` 分支合并进去了，如果可以的话，您方便重新 clone 一下 master 分支进行编译尝试吗？

**Comment by aliyuchang33** [comment]
有人又noob了？

**Comment by lhy0403** [comment]
是 main.cpp 里面一个变量初始化问题

**Comment by lhy0403** [comment]
和一个 Qt 那个上次弄了两天的翻译问题

**Comment by aliyuchang33** [comment]
写下文档吧，qt>=5.12

**Comment by lhy0403** [comment]
等我现在把 master 里面的脏 commit rebase 一下

**Comment by HUSTERGS** [comment]
> 首先很高兴能看到您解决了问题
> 但是，我不知道这个 issue 为什么会与 Python 的安装位置有关，
> 不过这个
> 
> ```
> [UI]: FAILED to find any translations, THIS IS A BUILD ERROR.
> ```
> 
> 报错确实我们 @aliyuchang33 在之前进行 CI 测试的时候频繁出现，主要的原因是旧版 Qt 缺少了 [lrelease.prf](https://github.com/lhy0403/Qv2ray/blob/master/libs/lrelease.prf) 这个文件。
> 详细请看以下 21 与 28 行
> https://github.com/lhy0403/Qv2ray/blob/b3ef3ad9763d5b86ae45113c6d322843ca388e4c/.travis.yml#L20-L28
> 
> 
> 这个文件描述了 Qt 如何处理 `lrelease` 和 `EXTRA_TRANSLATION` 变量（见 [Qv2ray.pro](https://github.com/lhy0403/Qv2ray/blob/master/Qv2ray.pro)）似乎是某些旧版 Qt 不包含这个功能，导致在编译时没有嵌入任何 UI 翻译文件。 （见 commit: [eed7826](https://github.com/lhy0403/Qv2ray/commit/eed7826d33d93200cf83cea7c61e7ce2a1cba5ab) ）
> 所以才导致了以上问题

编译version-v1之后可以正常启动了。之前那个换Python路径的说法有点问题，我当时是直接把`.zshrc`文件里面关于conda初始化的部分全部注释掉了然后再编译才可以用的，没有改之前的编译输出看到用的lib似乎是`~/anaconda3/include/qt`，而不是`/usr/lib/qt`，而且有很多warning，感觉可能是conda初始化脚本的问题？我也不是很清楚hhh。

**Comment by lhy0403** [comment]
好的，只要问题解决了就 OK

**Comment by axionl** [comment]
`Canda` is not the supported package on the Arch Linux official repository and AUR have no support for the Arch Linux based distribution, you need to maintainer your local executable environment.

**Comment by HUSTERGS** [comment]
> `Canda` is not the supported package on the Arch Linux official repository and AUR have no support for the Arch Linux based distribution, you need to maintainer your local executable environment.

Got it, thx :smile:
