### ISSUE TITLE
1.3.8 丢失一些DLL

### ISSUE THREAD

**Issue by leoxxx** [lhy0403/Qv2ray#102]
如图所示
![TIM截图20191008185240](https://user-images.githubusercontent.com/5364709/66390360-1d5ad300-e9fd-11e9-8a8e-f0b0a02fc39a.png)
![TIM截图20191008185904](https://user-images.githubusercontent.com/5364709/66390678-c0135180-e9fd-11e9-8167-71717cff1215.png)
WIN7 X64

**Comment by lhy0403** [comment]
噗，，，对不起
这是 GitHub Action 的锅，我们在 v1.3.8 尝试了使用新的 Github Action 
请试试旧版编译平台的发布版： https://jenkins.lhy0403.top/job/Qv2ray-Win32-Release/

**Comment by leoxxx** [comment]
我查了一下这DLL好像是MinGW-w64的。

**Comment by lhy0403** [comment]
感谢💗，以后发布之前会进行好相关测试！

**Comment by leoxxx** [comment]
@lhy0403 
https://github.com/lhy0403/Qv2ray/releases/tag/vTest
依旧报错，缺少DLL。

**Comment by lhy0403** [comment]
😂 哦哦这个还没有开始测试，，只是从网上看的一个方法
