### ISSUE TITLE
[2.0] 有关 Qv2ray v2.0 的 Linux 默认安装位置

### ISSUE THREAD

**Issue by lhy0403** [lhy0403/Qv2ray#103]
目前 Qv2ray 安装不论是在 AppImage (内部文件结构) `make install` 或 release 版本的 AUR 中, 安装位置均为 `/opt/Qv2ray`
在这个 Issue 中将具体讨论有关 v2.0 的默认安装位置问题

**Comment by lhy0403** [comment]
So let's ping @aliyuchang33 and @axionl 
我个人认为在 `/usr/local/bin` 更好一些，这个目录默认就在 PATH 变量里

**Comment by lhy0403** [comment]
提出此问题的原因有以下几点：
1. 现在情况下，使用 `make install` 并不能真正安装 desktop 文件和 icons 文件到正确的文件夹
2. `/usr/local/bin` 或者 `/usr/bin` 属于默认系统路径 PATH 的一部分，便于调用
3. Qv2ray 一般情况下如果使用 `make install` 安装，不会出现依赖问题，故不会在 `/opt` 目录使用某些（像别的某些）软件在 `/opt` 目录自带的库文件

**Comment by axionl** [comment]
> So let's ping @aliyuchang33 and @axionl
> 我个人认为在 `/usr/local/bin` 更好一些，这个目录默认就在 PATH 变量里

My personal suggestion on this issue is as follows, you can see the related parts of  the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=qv2ray-dev-git) and [Patch](https://aur.archlinux.org/cgit/aur.git/tree/0001-build-for-Arch-Linux.patch?h=qv2ray-dev-git).

![image](https://user-images.githubusercontent.com/8396456/66495186-6e48f500-eaeb-11e9-9774-433d7126295b.png)

- Qv2ray config path: `$HOME/.config/qv2ray`

**Comment by lhy0403** [comment]
Yes, it's more appropriate to change the default config path to `~/.config/qv2ray` following the Linux style.
and as in ArchLinux the `/bin` `/sbin` `/usr/bin` `/usr/sbin` are actually the same place, but other distro varies. I'd love to put the binary in `/usr/local/bin` instead.

**Comment by axionl** [comment]
> Yes, it's more appropriate to change the default config path to `~/.config/qv2ray` following the Linux style.
> and as in ArchLinux the `/bin` `/sbin` `/usr/bin` `/usr/sbin` are actually the same place, but other distro varies. I'd love to put the binary in `/usr/local/bin` instead.

Indeed, for Arch Linux, Pacman, as a package manager, should not touch the `/usr/local/bin` directory which is managed by the users themselves. You can keep your decision and I will make appropriate modifications for Arch Linux users.

**Comment by lhy0403** [comment]
Great then. So our final decision is:
 - ArchLinux: Make Patch to install packages in `some/bin` 
 - AppImage internal and `make install` location in `/usr/local/bin`

Let's forget about the `/opt/Qv2ray` then.
If that's ok @axionl this issue will be closed.

**Comment by axionl** [comment]
> Great then. So our final decision is:
> 
>     * ArchLinux: Make Patch to install packages in `some/bin`
> 
>     * AppImage internal and `make install` location in `/usr/local/bin`
> 
> 
> Let's forget about the `/opt/Qv2ray` then.
> If that's ok @axionl this issue will be closed.

Perhaps, setting the building target a lower-case name is more in line with Linux usage

**Comment by lhy0403** [comment]
Ok, approved.
This issue will be closed once related changes are made.

**Comment by aliyuchang33** [comment]
看不懂，用中文 doge

**Comment by lhy0403** [comment]
> 看不懂，用中文 doge

？中文括号

**Comment by code-dancing** [comment]
建议使用 AppImage这种格式包，无需安装，在网上找个图标，做一个快捷方式就行，非常方便。

![Screenshot from 2019-10-15 16-55-30](https://user-images.githubusercontent.com/26103839/66816446-ab3e3d00-ef6c-11e9-8fe3-b2e1574b1518.png)
![Screenshot from 2019-10-15 16-55-44](https://user-images.githubusercontent.com/26103839/66816457-ae392d80-ef6c-11e9-9c32-969fe325afc4.png)

**Comment by aliyuchang33** [comment]
这是个 @lhy0403

**Comment by lhy0403** [comment]
It's actually solved and I forgot to close it... so. do it now
