### ISSUE TITLE
客户端点击连接后无反应

### ISSUE THREAD

**Issue by Virpy** [lhy0403/Qv2ray#105]
manjaro发行版 linux内核5.3.5
点击连接后完全无日志 无反应 无法连接
一直显示已停止

**Comment by lhy0403** [comment]
你好，可以提供详细的截图和 console 输出吗

**Comment by Virpy** [comment]
当时情况就是我直接通过manjaro的包管理的AUR装的，没有通过console开启，GUI界面出来之后点击连接后除了按钮动画无任何反应，桌面是Xfce的。我确认我的服务器都可用。

**Comment by lhy0403** [comment]
尝试在 console 中开启一下, 文件位置应该是  `/opt/Qv2ray/bin/Qv2ray` 然后看看有没有报错之类的内容

**Comment by lhy0403** [comment]
而且请确保您把 v2ray 内核放到了 `~/.qv2ray/vcore` 目录下

**Comment by Virpy** [comment]
內核在windows下确认可以用，并且也放对了位置。至于日志，电脑暂时不在身边。

**Comment by lhy0403** [comment]
Ok

**Comment by DuckSoft** [comment]
> 內核在windows下确认可以用，并且也放对了位置。至于日志，电脑暂时不在身边。

我想请问，windows 的内核是如何在 linux 下运行的呢

**Comment by Virpy** [comment]
![image](https://user-images.githubusercontent.com/43743884/66724344-8310ea00-ee57-11e9-9394-33b800d53090.png)这是我屏幕截图，松开连接后仍旧是未连接，等待后无果

**Comment by Virpy** [comment]
> > 內核在windows下确认可以用，并且也放对了位置。至于日志，电脑暂时不在身边。
> 
> 我想请问，windows 的内核是如何在 linux 下运行的呢

 双系统啊…………

**Comment by lhy0403** [comment]
确定使用的是 linux 版本的 v2ray 而不是 windows 下的 exe 文件吗？
https://github.com/v2ray/v2ray-core/releases

**Comment by lhy0403** [comment]
尝试在右键菜单中点击 “连接到当前配置” 试一下

**Comment by Virpy** [comment]
> 确定使用的是 linux 版本的 v2ray 而不是 windows 下的 exe 文件吗？
> https://github.com/v2ray/v2ray-core/releases

…………我还以为都是一个内核呢………………………………我去换内核了

**Comment by DuckSoft** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/43743884/66724344-8310ea00-ee57-11e9-9394-33b800d53090.png)这是我屏幕截图，松开连接后仍旧是未连接，等待后无果

警告：你的 ✈️ 链接和参数已经全部暴露。小心水表。
@Virpy

**Comment by Virpy** [comment]
> > ![image](https://user-images.githubusercontent.com/43743884/66724344-8310ea00-ee57-11e9-9394-33b800d53090.png)这是我屏幕截图，松开连接后仍旧是未连接，等待后无果
> 
> 警告：你的 ✈️ 链接和参数已经全部暴露。小心水表。
> @Virpy

已删除，谢谢提醒

**Comment by DuckSoft** [comment]
@Virpy 应该已经删不掉了。记得更换服务器配置或者服务器地址吧。

**Comment by Virpy** [comment]
> @Virpy 应该已经删不掉了。记得更换服务器配置或者服务器地址吧。

谢谢提醒啦
