### ISSUE TITLE
建议更改 v2ray 内核放置提示信息

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#106]
原来不论操作系统都会说请放置 `.exe` 格式的内核，造成很多小白误解（见 #105）

**Comment by lhy0403** [comment]
Alright, I didn't expect it yet.

**Comment by lhy0403** [comment]
More fixes coming to v1.3.8.1

**Comment by DuckSoft** [comment]
可能这些地方也需要在下个版本发布前进行修复：
https://github.com/lhy0403/Qv2ray/blob/d48893e2ad35c59dd450a5d81e242d9886447979/docs/en-US/README.md#L21

https://github.com/lhy0403/Qv2ray/blob/d48893e2ad35c59dd450a5d81e242d9886447979/docs/zh-CN/README.md#L21

**Comment by lhy0403** [comment]
确实， `version-v1` 分支需要一些改动，每个版本发布时会把 `version-v1` 合并到 `master`

**Comment by lhy0403** [comment]
这个问题现在应该不存在了，因为 v2.0 将允许手动指定 v2ray 路径（甚至可能会自带 v2ray 内核）
十分感谢您的贡献！
