### ISSUE TITLE
[2.0] 【建议】v2ray内核的路径给出选择

### ISSUE THREAD

**Issue by strsikin** [lhy0403/Qv2ray#108]
默认安装后，需要到指定位置存放v2ray，能否让用户自动选择路径

**Comment by lhy0403** [comment]
会有解决方案的

**Comment by lhy0403** [comment]
https://github.com/lhy0403/Qv2ray/tree/version-v2
Version V2 已经有了解决方案，很可惜还在不稳定的 2.0 版本，因为这个功能已经实现，issue 将被关闭
