### ISSUE TITLE
[2.0] 关于实现 FOV001 的讨论

### ISSUE THREAD

**Issue by lhy0403** [lhy0403/Qv2ray#110]
Qv2ray 是否应该（需要）实现 https://github.com/v2ray/v2ray-core/issues/1569 里面 FOV001 的链接标准？

- 如果是的话，，有没有人可以帮忙写一下😂

**Comment by ZLplLQc** [comment]
以下只是个人观点。

FOV001和v2rayN的vmess没本质区别，都是把多层的json数据映射到单层的key/value对。而FOV001（我猜）为了硬套URI标准，引入了很容易和value重叠的分隔符，导致解释困难。话说URI本来就不是设计来传递复杂结构数据的啊，单是用URI做分享载体就已经不符合标准了吧。

kitsunebi有个实现是把(vmess://)到(?)之间内容用base64编码，按我的理解FOV001是全明文才对啊。再说既然都用base64编码了，为什么不整个base64呢？正如[#1569](https://github.com/v2ray/v2ray-core/issues/1569)的2楼所说，那样用正则提取链接多方便啊。

FOV001订阅标准就不讨论了。总的来说FOV001只是复杂化的vmess不建议实现。

**Comment by lhy0403** [comment]
Not to implement.
