### ISSUE TITLE
1.3.8.0在ubuntu 16.04报错，无法检测openssl

### ISSUE THREAD

**Issue by sbw983** [lhy0403/Qv2ray#112]
**简单描述这个 bug：**
1.3.8.0在ubuntu 16.04无法检测到openssl
出错信息如下
[UI]: Found Translator: en-US.qm
[UI]: Found Translator: ru-RU.qm
[UI]: Found Translator: zh-CN.qm
[INIT]: Loaded config file.
[UI]: Loaded Translator zh-CN
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_init_ssl
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_init_crypto
qt.network.ssl: QSslSocket: cannot resolve ASN1_STRING_get0_data
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_reset
qt.network.ssl: QSslSocket: cannot resolve RSA_bits
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_sk_new_null
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_sk_push
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_sk_free
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_sk_num
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_sk_pop_free
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_sk_value
qt.network.ssl: QSslSocket: cannot resolve DH_get0_pqg
qt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set_options
qt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set_ciphersuites
qt.network.ssl: QSslSocket: cannot resolve SSL_set_psk_use_session_callback
qt.network.ssl: QSslSocket: cannot resolve SSL_get_client_random
qt.network.ssl: QSslSocket: cannot resolve SSL_SESSION_get_master_key
qt.network.ssl: QSslSocket: cannot resolve SSL_session_reused
qt.network.ssl: QSslSocket: cannot resolve SSL_set_options
qt.network.ssl: QSslSocket: cannot resolve TLS_method
qt.network.ssl: QSslSocket: cannot resolve TLS_client_method
qt.network.ssl: QSslSocket: cannot resolve TLS_server_method
qt.network.ssl: QSslSocket: cannot resolve X509_STORE_CTX_get0_chain
qt.network.ssl: QSslSocket: cannot resolve X509_getm_notBefore
qt.network.ssl: QSslSocket: cannot resolve X509_getm_notAfter
qt.network.ssl: QSslSocket: cannot resolve X509_get_version
qt.network.ssl: QSslSocket: cannot resolve X509_STORE_set_ex_data
qt.network.ssl: QSslSocket: cannot resolve X509_STORE_get_ex_data
qt.network.ssl: QSslSocket: cannot resolve OpenSSL_version_num
qt.network.ssl: QSslSocket: cannot resolve OpenSSL_version
qt.network.ssl: Incompatible version of OpenSSL
[NETWORK]: Current OpenSSL version: 
[NETWORK]: Required OpenSSL version: OpenSSL 1.1.1b  26 Feb 2019
[NETWORK]: OpenSSL library MISSING, Quitting.

**如何复现这个bug：**
建议将1.3.8.0 openssl的依赖降级到1.0.2，或者把相应的库文件打包进AppImage

-

**Comment by sbw983** [comment]
已解决，谢谢

**Comment by xgdgsc** [comment]
上面链接访问不了

**Comment by lhy0403** [comment]
链接失效了，因为服务器相关原因，你可以临时自己编译一下，预计两周才能解决。
临时解决方案是找一下发行版里的  openssl  1.0 和 1.1 包进行安装
