### ISSUE TITLE
Ubuntu 16.04LTS安装失败

### ISSUE THREAD

**Issue by zr526799544** [lhy0403/Qv2ray#113]
**简单描述这个 bug：**

运行appimage 安装报错

**如何复现这个bug：**
1. 运行appimage

**相关截图或日志**

/home/toor/图片/2019-10-21 17-17-51屏幕截图.png

**系统信息**
 - 系统类型（windows, linux, macos）
    - 
 - 是从release下载的还是自己编译的
    - release
 - 首选项里的版本号：
    - 1.3.8

**Comment by zr526799544** [comment]
![2019-10-21 17-17-51屏幕截图](https://user-images.githubusercontent.com/37580152/67193035-3022ce00-f427-11e9-909a-183ca180dc6b.png)

**Comment by DuckSoft** [comment]
使用前先看使用说明。

**Comment by DuckSoft** [comment]
https://lhy0403.github.io/Qv2ray/zh-CN/

**Comment by zr526799544** [comment]
很尴尬。。。。。懒人党的失败。。。。。。。
