### ISSUE TITLE
linux fedora 无法运行.AppImage文件

### ISSUE THREAD

**Issue by wopincm** [lhy0403/Qv2ray#117]
### 执行`.AppImage`文件报错如下：

No protocol specified
qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

**Comment by lhy0403** [comment]
你好，可以试一下这个 AppImage 吗？
https://jenkins.lhy0403.top/job/Qv2ray-AppImage-Release/104/

**Comment by lhy0403** [comment]
你用的是 X 还是 Wayland？

**Comment by wopincm** [comment]
@lhy0403 我试过https://jenkins.lhy0403.top/job/Qv2ray-AppImage-Release/104/了，  还是相同的问题
我不明白你说的 `是 X 还是 Wayland`是什么意思

**Comment by lhy0403** [comment]
呃，你可以提供一下 `echo $XDG_SESSION_TYPE` 的输出吗？

**Comment by aliyuchang33** [comment]
如果我没记错的话，，，arch下的解决办法是删除相关的包然后pip install....

**Comment by lhy0403** [comment]
“相关的包”？

**Comment by aliyuchang33** [comment]
pyhon-xxx

**Comment by KnaveM** [comment]
![image](https://user-images.githubusercontent.com/33738071/68066742-b9b39380-fd77-11e9-8d78-9820bed4caa5.png)
kali 双击运行后生成一个乱码文本，运行不了

**Comment by lhy0403** [comment]
尝试过在控制台里输入： `chmod +x ./qv2ray.AppImage` 然后再运行了吗？

**Comment by wopincm** [comment]
@lhy0403 现在是正常的，就好像突然自己好了一样
