### ISSUE TITLE
你好，我按照方法构建了之后提示下载最新版，核心文件找不到

### ISSUE THREAD

**Issue by qimy0521** [lhy0403/Qv2ray#12]

**Comment by qimy0521** [comment]
使用的qt是5.12.0 py3.6

**Comment by lhy0403** [comment]
很抱歉，目前这个软件还在开发，因为从原作者那里fork过来的代码比较不友好所以删掉了很多具体功能，目前这几天正在积极重写

**Comment by lhy0403** [comment]
预计下下周 7 月 17 号之前能发出测试版

**Comment by qimy0521** [comment]
期待能早日用上

**Comment by aliyuchang33** [comment]
强烈建议移除python依赖，会gc(指gui coredump)，反正手动写个vmess解析也不难

**Comment by lhy0403** [comment]
vmess 解析暂时没有放到Beta版本的 TODO 里面，不过应该不难，V1肯定会有
 - python的依赖确实要移除的，毕竟在 Windows 里面的python还要额外配置 
（见 [FixPythonWithMinGW.bat](https://github.com/lhy0403/Hv2ray/blob/master/tools/FixPythonWithMinGW.bat)）

**Comment by lhy0403** [comment]
现在在 linux 环境下面的最新测试版 v0.9.1a 默认使用 `/bin/v2ray` 做为 v2ray 主程序位置，默认使用 `/etc/v2ray` 做为 `geoip.dat` 等资源文件位置

所以你需要：

1. 安装发行版里的 v2ray 包
2. 或者 手动修改 `~/.qv2ray/Qv2ray.conf` 文件里面的配置（因为GUI修改配置还未实现）

如果是后者的话，要从 https://github.com/v2ray/v2ray-core/releases 下载v2ray 内核

**Comment by lhy0403** [comment]
#16

**Comment by lhy0403** [comment]
>     2. 或者 手动修改 `~/.qv2ray/Qv2ray.conf` 文件里面的配置（因为GUI修改配置还未实现）
[v0.9.2a](https://github.com/lhy0403/Qv2ray/releases/tag/v0.9.2a) 版本已经可以使用 GUI 修改配置了

**Comment by lhy0403** [comment]
>     2. 或者 手动修改 `~/.qv2ray/Qv2ray.conf` 文件里面的配置（因为GUI修改配置还未实现）
[v0.9.2a](https://github.com/lhy0403/Qv2ray/releases/tag/v0.9.2a) 版本已经可以使用 GUI 修改配置了 
@qimy0521

**Comment by lhy0403** [comment]
参见  v0.9.9b https://github.com/lhy0403/Qv2ray/releases/tag/v0.9.9b
