### ISSUE TITLE
刚刚下载了最新的 Linux release，提示找不到 openssl 库

### ISSUE THREAD

**Issue by wanglongbiao** [lhy0403/Qv2ray#122]
**简单描述这个 bug：**
下载了最新的 AppImage 文件，+x 后执行，提示找不到 openssl 库
我用的系统是 xubuntu 16.04
系统上的 openssl 是最新的

![微信截图_20191030095441](https://user-images.githubusercontent.com/7327187/67822447-646b4e00-fafb-11e9-995b-b8716b88f901.png)

**Comment by lhy0403** [comment]
https://jenkins.lhy0403.top/job/Qv2ray-AppImage-Release/lastSuccessfulBuild/artifact/build/AppDir/
试试这个？

**Comment by wanglongbiao** [comment]
上面这个报错提示找不到 v2ray 核心文件
![微信截图_20191030095953](https://user-images.githubusercontent.com/7327187/67822941-21f64100-fafc-11e9-9737-2c2f8ade6fee.png)

**Comment by lhy0403** [comment]
https://lhy0403.github.io/Qv2ray
