### ISSUE TITLE
windows 1.3.8.0版，删除Alter ID默认值时，应用崩溃

### ISSUE THREAD

**Issue by quanqinle** [lhy0403/Qv2ray#123]
**简单描述这个 bug：**
打开应用（windows 1.3.8.0版），在【编辑链接设置】界面，鼠标选中Alter ID输入框中的全部默认值，然后删除，此时应用崩溃。

**Comment by lhy0403** [comment]
这是个已知 bug

**Comment by lhy0403** [comment]
会在2.0统一修复
临时解决方案是 在alter id处全选，直接输入数字

**Comment by lhy0403** [comment]
@quanqinle 问题解决了嘛？

**Comment by quanqinle** [comment]
问题解决。临时方案可以规避问题。
