### ISSUE TITLE
HTTP & Socks 前置代理支持

### ISSUE THREAD

**Issue by gudong321** [lhy0403/Qv2ray#125]
1. 在公司的http_proxy代理网络环境中，无法通过Qv2ray客户端软件连梯子上网了，vmess协议或shadowsocks协议都不行，只能在家里或其他无代理环境等地方使用，很不方便。
2. 一般的shadowsocks客户端软件都有“正向代理”功能，咱们的v2ray客户端软件是不是也可以提供这样的功能？即能在代理环境中连接梯子？这样就完美了！十分期待！

**Comment by lhy0403** [comment]
你好，v2ray 前置代理需要自己编写配置文件进行设置
https://github.com/v2ray/v2ray-core/issues/1736

**Comment by lhy0403** [comment]
Should we add this feature?
(Only for simple single outbound configs) @aliyuchang33 @axionl

**Comment by aliyuchang33** [comment]
sb

**Comment by aliyuchang33** [comment]
@lhy0403 你就是菜鸡，v2ray支持前置代理

**Comment by lhy0403** [comment]
See: https://github.com/v2ray/discussion/issues/129

**Comment by lhy0403** [comment]
禁止暴躁（ @aliyuchang33

**Comment by axionl** [comment]
> Should we add this feature?
> (Only for simple single outbound configs) @aliyuchang33 @axionl

There is no such requirement for me personally, and I can edit the configuration file to implement it. Adding new controls may make the original setting panel more complex. But if you want to do it, you can do it.

**Comment by aliyuchang33** [comment]
你要想用代理链的话，是linus平台可以用proxychains

**Comment by lhy0403** [comment]
I'll try to implement it as a global setting (only for single outbound config.) 
It *should* be easy as just a few outbounds, inbounds, and routes need to be added.

Mention #69 LMAO

**Comment by gudong321** [comment]
Thank you for your serious  and contribution！ @lhy0403 @axionl

**Comment by gudong321** [comment]
@lhy0403 https://static.lhy0403.top/payment/alipay.jpg 你好，发现这个打不开

**Comment by lhy0403** [comment]
emmmmm 网站服务器更新了，，，得等一段时间，
您可以留着钱给自己买雪碧😂

**Comment by aliyuchang33** [comment]
lmao

**Comment by lhy0403** [comment]
Things just changed.

**Comment by lhy0403** [comment]
@aliyuchang33 Should we still implement proxychains if the stream settings has been dropped when using forward proxy?

**Comment by aliyuchang33** [comment]
No need in my opinion.

**Comment by lhy0403** [comment]
@DuckSoft @axionl @thebadgateway 

What's your opinion guys?

**Comment by lhy0403** [comment]
Sorry for the long delay, but it’s now been fixed in the dev branch, would someone have a test?

**Comment by lhy0403** [comment]
Sorry for the long delay, but it’s now been fixed in the dev branch, would someone have a test?

**Comment by gudong321** [comment]
- 测试环境 ：windows 10
- 软件版本：Qv2ray-refs.tags.v1.99.5-win64
- 代理选择：HTTP
- DNS选择：本地DNS & 软件推荐DNS
- 代理情况：未成功
- 日志如下（私有ip已脱敏）：
V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 windows/amd64)
A unified platform for anti-censorship.
2020/01/21 09:37:26 [Debug] v2ray.com/core/app/log: Logger started
2020/01/21 09:37:26 [Info] v2ray.com/core/app/dns: DNS: created udp client inited for 8.8.4.4:53
2020/01/21 09:37:26 [Info] v2ray.com/core/app/dns: DNS: created udp client inited for 1.1.1.1:53
2020/01/21 09:37:26 [Info] v2ray.com/core/app/dns: DNS: created localhost client
2020/01/21 09:37:26 [Debug] v2ray.com/core/app/stats: create new counter inbound>>>_QV2RAY_API_INBOUND_>>>traffic>>>uplink
2020/01/21 09:37:26 [Debug] v2ray.com/core/app/stats: create new counter inbound>>>_QV2RAY_API_INBOUND_>>>traffic>>>downlink
2020/01/21 09:37:26 [Debug] v2ray.com/core/app/proxyman/inbound: creating stream worker on 127.0.0.1:15490
2020/01/21 09:37:26 [Debug] v2ray.com/core/app/stats: create new counter inbound>>>http_IN>>>traffic>>>uplink
2020/01/21 09:37:26 [Debug] v2ray.com/core/app/stats: create new counter inbound>>>http_IN>>>traffic>>>downlink
2020/01/21 09:37:26 [Debug] v2ray.com/core/app/proxyman/inbound: creating stream worker on 127.0.0.1:8888
2020/01/21 09:37:26 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:15490
2020/01/21 09:37:26 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:8888
2020/01/21 09:37:26 [Warning] v2ray.com/core: V2Ray 4.22.1 started
2020/01/21 09:37:26 [Debug] [1595673333] v2ray.com/core/proxy/dokodemo: processing connection from: 127.0.0.1:52656
2020/01/21 09:37:26 [Info] [1595673333] v2ray.com/core/app/dispatcher: taking detour [_QV2RAY_API_] for [tcp:127.0.0.1:0]
2020/01/21 09:37:50 [Info] [2658146860] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [www.google.com:443] with URL [//www.google.com:443]
2020/01/21 09:37:50 [Debug] v2ray.com/core/app/dns: UDP:8.8.4.4:53 querying DNS for: www.google.com.
2020/01/21 09:37:50 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:8.8.4.4:53
2020/01/21 09:37:50 [Info] v2ray.com/core/transport/internet/udp: establishing new connection for udp:8.8.4.4:53
2020/01/21 09:37:50 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:8.8.4.4:53
2020/01/21 09:37:50 [Info] v2ray.com/core/app/dispatcher: default route for udp:8.8.4.4:53
2020/01/21 09:37:50 [Info] v2ray.com/core/transport/internet/kcp: dialing mKCP to udp:149.28.146.245:52126
2020/01/21 09:37:50 [Info] [15932425] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [www.gstatic.com:443] with URL [//www.gstatic.com:443]
2020/01/21 09:37:50 [Info] [469362692] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [apis.google.com:443] with URL [//apis.google.com:443]
2020/01/21 09:37:50 [Debug] v2ray.com/core/app/dns: UDP:8.8.4.4:53 querying DNS for: apis.google.com.
2020/01/21 09:37:50 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:8.8.4.4:53
2020/01/21 09:37:50 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:8.8.4.4:53
2020/01/21 09:37:50 [Debug] v2ray.com/core/app/dns: UDP:8.8.4.4:53 querying DNS for: www.gstatic.com.
2020/01/21 09:37:50 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:8.8.4.4:53
2020/01/21 09:37:50 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:8.8.4.4:53
2020/01/21 09:37:50 [Info] v2ray.com/core/transport/internet/kcp: #63736 creating connection to 149.28.146.245:52126
2020/01/21 09:37:50 [Info] v2ray.com/core/proxy/vmess/outbound: tunneling request to udp:8.8.4.4:53 via tcp:xxx.xxx.xxx.xxx:xxxxx
2020/01/21 09:37:50 [Info] [4199143244] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [www.google.com:443] with URL [//www.google.com:443]
2020/01/21 09:37:50 [Debug] v2ray.com/core/app/dns: UDP:8.8.4.4:53 querying DNS for: www.google.com.
2020/01/21 09:37:50 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:8.8.4.4:53
2020/01/21 09:37:50 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:8.8.4.4:53
2020/01/21 09:37:54 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain www.google.com at server UDP:8.8.4.4:53 > context deadline exceeded
2020/01/21 09:37:54 [Debug] v2ray.com/core/app/dns: UDP:1.1.1.1:53 querying DNS for: www.google.com.
2020/01/21 09:37:54 [Debug] v2ray.com/core/transport/internet/kcp: #63736 entering state 1 at 3993
2020/01/21 09:37:54 [Info] v2ray.com/core/transport/internet/kcp: #63736 closing connection to xxx.xxx.xxx.xxx:xxxxx
2020/01/21 09:37:54 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:1.1.1.1:53
2020/01/21 09:37:54 [Info] v2ray.com/core/transport/internet/udp: establishing new connection for udp:1.1.1.1:53
2020/01/21 09:37:54 [Info] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled
2020/01/21 09:37:54 [Info] v2ray.com/core/transport/internet/udp: failed to handle UDP input > io: read/write on closed pipe
2020/01/21 09:37:54 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:1.1.1.1:53
2020/01/21 09:37:54 [Info] v2ray.com/core/app/dispatcher: default route for udp:1.1.1.1:53
2020/01/21 09:37:54 [Info] v2ray.com/core/transport/internet/kcp: dialing mKCP to udp:xxx.xxx.xxx.xxx:xxxxx
2020/01/21 09:37:54 [Info] v2ray.com/core/transport/internet/kcp: #63737 creating connection to xxx.xxx.xxx.xxx:xxxxx
2020/01/21 09:37:54 [Info] v2ray.com/core/proxy/vmess/outbound: tunneling request to udp:1.1.1.1:53 via tcp:xxx.xxx.xxx.xxx:xxxxx
2020/01/21 09:37:54 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain apis.google.com at server UDP:8.8.4.4:53 > context deadline exceeded
2020/01/21 09:37:54 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain www.gstatic.com at server UDP:8.8.4.4:53 > context deadline exceeded
2020/01/21 09:37:54 [Debug] v2ray.com/core/app/dns: UDP:1.1.1.1:53 querying DNS for: apis.google.com.
2020/01/21 09:37:54 [Debug] v2ray.com/core/app/dns: UDP:1.1.1.1:53 querying DNS for: www.gstatic.com.
2020/01/21 09:37:54 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:1.1.1.1:53
2020/01/21 09:37:54 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:1.1.1.1:53
2020/01/21 09:37:54 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:1.1.1.1:53
2020/01/21 09:37:54 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:1.1.1.1:53
2020/01/21 09:37:54 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain www.google.com at server UDP:8.8.4.4:53 > context deadline exceeded
2020/01/21 09:37:54 [Debug] v2ray.com/core/app/dns: UDP:1.1.1.1:53 querying DNS for: www.google.com.
2020/01/21 09:37:54 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:1.1.1.1:53
2020/01/21 09:37:54 [Debug] v2ray.com/core/transport/internet/udp: dispatch request to: udp:1.1.1.1:53
2020/01/21 09:37:58 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain www.google.com at server UDP:1.1.1.1:53 > context deadline exceeded
2020/01/21 09:37:58 [Debug] v2ray.com/core/transport/internet/kcp: #63737 entering state 1 at 4000
2020/01/21 09:37:58 [Info] v2ray.com/core/transport/internet/kcp: #63737 closing connection to xxx.xxx.xxx.xxx:xxxxx
2020/01/21 09:37:58 [Info] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: connection ends > context canceled
2020/01/21 09:37:58 [Info] v2ray.com/core/transport/internet/udp: failed to handle UDP input > io: read/write on closed pipe
2020/01/21 09:37:58 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain www.gstatic.com at server UDP:1.1.1.1:53 > context deadline exceeded
2020/01/21 09:37:58 [Info] v2ray.com/core/app/dns: failed to lookup ip for domain apis.google.com at server UDP:1.1.1.1:53 > context deadline exceeded

**Comment by gudong321** [comment]
@另外，Deepin Linux下也未代理成功，年后弄也行，辛苦了@lhy0403
