### ISSUE TITLE
啥时候添加订阅功能

### ISSUE THREAD

**Issue by chaichunyang** [lhy0403/Qv2ray#126]
**简单描述这个 bug：**
机场一个一个添加很麻烦

**如何复现这个bug：**
1. 什么时候添加订阅功能呢？

**Comment by lhy0403** [comment]
（快了

**Comment by axionl** [comment]
> （快了

Please consider adding a new  issue template for `feature request` and try the format auto-check.

**Comment by lhy0403** [comment]
@axionl  Sure, Thanks!

**Comment by ntgeralt** [comment]
第一次运行提示找不到v2文件时，可以直接提示v2文件应该放哪里。其实最好直接打包一起，也不差那17MB。

第一次启动时，提示未启动http规则，可以预先直接启用分流规则或pac模式

**Comment by lhy0403** [comment]
#121

**Comment by lhy0403** [comment]
Subscription is partly supporting, using it is OK, but not expected to be robost.
More features on the way.

**Comment by lhy0403** [comment]
Subscription issues goes here please.

**Comment by huyizheng** [comment]
报个bug：订阅出来的节点无法在“自动连接”里选择。

**Comment by lhy0403** [comment]
好

**Comment by lhy0403** [comment]
Subscriptions should be fully supported now. Closing.
