### ISSUE TITLE
Contact me

### ISSUE THREAD

**Issue by thebadgateway** [lhy0403/Qv2ray#127]
Write me, I have a commercial offer for you.
https://t.me/thebadgateway

**Comment by lhy0403** [comment]
Sorry, but I don't accept commercial offers BTW.

**Comment by thebadgateway** [comment]
> Sorry, but I don't accept commercial offers
> Thanks a lot BTW.
I wanted to buy a Qv2ray.

**Comment by lhy0403** [comment]
Sorry I didn't fully understand.
Qv2ray is licenced under GPLv3, you may ask for any features, or 'pull request' a new feature if you wish.
I don't accept any paid/non-paid feature requests with time limitations. It will only make a mess in my life.
And you CAN have your fork of Qv2ray, but you need to keep the same License, and should not distribute it in any close-source form (See GPLv3)

I don't accept any feature requests in private. Me personally will not make any 'privately distributed' version of Qv2ray.

Sorry about the inconvenience.
[Please point me out if I misunderstood your idea.]
