### ISSUE TITLE
请问如何配置git走v2ray

### ISSUE THREAD

**Issue by 381162797** [lhy0403/Qv2ray#128]
尝试过git config --global http.proxy http://127.0.0.1:10808无效

**Comment by lhy0403** [comment]
https://gist.github.com/evantoli/f8c23a37eb3558ab8765
http://cms-sw.github.io/tutorial-proxy.html
善用搜索

**Comment by axionl** [comment]
Enable the `HTTP Inbound Settings` and setting the correct port for the HTTP proxy.
