### ISSUE TITLE
[Visual Design] Icon design draft with breeze style.

### ISSUE THREAD

**Issue by axionl** [lhy0403/Qv2ray#130]
![Qv2ray_Banner](https://user-images.githubusercontent.com/8396456/68696206-8236b980-05b7-11ea-99d5-267789b288df.png)

## Description:
My design was inspired by V2ray's radial icon. A bird standing on `Q`indicates that the project was built on Qt and it's lightweight. If there is a problem with the design, please feel free to suggest it below. If there is no change, I will continue to implement the system tray icon.

- Color specification: https://hig.kde.org/style/color/default.html
- Fonts: [Noto Sans](https://fonts.adobe.com/fonts/noto-sans) and self-designed font for the `Q`
- Application Icon Preview:
    - 128x128
![Qv2ray128x128](https://user-images.githubusercontent.com/8396456/68696370-d3df4400-05b7-11ea-8e14-bc0e56c215d4.png)

    - Application launcher
![image](https://user-images.githubusercontent.com/8396456/68696513-16088580-05b8-11ea-8cd1-34028a125bc2.png)
- Icon preview collection:
https://github.com/lhy0403/Qv2ray/issues/130#issuecomment-553457532

**Comment by lhy0403** [comment]
That'll be super cool.
I'd prefer to add a `v2ray` after that Q, to make more sense of the logo.
Will the area after Q be able to store 5 more characters? Will it make the whole icon look complicated?

I'm not good at designing and I know it'll make a designer mad if someone continuously changes the needs.
But is it possible to make aother flat logo like those, (I mean another simpler logo just for system tray area, because a dark logo isn't that good-looking)?

![image](https://user-images.githubusercontent.com/18734999/68660355-f3ed1400-0573-11ea-9b43-419031615e39.png)

**Comment by axionl** [comment]
> That'll be super cool.
> I'd prefer to add a `v2ray` after that Q, to make more sense of the logo.
> Will the area after Q be able to store 5 more characters? Will it make the whole icon look complicated?
> 
> I'm not good at designing and I know it'll make a designer mad if someone continuously changes the needs.
> But is it possible to make aother flat logo like those, (I mean another simpler logo just for system tray area, because a dark logo isn't that good-looking)?
> 
> ![image](https://user-images.githubusercontent.com/18734999/68660355-f3ed1400-0573-11ea-9b43-419031615e39.png)

As mentioned above, I will continue to design the system tray icon based on this icon.

**Comment by axionl** [comment]
- System tray icons preview:
![image](https://user-images.githubusercontent.com/8396456/68695790-b1006000-05b6-11ea-9687-3a3f2124b7a5.png)
![Qv2ray_System_Tray_256x256](https://user-images.githubusercontent.com/8396456/68695854-c5445d00-05b6-11ea-8c28-82fef7808407.png)
- Application icon update:
![qv2ray](https://user-images.githubusercontent.com/8396456/68695873-cb3a3e00-05b6-11ea-807d-220bbf66904b.png)

**Comment by lhy0403** [comment]
Is it able to have two different icons (I mean different colours of Q) to distinguish different connection status?

It's AMAZING! however.. if that's too difficult it'll be ok to use one icon though

**Comment by lhy0403** [comment]
It's really amazing

**Comment by aliyuchang33** [comment]
Q下面那点绿能渐变一下么，还有能给个蓝色版本配色的么？

**Comment by axionl** [comment]
Here is the source file, you can easily open it with drawing software like `Inkscape` and modify the color of the component.

![image](https://user-images.githubusercontent.com/8396456/68731785-2f3b2180-060c-11ea-94a8-9aab191c7424.png)


[Qv2ray_Icons_Design.zip](https://github.com/lhy0403/Qv2ray/files/3839333/Qv2ray_Icons_Design.zip)

sha256sums: `bcb2579788190d4a425e5e2ec20e909dd19c2c9ccb913b09452cd0950f68d6b3`

**Comment by axionl** [comment]
> Q下面那点绿能渐变一下么，还有能给个蓝色版本配色的么？

- Blue version:
![image](https://user-images.githubusercontent.com/8396456/68732531-b8ebee80-060e-11ea-8243-e027e1be9ec3.png)
- Green version:
![image](https://user-images.githubusercontent.com/8396456/68732659-2ac43800-060f-11ea-9219-547c7d4caa60.png)
- System tray icon gray version:
![image](https://user-images.githubusercontent.com/8396456/68732551-cacd9180-060e-11ea-9b67-4ed8ccb32ae7.png)
> [Qv2ray_Icons_Color_Test.zip](https://github.com/lhy0403/Qv2ray/files/3839395/Qv2ray_Icons_Color_Test.zip)
sha256sums: `dfe788d22c6340024f805f5fe48bcea10ef6b7968e9780c22172a53b87a9661c`

**Comment by axionl** [comment]
## A pixel simplified graph for system tray

![Pixel_Fixed](https://user-images.githubusercontent.com/8396456/68742540-610fb080-062b-11ea-94c0-a75f7b15a866.png)
- Dark color:
![image](https://user-images.githubusercontent.com/8396456/68742603-88ff1400-062b-11ea-8716-eb17011a7878.png)
- Light color:
![2019-11-13_15-54](https://user-images.githubusercontent.com/8396456/68743634-dbd9cb00-062d-11ea-9a26-899a88ca3b71.png)

**Comment by lhy0403** [comment]
@aliyuchang33 Well I prefer the green version (For Qt), and @axionl this tray bird isn't making it easy to recognize what the program does, I think we need a Q or something related.
BTW I just added a dark mode so yes, thanks for your dark mode logo again.

**Comment by thebadgateway** [comment]
Green the best!

**Comment by thebadgateway** [comment]
99% of the logo designs are not related to the program.

**Comment by lhy0403** [comment]
@thebadgateway Yes I do agree but the bird and the line it `staning` on makes me think it's a task manager (with CPU graph LMAO).... Maybe it's my personal problem 😊

**Comment by thebadgateway** [comment]
> Yes I do agree but the bird and the line it `staning` on makes me think it's a task manager (with CPU graph LMAO).... Maybe it's my personal problem

Bird monitors traffic.

**Comment by thebadgateway** [comment]
You are too nitpicking. The letter Q is the personification of this unusual bird.

**Comment by lhy0403** [comment]
Alright 😂 I accept the changes.

**Comment by lhy0403** [comment]
@axionl I added a macro `QV2RAY_USE_BUILTIN_DARKTHEME` defined as `true` by default to indicate Qv2ray to handle dark mode UI itself (ignoring system settings) feel free to change it in AUR if it should use the system color settings
The chart color scheme can still be changed manually because it cannot be changed from the system's color settings.

**Comment by axionl** [comment]
- For the dark module
I don't know how the dark icon theme works in a variety of desktop environments, and I prefer to give users a checkbox to choose if it is convenient for you to implement.

- About the symbol of Qt
The system tray icon with "Q" ( see`Qv2ray_System_Tray.svg`) has also been considered. Since, for most users, they are still not sure what it means and it is too complicated to be pixelated that I just keep it in the application icon.

- Others:
By the way, do you consider creating a temporary development group on the telegram?

**Comment by aliyuchang33** [comment]
idfc

**Comment by lhy0403** [comment]
@axionl I have added a checkbox enabling a dark mode in the preference window.
- If `QV2RAY_USE_BUILTIN_DARKTHEME` is set to `true` during the build.
    - The setting in the Preference Window will override the system settings, which is:
        - KDE and Qt-Based DEs: It can override color schemes set in the PlasmaSettings.
        - GNOME: I don't think there no such setting for Qt, but there is a `qt5ct` for you to change the Qt's own global color scheme.
    - And, disable the theme selection feature, because other themes may break the color palette.
 - else, if `QV2RAY_USE_BUILTIN_DARKTHEME` is set to `false` during the build:
    - This dark-mode setting option in the Preference Window will only change the UI for that chart in Main Window.
        - Because the Qt Chart Theme cannot be modified anywhere else except in the code.

**Comment by axionl** [comment]
@lhy0403 

![image](https://user-images.githubusercontent.com/8396456/68778401-19f6df00-066e-11ea-8b04-ce1611126094.png)

All the icons have been drawn. In addition, Icons could be enlarged to view.

**Comment by lhy0403** [comment]
Yay!
That's really cool @axionl Thanks a lot for your hard work!

Please, can you commit it into a new branch called `dev-logos` IF THIS CHECK passes?
https://github.com/lhy0403/Qv2ray/commit/390f3ba9e1fea3760fe676c3578326113e3196b7/checks?check_suite_id=309194076

Or I may do it tomorrow if you are busy?

**Comment by axionl** [comment]
I hope that you can help me with it. 

Notice that the icno for the `About` interface defaults to using the system tray icon, please consider replacing it with the app icon or the banner above.

![image](https://user-images.githubusercontent.com/8396456/68783864-a0172380-0676-11ea-9bae-38bec57d58d1.png)

**Comment by lhy0403** [comment]
@axionl Please feel free to open a pull request against `dev-logos` or directly push to the `https://github.com/lhy0403/Qv2ray/tree/dev-logos` branch.

I'll make changes accordingly. Thanks

**Comment by axionl** [comment]
@lhy0403 

Forgot to remind you, the branch has been updated.

https://github.com/lhy0403/Qv2ray/commit/606dfd337189c563847798ae4bd9177054e5b180

**Comment by lhy0403** [comment]
Yeah I just saw that. Thanks

**Comment by lhy0403** [comment]
@axionl as far as I know, windows taskbar does not support SVG formatted imgs so we need to change all the images into PNG format.
...
By the way I think we need two sets of ui icons, (like share, import, ping and.....) for both light and dark theme. Can you suggest a color that I may use in the dark theme?

**Comment by axionl** [comment]
- SVG to png conversions can be easily done using scripts and `imagemagick`.

Example:
```shell
for file in ./*.svg; do
        convert -background none "$file" "`basename "$file" .svg`".png;
done
```

- ui icons
The icons are all solid and can be converted in Inkscape, I hope you can help me...

**Comment by lhy0403** [comment]
Just the app icons (the one shown in the windows taskbar) needs to be converted. Thank you for your scripts.
I'll do it myself creating the light colour set.

**Comment by huyizheng** [comment]
最新的dev-logo分支编译出来的版本，在kde里托盘图标是空的，亮色和暗色微风主题下都是。

**Comment by lhy0403** [comment]
@huyizheng devlogo 部分问题还没有处理完😊

**Comment by lhy0403** [comment]
License for those SVGs are......? @axionl

**Comment by lhy0403** [comment]
@axionl Some basic work is done. Please check if more tweaks are required in the PR #131

**Comment by axionl** [comment]
> License for those SVGs is......? @axionl

`CC-BY-NC` license is enough.

**Comment by axionl** [comment]
![image](https://user-images.githubusercontent.com/8396456/68996672-29796080-08d8-11ea-9523-e0dfa8360f23.png)
typo?

**Comment by axionl** [comment]
I hope that alignment can be achieved here, between the hosts and log lists.

**Comment by lhy0403** [comment]
> ![image](https://user-images.githubusercontent.com/8396456/68996672-29796080-08d8-11ea-9523-e0dfa8360f23.png)
> typo?

Yeah. the typo is fixed, but what did you mean by: "achieve the alignment" here? 

![image](https://user-images.githubusercontent.com/18734999/69002316-ce6f5a00-0927-11ea-8790-4c687c4c54f6.png)

**Comment by axionl** [comment]
@lhy0403 

![IMG_20191117_130315~2.jpg](https://i.loli.net/2019/11/17/XoduwU2CreYmfx4.jpg)

**Comment by lhy0403** [comment]
I still didn’t understand.....
Can you provide a better explanation?

**Comment by lhy0403** [comment]
>  By the way, do you consider creating a temporary development group on the telegram?

I'd say no, as there's not so many developers, if there are more than 15 contributors, I may consider.

**Comment by axionl** [comment]
> I still didn’t understand.....
> Can you provide a better explanation?

![2019-11-17_20-17](https://user-images.githubusercontent.com/8396456/69007323-4c0e8680-0977-11ea-8ca2-4aa4ed9d2a92.png)

**Comment by lhy0403** [comment]
I don't suggest doing so. layout in a pure grid will make the UI looks stupid (in other word, dull or monotonous)

**Comment by huyizheng** [comment]
![Screenshot_20191117_203718](https://user-images.githubusercontent.com/22879638/69007568-54b48c00-097a-11ea-8541-0e5da8cafa9e.png)
最新的dev-logo分支编译的结果，在窗口宽度过小的时候按钮图标会错位。
即目前版本的最小窗口宽度不能容纳所有按钮的图标，可能需要把窗口的最小宽度加大一点。

**Comment by lhy0403** [comment]
@huyizheng OK!

**Comment by axionl** [comment]
> I don't suggest doing so. layout in a pure grid will make the UI looks stupid (in another word, dull or monotonous).
> You may try to modify yourself. And have a try.

Well, but I still cannot control the size of the speed graph.

**Comment by lhy0403** [comment]
Sorry I meant to modify the UI in QtCreator, and rebuild it from the source.
You may need to break the layout and re-create a grid-layout containing all 4 parts (HostList, HostDetail, Log and the Chart).

**Comment by axionl** [comment]
Sorry, I accidentally clicked the wrong button to close the issue, now it is reopened.

**Comment by axionl** [comment]
![image](https://user-images.githubusercontent.com/8396456/69007797-8ed35d00-097d-11ea-9522-151c2d990557.png)

Unnecessary checkbox?

Build on: https://github.com/lhy0403/Qv2ray/commit/fb6a5ec147b0adf3adc9fc6ebb4ab490f5865a47

**Comment by huyizheng** [comment]
> @huyizheng OK!
> 现在的窗口限制是 740*590 ，您可以确认一下吗？
> 可能是您的字体太大导致的

我这里也是这个数。

**Comment by lhy0403** [comment]
> ![image](https://user-images.githubusercontent.com/8396456/69007797-8ed35d00-097d-11ea-9522-151c2d990557.png)
> 
> Unnecessary checkbox?
> 
> Build on: [fb6a5ec](https://github.com/lhy0403/Qv2ray/commit/fb6a5ec147b0adf3adc9fc6ebb4ab490f5865a47)

Sorry.... Accident

**Comment by axionl** [comment]
What about the traffic statistics icon?
![image](https://user-images.githubusercontent.com/8396456/69011250-a45b7d80-09a3-11ea-9502-bba93f101696.png)
[traffic_statistics_btn.zip](https://github.com/lhy0403/Qv2ray/files/3855883/traffic_statistics_btn.zip)

**Comment by thebadgateway** [comment]
[Click](https://i.yapx.ru/FvXUZ.png) I do not see the tray icon.

**Comment by lhy0403** [comment]
Yes there IS an icon. And please change the setting of `DarkMode Icon` in prefrence window. See if that helps?

**Comment by lhy0403** [comment]
As we are not able to detect the colour of users' tray colour. This could be the only method of changing the tray Icon... sorry about that.

**Comment by thebadgateway** [comment]
I apologize, did not manage to delete the comment when I found it myself. But you were faster with the answer.

**Comment by DuckSoft** [comment]
> 
> 
> ![Qv2ray_Banner](https://user-images.githubusercontent.com/8396456/68696206-8236b980-05b7-11ea-99d5-267789b288df.png)
> ## Description:
> 
> My design was inspired by V2ray's radial icon. A bird standing on `Q`indicates that the project was built on Qt and it's lightweight. If there is a problem with the design, please feel free to suggest it below. If there is no change, I will continue to implement the system tray icon.
> 
>     * Color specification: https://hig.kde.org/style/color/default.html
> 
>     * Fonts: [Noto Sans](https://fonts.adobe.com/fonts/noto-sans) and self-designed font for the `Q`
> 
>     * Application Icon Preview:
>       
>       * 128x128
>         ![Qv2ray128x128](https://user-images.githubusercontent.com/8396456/68696370-d3df4400-05b7-11ea-8e14-bc0e56c215d4.png)
>       * Application launcher
>         ![image](https://user-images.githubusercontent.com/8396456/68696513-16088580-05b8-11ea-8cd1-34028a125bc2.png)
> 
>     * Icon preview collection:
>       [#130 (comment)](https://github.com/lhy0403/Qv2ray/issues/130#issuecomment-553457532)

Shall it be `Qv2ray` instead of `QV2ray` in your logo?

**Comment by lhy0403** [comment]
Actually, the official name is with capital V... But Qv2ray misused as small v. which accidentally makes this name pretty good looking (Maybe?) We need a further discussion.

**Comment by lhy0403** [comment]
I think this could be closed as solved?

**Comment by lhy0403** [comment]
eeeeeexcept that V issue...

**Comment by axionl** [comment]
Closed
