### ISSUE TITLE
dev build不了，加一下dokodemo的入站，tproxy开启了就加

### ISSUE THREAD

**Issue by aliyuchang33** [lhy0403/Qv2ray#136]
RT

**Comment by lhy0403** [comment]
PR welcome

**Comment by aliyuchang33** [comment]
day dreaming

**Comment by lhy0403** [comment]
TProxy is for complex configs, where should be edited in the RouteEditor, where users can fully handle the config file, where Qv2ray behaves much like a text editor only. 
This issue is invalid as there's already a `dokodemo-door` support in the route editor.

**Comment by aliyuchang33** [comment]
你edit里边没有inbound edit的功能，只有out和routing，所以想自己编辑都没办法

**Comment by lhy0403** [comment]
v2 没有写完

**Comment by lhy0403** [comment]
临时解决方案有json编辑器

**Comment by lhy0403** [comment]
Closed as solved.
