### ISSUE TITLE
windows通过二维码导入配置后无法科学上网

### ISSUE THREAD

**Issue by HOMHOG** [lhy0403/Qv2ray#140]

**Comment by lhy0403** [comment]
more info？

**Comment by HOMHOG** [comment]
qv2ray is so simple,i don't know what kind of info can i provide

**Comment by DuckSoft** [comment]
then you are too naive

**Comment by DuckSoft** [comment]
Provide with us the exact steps to reproduce the problem.

**Comment by lhy0403** [comment]
Well at least did you set system proxy in your browser or system or .... application?

**Comment by HOMHOG** [comment]
no

**Comment by DuckSoft** [comment]
If you are not good at describe things, then don't. Screenshots or clip of video will do.

**Comment by HOMHOG** [comment]
> Well at least did you set system proxy in your browser or system or .... application?

No

**Comment by DuckSoft** [comment]
I don’t think scanning a QR code will trigger this problem. Have you checked your proxy setting? If not, you may need to configure your browser to use Qv2ray proxy.

**Comment by HOMHOG** [comment]
Can you read Chinese? I want to discrib by Chinse

**Comment by DuckSoft** [comment]
Do it then.

**Comment by HOMHOG** [comment]
我的v2ray 配置mac电脑和手机上都是可以的，我只是打开qV2ray通过二维码添加了配置，提示连接成功了，但是浏览器不能访问google

**Comment by DuckSoft** [comment]
> 我的v2ray 配置mac电脑和手机上都是可以的，我只是打开qV2ray通过二维码添加了配置，提示连接成功了，但是浏览器不能访问google

您可能需要调整浏览器的“代理设置”，以使浏览器使用 Qv2ray 作为其代理。

**Comment by HOMHOG** [comment]
我试下

**Comment by HOMHOG** [comment]
> > 我的v2ray 配置mac电脑和手机上都是可以的，我只是打开qV2ray通过二维码添加了配置，提示连接成功了，但是浏览器不能访问google
> 
> 您可能需要调整浏览器的“代理设置”，以使浏览器使用 Qv2ray 作为其代理。

不好意思 Chrome能指定软件作为代理？

**Comment by lhy0403** [comment]
Chrome is using system proxy settings. If you are using Qv2ray 2.0 alpha 1, please try switching on `set system proxy` in  the  `Inbound Settings` tab in the `Prefrences Window`

**Comment by DuckSoft** [comment]
默认情况下，Qv2ray 会在连接节点后，在 127.0.0.1 的 1080 端口启动 SOCKS5 代理。请将浏览器指向这个代理即可。

**Comment by DuckSoft** [comment]
或者，您可以考虑使用第三方的代理切换插件，如 SwitchyOmega 等。

**Comment by HOMHOG** [comment]
> 或者，您可以考虑使用第三方的代理切换插件，如 SwitchyOmega 等。

我知道这个 我期望q2ray本身就能做到更方便，放弃了

**Comment by DuckSoft** [comment]
> > 或者，您可以考虑使用第三方的代理切换插件，如 SwitchyOmega 等。
> 
> 我知道这个 我期望q2ray本身就能做到更方便，放弃了



> Chrome is using system proxy settings. If you are using Qv2ray 2.0 alpha 1, please try switching on `set system proxy` in the `Inbound Settings` tab in the `Prefrences Window`

那么，此方案即可。

**Comment by DuckSoft** [comment]
@lhy0403 should we label this issue?

**Comment by lhy0403** [comment]
Sure

**Comment by HOMHOG** [comment]
> Chrome is using system proxy settings. If you are using Qv2ray 2.0 alpha 1, please try switching on `set system proxy` in the `Inbound Settings` tab in the `Prefrences Window`

I use 1.99.2.919,I want to know every one use qV2ray on windows should do this after config the server?

**Comment by lhy0403** [comment]
No, @HOMHOG this auto-setup will be set to automatically enabled before final release

**Comment by HOMHOG** [comment]
> No, @HOMHOG this auto-setup will be set to automatically enabled before final release

Thanks for your reply.

**Comment by HOMHOG** [comment]
@lhy0403 @DuckSoft Problem solved,I just check up the "http" item below the inbound setting,then it's OK,I wonder why this is not automatic.

**Comment by lhy0403** [comment]
The alpha v2 version is still under development, please feel free to report any further bugs :+1:

**Comment by HOMHOG** [comment]
> The alpha v2 version is still under development, please feel free to report any further bugs 👍

No problem,👍
