### ISSUE TITLE
pac无法实现，本人系统deepin15.11(debian分支)

### ISSUE THREAD

**Issue by kingskill** [lhy0403/Qv2ray#141]
“入站设置”中，pac支持这一项已经打钩，但是不起作用，无效。而且pac只能选择http代理服务器，无法选择socks。强行选择socks后确定，退出再进，居然又恢复成http。目前只能暂时取消pac打钩。

入站设置中，http和socks选项都有效。现在只能靠deepin控制中心系统代理中，手动输入例外网址来规避国内网站。

**Comment by lhy0403** [comment]
Seems to be PAC related issue #121

**Comment by kingskill** [comment]
另外，继续期待订阅链接功能……

**Comment by lhy0403** [comment]
订阅这两天在写，应该下周就会完成

**Comment by lhy0403** [comment]
您尝试过下载 GFWList 吗？
目前PAC功能不是很完善，需要手动点一下 `下载 GFWList` 按钮，等一段时间下载完成后才能使用
![image](https://user-images.githubusercontent.com/18734999/69873636-d3eb7d80-12f3-11ea-84f9-405fbd7a62cd.png)

**Comment by kingskill** [comment]
> 您尝试过下载 GFWList 吗？
> 目前PAC功能不是很完善，需要手动点一下 `下载 GFWList` 按钮，等一段时间下载完成后，才能使用
> ![image](https://user-images.githubusercontent.com/18734999/69873636-d3eb7d80-12f3-11ea-84f9-405fbd7a62cd.png)

试过了。gfwlist也下载了。我去文件夹看过。应该是完整的。但是pac不起作用。另外use proxy: http 这一项，无论如何都无法改成socks。改了以后退出再进，又变成http。

**Comment by lhy0403** [comment]
请确认一下首选项的版本号是多少？

**Comment by kingskill** [comment]
> 请确认一下首选项的版本号是多少？

![深度截图_Qv2ray-refs tags v1 99 2-linux AppImage_20191129231322](https://user-images.githubusercontent.com/43365116/69877704-dce14c80-12fd-11ea-9969-5cbdc93a2db8.png)

**Comment by lhy0403** [comment]
@kingskill https://github.com/lhy0403/Qv2ray/commit/ecc8e330e8e6498f26633386a7c2ab412e021e7c 前两天有一个新版本 commit 修复了这个错误，您可以自己编译试一下

**Comment by kingskill** [comment]
> @kingskill [ecc8e33](https://github.com/lhy0403/Qv2ray/commit/ecc8e330e8e6498f26633386a7c2ab412e021e7c) 前两天有一个新版本 commit 修复了这个错误，您可以自己编译试一下

试了一下编译，好像有问题。./tool里面的那个.sh文件好像缺失。

**Comment by kingskill** [comment]
麻烦给一下详细的编译教程。

**Comment by kingskill** [comment]
有一个相似的文件grpc_gen.sh，但运行起来后还是找不到。
`./grpc_gen.sh:行4: protoc: 未找到命令
./grpc_gen.sh:行5: protoc: 未找到命令`

![深度截图_dde-file-manager_20191130003034](https://user-images.githubusercontent.com/43365116/69881747-ec19c780-1308-11ea-80c3-de6a36ba238a.png)
![深度截图_deepin-editor_20191130003042](https://user-images.githubusercontent.com/43365116/69881752-ef14b800-1308-11ea-9a6f-898b03da0ace.png)

**Comment by lhy0403** [comment]
@kingskill 你要是日常使用的话还是建议 v1.3.8
虽然功能少，但是相对较稳定 
https://github.com/lhy0403/Qv2ray/releases/tag/v1.3.8.0

**Comment by lhy0403** [comment]
Closed due to using an unsupported, old build version. 
Sorry about the inconvenience.
