### ISSUE TITLE
win10（1909）系统上运行一段时间系统代理会自动断开，需要手动重新开启（qv2ray版本：1.99.2.919）

### ISSUE THREAD

**Issue by HOMHOG** [lhy0403/Qv2ray#142]
![image](https://user-images.githubusercontent.com/17916908/69902450-fc917700-13c8-11ea-88d5-98a768686974.png)

**Comment by lhy0403** [comment]
什么叫做 “会自动断开？”

**Comment by HOMHOG** [comment]
> 什么叫做 “会自动断开？”

就是突然断流，然后进系统设置看代理开关就关了

**Comment by lhy0403** [comment]
Qv2ray 有提示重新连接吗？
log 框有没有被清空？

**Comment by HOMHOG** [comment]
> Qv2ray 有提示重新连接吗？
> log 框有没有被清空？

没有提示重新连接，log没有清空。系统代理开关关闭，手动开启又正常

**Comment by lhy0403** [comment]
有可能是其他软件进行的设置，这个问题目前无法复现

**Comment by lhy0403** [comment]
为了排查问题，您可以尝试用 （当前最新的）Windows Build 版本试一下吗？
https://github.com/lhy0403/Qv2ray/commit/7e0a8ea8f68354885ef6b3880de21bde459edb2d/checks?check_suite_id=333991335
右上角点击 
![image](https://user-images.githubusercontent.com/18734999/69902533-e6d08180-13c9-11ea-88a0-21faaf0dcc9f.png)

**Comment by HOMHOG** [comment]
> 为了排查问题，您可以尝试用 （当前最新的）Windows Build 版本试一下吗？
> https://github.com/lhy0403/Qv2ray/commit/7e0a8ea8f68354885ef6b3880de21bde459edb2d/checks?check_suite_id=333991335
> 右上角点击
> ![image](https://user-images.githubusercontent.com/18734999/69902533-e6d08180-13c9-11ea-88a0-21faaf0dcc9f.png)

好的 我试试alpha版

**Comment by lhy0403** [comment]
其实 1.99.2.* 就是 alpha, 只是最近修了一部分的bug,不知道包不包含您提出的这个情况

**Comment by DuckSoft** [comment]
cannot reproduce.

**Comment by DuckSoft** [comment]
@HOMHOG Any update about this issue?

**Comment by DuckSoft** [comment]
无更新，且无法复现，本 Issue 关闭。
若相同问题再度出现，可另开一 Issue 引用本 Issue。
