### ISSUE TITLE
建议将图标中的 QV2ray 更换为 Qv2ray

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#143]
![图片](https://user-images.githubusercontent.com/7822648/69906051-4e052a80-13f8-11ea-9d73-ffffe359cf11.png)
RT. 图标里V大写，名称里v小写，强迫症患者已疯

ref:
> Actually, the official name is with capital V... But Qv2ray misused as small v. which accidentally makes this name pretty good looking (Maybe?) We need a further discussion.

cc @axionl

**Comment by lhy0403** [comment]
Yes let's ping @axionl

**Comment by lhy0403** [comment]
This one is not exactly the same issue @thebadgateway had mentioned in #121, but I'm working on a fix.

**Comment by axionl** [comment]
https://github.com/lhy0403/Qv2ray/commit/5fc199a66d7fc641ecbcf91fd6ee2265798d1601
