### ISSUE TITLE
[dev] 导入时若 prefix 为空，则不应再在 prefix 与名称之间附加分隔符

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#144]
效果：
![图片](https://user-images.githubusercontent.com/7822648/69906142-b274b980-13f9-11ea-91f3-f8eb8fc602f1.png)

祸根：
https://github.com/lhy0403/Qv2ray/blob/ec49dffbb57b4f8c86ad5c3b866197acc37e9e59/src/QvCoreConfigOperations_Convertion.cpp#L235

以上。具体的行为可能还需要进一步讨论。

---
ref:
https://github.com/lhy0403/Qv2ray/issues/121#issuecomment-560019219

**Comment by lhy0403** [comment]
This one is not exactly the same issue @thebadgateway had mentioned in #121, but I'm working on a fix.

**Comment by lhy0403** [comment]
Should be fixed, please test @DuckSoft

**Comment by DuckSoft** [comment]
Tested and proven fixed. Closing.
