### ISSUE TITLE
dark mode support needed in speed chart

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#145]
speedchart is way too bright in dark mode user interfaces.
consider make it support dark mode.

![图片](https://user-images.githubusercontent.com/7822648/69906211-e3092300-13fa-11ea-9e82-8add3f6a2604.png)

**Comment by DuckSoft** [comment]
False alarm. 
This is solved by enabling dark mode.

**Comment by lhy0403** [comment]
Sorry for the inconvience since Qt cannot detect the OS's color settings.
