### ISSUE TITLE
speed chart: considering removing the title

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#146]
this title has no meaning since there's already 'speed chart' title above. 
consider removing it to leave more space for the chart itself. 
![图片](https://user-images.githubusercontent.com/7822648/69906260-b6094000-13fb-11ea-8dae-5dca3c98784c.png)

**Comment by lhy0403** [comment]
Yes that's a trick, Qt doesn't support removing the title, Instead we need to set the margin offset to -45 (or something negative, to remove the title bar)

Or... can we set the title to "" (empty string)?

**Comment by DuckSoft** [comment]
This is resolved in v1.99.2.1320. You may safely close this issue now.

![图片](https://user-images.githubusercontent.com/7822648/69985929-37d1a880-1577-11ea-9c29-bce65d6c64ab.png)
