### ISSUE TITLE
multiple selection and delete support

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#147]
Sometimes you just have to remove all that thousands of existing nodes you have imported.
It works to select one, click remove and click 'confirm' to remove a single node. 
But what about dozens of nodes?

Now that we have multiple vmess importing, I think multiple deletion is also important.
That's it.

- [x] multiple selection
- [x] multiple deletion

---
cc: @lhy0403

**Comment by thebadgateway** [comment]
I agree with @DuckSoft

**Comment by lhy0403** [comment]
TODO: This one should be implemented AFTER subscription because the different operation is required for subscriptions.

**Comment by thebadgateway** [comment]
@lhy0403 It is enough to implement the selection of lines through the shift button

**Comment by lhy0403** [comment]
@thebadgateway And multiselection using ctrl key, (Qt has this feature natively so I think it's not very difficult)

This fix will only affect `delete connection`, duplicating connection is not affected.

**Comment by lhy0403** [comment]
Subscription is partly done and I'll move onto this issue now.

**Comment by DuckSoft** [comment]
@lhy0403 this support is partial done in 1.99.2.1320.
multiple choice is enabled but when you click delete, it will only delete the first.

**Comment by lhy0403** [comment]
Fix applied. please test later.

**Comment by DuckSoft** [comment]
Multiple deletion testing in progress.

**Comment by DuckSoft** [comment]
tested.
