### ISSUE TITLE
高分屏设置qt缩放之后，截图会错位。

### ISSUE THREAD

**Issue by huyizheng** [lhy0403/Qv2ray#148]
在反馈 bug 之前，您可以去我们的 [Telegram Group](https://t.me/qv2ray) 寻求帮助

在高分屏中，如果设置了qt缩放相关的环境变量，会导致截图时错位。
最新的committ是这样的，由于我昨天才刚换高分屏，所以不知道前面的committ会不会这样。

**如何复现这个bug：**
1. 设置QT_SCREEN_SCALE_FACTORS=2环境变量。
2. 打开qv2ray，导入，屏幕截图。
3. 设置xrandr --dpi 216以上，然后设置QT_AUTO_SCREEN_SCALE_FACTOR=1，也能产生同样的效果。

**Qv2ray 本应该是怎样工作的？**
不设置高dpi缩放则不会错位。

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 

**相关截图或日志**
![857413005_66231](https://user-images.githubusercontent.com/22879638/69924176-ea0c6000-14e4-11ea-921e-8d673726a691.jpg)
这图是我在高分屏设置缩放后开启截图功能时，整个屏幕的截图。
从图中看，无论是截图时的背景，还是实际截出来的图，都是错位的

**系统信息**
 - 系统类型（windows, linux, macos）
    - archlinux
 - 是从release下载的还是自己编译的
    - aur的dev版
 - 首选项里的版本号：
    - 1.9.2.1090

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

-

**Comment by huyizheng** [comment]
我现在不确定这个bug是截图工具的问题还是qt本身的问题了。
因为我发现obs和simplescreenrecorder也是这样的，即当qt缩放的那个环境变量设为2时，软件默认检测到的“全屏”就是减小一半分辨率的结果（即我是4k屏，软件自动检测全屏会检测出1920x1080）。从而导致捕获不完全。
但这两个软件我只需要手动指定好3840x2160即可恢复正常。

**Comment by lhy0403** [comment]
@huyizheng 有一说一，这个bug确实在我设置了 `QT_SCREEN_SCALE_FACTORS=2` 后出现了

**Comment by lhy0403** [comment]
可能您的截图软件和 Qv2ray 都出现了问题😂
我会仔细看看

**Comment by DuckSoft** [comment]
Cannot reproduce with Flameshot, same version of Qv2ray on Arch Linux.
![图片](https://user-images.githubusercontent.com/7822648/70194087-487f4b80-173c-11ea-81be-8c83385b1024.png)

**Comment by lhy0403** [comment]
@DuckSoft possible fixed the inner image issue in this commit: https://github.com/lhy0403/Qv2ray/commit/9c0da40c21732e2ad7a058402fced2aceeb6c86e

But the background seems to be broken as well....

**Comment by DuckSoft** [comment]
background is the original picture of the issue lol

Leroy.H.Y <notifications@github.com>于2019年12月5日 周四下午12:08写道：

**Comment by DuckSoft** [comment]
> @DuckSoft possible fixed the inner image issue in this commit: [9c0da40](https://github.com/lhy0403/Qv2ray/commit/9c0da40c21732e2ad7a058402fced2aceeb6c86e)
> 
> But the background seems to be broken as well....

Maybe I should add a larger picture to show it.
No problem found under KDE Plasma.
![图片](https://user-images.githubusercontent.com/7822648/70203769-07496480-1759-11ea-9f69-9438d9546a67.png)

----
cc: @lhy0403

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/70203897-7f178f00-1759-11ea-9c92-a5d97f480022.png)
Fix confirmed.

**Comment by lhy0403** [comment]
I'm gonna test this afternoon, even me myself didn't know that was *accidently* fixed

**Comment by lhy0403** [comment]
Confirmed to be fixed after testing on a 4K laptop.
