### ISSUE TITLE
[subscription][dev]不断戳更新订阅按钮会导致列表不断刷屏

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#149]
在反馈 bug 之前，您可以去我们的 [Telegram Group](https://t.me/qv2ray) 寻求帮助

**如何复现这个bug：**
1. 打开主界面订阅按钮，出现订阅对话框
2. 点击更新订阅按钮更新一个已有的订阅
![图片](https://user-images.githubusercontent.com/7822648/69986843-25f10500-1579-11ea-874c-edd8b216413b.png)

3. 再点一次更新订阅按钮，列表不断向下滚动刷出相同的节点，如图
![图片](https://user-images.githubusercontent.com/7822648/69986976-749e9f00-1579-11ea-8435-792d4a10c9ee.png)

**Qv2ray 本应该是怎样工作的？**
不应该刷出相同的节点列表，而应清空列表，重新获取订阅。

**系统信息**
 - 系统类型（windows, linux, macos）
    - arch linux
 - 是从release下载的还是自己编译的
    - compiled from aur
 - 首选项里的版本号：
    - v1.99.2.1320

**Comment by thebadgateway** [comment]
Inconvenient interface, I did not immediately understand how to use it. Maybe better like that?
![Group-1.png](https://pixs.ru/images/2019/12/02/Group-1.png)

**Comment by lhy0403** [comment]
@thebadgateway Well the add subscription and manage subscription are two different things, **(currently)**, I'll merge it in the future.

**Comment by lhy0403** [comment]
As for the window in your design is for *importing* configs, it's not very appropriate to put `delete` and `update` there. 
I think the Subscription tab should trigger the subscription management window, to prevent confusion and duplication of the `add` feature.

**Comment by lhy0403** [comment]
![image](https://user-images.githubusercontent.com/18734999/70004724-48e3df00-15a2-11ea-84d4-371be763fa37.png)

**Comment by thebadgateway** [comment]
Very often a user only needs to add a subscription. And deleting and editing is very rare. Therefore, the add line should be near.

**Comment by DuckSoft** [comment]
This problem is fixed as of Qv2ray v1.99.2.1515.
Closing now.
