### ISSUE TITLE
[subscription][dev]订阅链接框竟然能输入多行文本

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#151]
如题。图见下：
![图片](https://user-images.githubusercontent.com/7822648/69987335-3fdf1780-157a-11ea-8d3f-f238b78ba192.png)

**Comment by lhy0403** [comment]
I replaced this with a single line QLineEdit, which has a shorter input range but I think it's enough.

**Comment by DuckSoft** [comment]
Confirmed. Closing.
