### ISSUE TITLE
implementation missing for "help" button in the configuration window

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#152]
there is help button. but when you click it and hover mouse to any of the controls, you will get that there is no help implemented. I don't know if this is a problem.

![图片](https://user-images.githubusercontent.com/7822648/69987583-cc89d580-157a-11ea-822f-3086f05e025c.png)
---
cc @lhy0403

**Comment by lhy0403** [comment]
Yes it's a bug and I'll disable it in the next few commit.

**Comment by lhy0403** [comment]
Is the prefrence window the only one containing this issue?

**Comment by lhy0403** [comment]
Alright, fixed and closed.
