### ISSUE TITLE
Qv2ray eats lots of memory when active long

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#157]
Did it take up nearly...... 1.2 GB memory? 
![image](https://user-images.githubusercontent.com/18734999/70206397-68296a80-1762-11ea-8bf6-992cb3bdd2f7.png)

_Originally posted by @lhy0403 in https://github.com/lhy0403/Qv2ray/issues/121#issuecomment-561974686_

**Comment by lhy0403** [comment]
I'm not sure if it's caused by the log widget.....

**Comment by DuckSoft** [comment]
It shall be wise if we limit the maximum lines of logs. But I’ve ever seen [plugin] in log keep flashing rapidly. Need investigation.

**Comment by lhy0403** [comment]
`[PLUGIN]` might be caused by the plugin daemon... I may need further investigate.

**Comment by DuckSoft** [comment]
Seems that it's the bug. Look at the animation.
![Peek 2019-12-06 02-38](https://user-images.githubusercontent.com/7822648/70263531-91351400-17d1-11ea-9f4d-75e67f479198.gif)

---
cc @lhy0403

**Comment by lhy0403** [comment]
Maybe the log highlighter is the real cause of this problem? 
Just a guess, let me see...

**Comment by DuckSoft** [comment]
Will try testing the new version, where plugin log is placed at DEBUG level.
Hopefully this will be fixed.

**Comment by lhy0403** [comment]
Is it working properly now? @DuckSoft

**Comment by DuckSoft** [comment]
> Is it working properly now? @DuckSoft

Now it's okay. Closing.
