### ISSUE TITLE
订阅编辑器中的按钮 tooltip 不正确

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#160]
期望：两个按钮的工具提示（tooltip）分别提示**添加订阅**、**删除订阅**。

实际：两个按钮的工具提示分别显示**添加连接**、**删除连接**。

附图：

![图片](https://user-images.githubusercontent.com/7822648/70274549-4aeaaf80-17e7-11ea-9044-79ab05c5fe62.png)
![图片](https://user-images.githubusercontent.com/7822648/70274576-5c33bc00-17e7-11ea-9d34-cecd5c5bd25a.png)

**Comment by lhy0403** [comment]
Marked as fixed and will be closed soon.

**Comment by DuckSoft** [comment]
Confirmed. Closing.
