### ISSUE TITLE
need proper context menu handling for subscription node in tree list of hosts

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#161]
### current status
see the pic:
![图片](https://user-images.githubusercontent.com/7822648/70275487-31e2fe00-17e9-11ea-8001-59d1607d50ca.png)

### todos
to be discussed.

---
cc @lhy0403

**Comment by lhy0403** [comment]
Marked as fixed and will close after commit.

**Comment by DuckSoft** [comment]
Well done! Closing.
