### ISSUE TITLE
improving vmess sharing experience

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#162]
Currently we only have these ways to share vmess links:
1. save qrcode as picture (to a fixed folder in disk)
2. offer user the vmess link to copy

I suggest we offer user these extra options:
- [x] copy vmess directly into clipboard
- [x] copy qrcode picture into clipboard, without writing out file
- [x] save qrcode as picture, but ask user the location to save

I think these should help improving the user experience. 
Looking forward to heated discussions.

**Comment by thebadgateway** [comment]
I believe that an excess of functionality is also bad.
And only 1 option out of 3 is enough.
"copy vmess directly into clipboard"

**Comment by lhy0403** [comment]
@thebadgateway Well in China we also share configs via QRCode, e,g. to import it on phone or iPad.

**Comment by thebadgateway** [comment]
@lhy0403 I know this well, however, everyone is now using a subscription. And if you have one server, then you already have the qrcode save function

**Comment by lhy0403** [comment]
For me personally, I share one of the subscription to my phone. instead of using the whole subscription link, (for it's slow to download.)

**Comment by thebadgateway** [comment]
I still need the option to automatically renew my subscription. :)

**Comment by thebadgateway** [comment]
> For me personally, I share one of the subscription to my phone. instead of using the whole subscription link, (for it's slow to download.)

I think this is an exceptional case, because one server for the phone is very small.

**Comment by lhy0403** [comment]
Will do @thebadgateway

**Comment by lhy0403** [comment]
We will add all of three options mentioned by @DuckSoft https://github.com/lhy0403/Qv2ray/issues/162#issue-533615246 since implementing these is not very difficult.

**Comment by DuckSoft** [comment]
Functionality confirmed. 
Well done! Closing.
