### ISSUE TITLE
empty subscription is mistaken as a dedicated host

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#164]
## reproduction
1. clean install qv2ray v1.99.2.1515
2. subscription -> new subscription. leave it empty and close.
now you should see an empty subscription in your host list:
![图片](https://user-images.githubusercontent.com/7822648/70278416-2f83a280-17ef-11ea-9761-e2ed70cacf00.png)
3. bug occurs: 
- dblclick it to absurdly "connect" to the subscription
![图片](https://user-images.githubusercontent.com/7822648/70278506-60fc6e00-17ef-11ea-970b-0bf1ab8a3929.png)
- duplicating produces a strange copy
![图片](https://user-images.githubusercontent.com/7822648/70278579-82f5f080-17ef-11ea-82e8-5b8617a1bedb.png)
- deleting: file deletion failed
![图片](https://user-images.githubusercontent.com/7822648/70278640-9e60fb80-17ef-11ea-9eb3-9fd845570bc4.png)
- ... and more

---
cc @lhy0403

**Comment by lhy0403** [comment]
Mark as fixed.

**Comment by DuckSoft** [comment]
Confirmed. Closing.
