### ISSUE TITLE
consider removing excess subscription source indicator in grouped host items

### ISSUE THREAD

**Issue by thebadgateway** [lhy0403/Qv2ray#166]
A very cool idea is to subscribe in a tab. But I think that we need to remove the prefix on the right, because it is superfluous.
![ 6 дек 2019--09:31:36](https://user-images.githubusercontent.com/45717841/70326862-83829b80-1870-11ea-8ae8-86f0bc7c6449.png)

**Comment by lhy0403** [comment]
ah yes I just forgot to remove that.

**Comment by lhy0403** [comment]
No. I just need to mention that cannot be removed.

**Comment by lhy0403** [comment]
The text in the tree view is the key in the internal QMap<QString, Config> , removing it may cause issues in this senario:

- User has a subscription named whatever he wants..
- This subscription has a connection named `myconn`
- User imported another `vmess://` and input the same name `myconn`
- which QMap does not allow duplicated key.

**Comment by lhy0403** [comment]
I'd be damn happy if someone can suggest a method solving this, which allowing us to show Ping value in this list as well 
cc @DuckSoft

**Comment by DuckSoft** [comment]
Hold this issue currently.
Hopefully it will be fixed in later versions.

**Comment by lhy0403** [comment]
I just got an idea which may help to fix this issue.

**Comment by lhy0403** [comment]
Just uploaded a fix, which completely rewrite the UI logic base, and may have some issues....
Please have a tray and report to me if anything goes wrong

**Comment by lhy0403** [comment]
Fixed it again, all related code has been rewritten, please has a test @thebadgateway

**Comment by DuckSoft** [comment]
This is confirmed as fixed in recent versions (v1.99.4.2707).
Closing for now. If problem persists, feel free to reopen this.
