### ISSUE TITLE
crutial path escaping risk in subscription name

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#168]
![图片](https://user-images.githubusercontent.com/7822648/70347467-8d6dc400-189b-11ea-9a32-5d9819338778.png)
![图片](https://user-images.githubusercontent.com/7822648/70347489-98c0ef80-189b-11ea-89aa-90965e74e17d.png)

i will suggest never ever use file system itself directly to store structured data.
too dangerous.
@lhy0403

**Comment by lhy0403** [comment]
Fix applied, please test if it's working properly as expected.

**Comment by DuckSoft** [comment]
https://github.com/lhy0403/Qv2ray/blob/8f5c5cf7d870a406f13f72ffed9cde31682e3bd4/src/ui/w_MainWindow.cpp#L748-L761

> Fix applied, please test if it's working properly as expected.

still we need to check two special files/folders: `.` and `..`

**Comment by lhy0403** [comment]
@DuckSoft Ah yes....

**Comment by DuckSoft** [comment]
Good job. Done.
