### ISSUE TITLE
v2ray core file not found in the AppImage

### ISSUE THREAD

**Issue by probonopd** [lhy0403/Qv2ray#170]
**Briefly describe this bug：**

Dear developer, please put v2ray core file into the AppImage and make it work, e.g., by constructing a relative path using `QCoreApplication::applicationDirPath()`.

**How can I trigger this bug：**

1. Download AppImage
2. Make Executable
3. Run

**What is expected to happen**

Works

**Screenshots**

![notfound](https://user-images.githubusercontent.com/2480569/70379780-f18a9980-1928-11ea-818f-329dbde443cc.png)

> v2ray core file cannot be found at:
> 
> Please go to prefrence window to change the location.
> Or put v2ray core file in the location above.

**System Information**

 - OS Type: Linux
 - Built from the source or download from the release? Downloaded
 - Version string in the Preferences Window: 1.99.2.918 Nov 27 2019 04:02:27

**Other Info**

You may want to write anything if you think it helps us to fix the bug.

Reference:
https://github.com/AppImage/appimage.github.io/pull/1764

**Comment by probonopd** [comment]
Reference:
https://github.com/AppImage/appimage.github.io/pull/1764

**Comment by lhy0403** [comment]
Well Qv2ray is a separated app compared with v2ray, and, unfortunately we currently have no plan to bundle it inside the AppImage, sorry.

**Comment by probonopd** [comment]
Why not bundle it inside the AppImage? The idea of AppImage is that you don't need anything else but one file.

**Comment by lhy0403** [comment]
We let the user download themself to prevent abuse of Qv2ray by letting them download and extract the core file, instead of making it a ready-to-use single AppImage. 
It's only a GUI instead of a toolset to bypass the firewall, which may against the local law.

**Comment by DuckSoft** [comment]
We tried not include these files in order to keep our asses.
Closing now.

**Comment by probonopd** [comment]
Thanks, I understand.

**Comment by keivanhh** [comment]
ive the same prob in mac os what shall I do ?
would you plz kindley explain?

**Comment by ali-sardari** [comment]
https://www.youtube.com/watch?v=otZWoeDaqn8

Core:
https://github.com/v2fly/v2ray-core/releases/tag/v4.31.0

**Comment by MatejKovacic** [comment]
Hi, I run into the same issue and under `Kernel settings` tried to enter `V2Ray Core executable path` - I entered `/usr/bin/v2ray`. But it says `V2Ray core executable not found`.

I have Ubuntu 22.04 and installed snap version of Qv2ray...
