### ISSUE TITLE
English translations might be broken

### ISSUE THREAD

**Issue by lhy0403** [lhy0403/Qv2ray#171]
@thebadgateway
I'm working on this issue.

**Comment by lhy0403** [comment]
@thebadgateway What's the behavior?
Can you switch to en-US, if so, is it still in Russian or.... crash?

**Comment by thebadgateway** [comment]
I change the language to English and restart the program, but the interface remains in Russian

**Comment by lhy0403** [comment]
Can you provide the log ? It should be helpful for us to solve the problem

**Comment by lhy0403** [comment]
I just pushed a commit 99e9fb3 , allowing en-US be part of the release build process, can you have a test? 
Thanks!

**Comment by thebadgateway** [comment]
Build through actions does not work. I can not use new versions

**Comment by lhy0403** [comment]
Ah, it's a serious issue, many people have been affected, https://github.com/jurplel/install-qt-action/issues/14

**Comment by lhy0403** [comment]
I just changed to reverted Github Action, let's see if the build will success or not.

**Comment by thebadgateway** [comment]
I downloaded the new version. As before, switching the language to English does not work.

**Comment by thebadgateway** [comment]
https://yadi.sk/i/2ZZBoa8APhNPtw 
Does not work.

**Comment by thebadgateway** [comment]
https://yadi.sk/i/-wJYO_1XvFwhQg
Wondows 10

**Comment by lhy0403** [comment]
Well......... I received your videos and currently working on a fix
(I may need to install a Russian environment 🤣

**Comment by lhy0403** [comment]
And for macOS, the grpc.dylib is still missing right?
I’ll try to copy it directly...

**Comment by lhy0403** [comment]
@thebadgateway Fix applied, it seems to be working on my newly-setup Russian env.

**Comment by lhy0403** [comment]
http://download.qt.io/ is down, Github Action cannot continue....

**Comment by lhy0403** [comment]
[UPDATE] Qt website is now avaliable and Github Action is ready, can you please have a try of the latest build?

**Comment by thebadgateway** [comment]
Please close - en-Us  works!

**Comment by lhy0403** [comment]
Finally done, Thanks a lot for your patience 😂.
