### ISSUE TITLE
Subscription List Order

### ISSUE THREAD

**Issue by thebadgateway** [lhy0403/Qv2ray#172]
A few versions ago, the list of servers in the subscription became in the reverse order of the alphabet.

![10 дек 2019--02:29:04](https://user-images.githubusercontent.com/45717841/70461976-e1271a00-1af4-11ea-9d87-0829d71244cb.png)

**Comment by DuckSoft** [comment]
Well that's hard to fix in this version lol.
By the way, what do you expect this to be like?

**Comment by lhy0403** [comment]
I accidentally fixed this bug....... LOL
I need to write an easy-to-understand doc even for myself.

**Comment by lhy0403** [comment]
It happened in renaming a connection entry and triggered a reload of the list, something happened causing somewhat an entry is holding 0 as ptr.
It'll be fixed in the upcoming refactoring commit.

**Comment by lhy0403** [comment]
Just fixed in the previous commit, @thebadgateway please check it out!

**Comment by thebadgateway** [comment]
I did not see the changes. I am using commit ccc7e2e

**Comment by lhy0403** [comment]
> I did not see the changes. I am using commit [ccc7e2e](https://github.com/lhy0403/Qv2ray/commit/ccc7e2e6d3adac2038fd424d8a9621b268367717)

It’s not on the v2 branch yet, still within dev

**Comment by thebadgateway** [comment]
Thx, closed pls

**Comment by lhy0403** [comment]
@thebadgateway did you test the fixes? Is it now fixed?
