### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by snowman** [lhy0403/Qv2ray#180]
**如何复现这个bug：**
1. i doonoh......

**相关截图或日志**
![2019-12-14-210842_1920x1080_scrot](https://user-images.githubusercontent.com/16096559/70849192-0a112b80-1eb6-11ea-8804-72626b6c02a1.png)

**系统信息**
 - 系统类型（windows, linux, macos）
    - linux
 - 是从release下载的还是自己编译的
    - yay -S Qv2ray
 - 首选项里的版本号：
    - ???

**Comment by snowman** [comment]
If the English lang version is available, then could fix this for me :J)

**Comment by lhy0403** [comment]
It seems to be missing of Chinese Fonts, could you please check it?

My installed fonts FYI

![image](https://user-images.githubusercontent.com/18734999/70849246-b5ba7b80-1eb6-11ea-9041-e9f2ca0b8931.png)

**Comment by lhy0403** [comment]
You may wish to change to English in the Preference Window. There's an option to do that.
Restart Qv2ray after changing the language.

**Comment by snowman** [comment]
After following the wiki of 
https://wiki.archlinux.org/index.php/Font_Configuration/Chinese_(简体中文) installation with
```bash
$ sudo pacman -S ttf-roboto noto-fonts noto-fonts-cjk adobe-source-han-sans-cn-fonts adobe-source-han-serif-cn-fonts ttf-dejavu
```
and add `~/.config/fontconfig/fonts.conf` file, the problem solve.

![2019-12-14-213031_680x555_scrot](https://user-images.githubusercontent.com/16096559/70849468-c02a4480-1eb9-11ea-87b6-00256e65efe8.png)

By the way, what commands you run gives above output??

**Comment by lhy0403** [comment]
it was just a simple list and grep, since I use `yaourt`
`> yaourt font | grep installed`
