### ISSUE TITLE
功能请求 希望能自定义路由

### ISSUE THREAD

**Issue by Okabe-Kurisu** [lhy0403/Qv2ray#184]
config.json中的routing字段
方便linux用户对于企业网络的地址进行直连

**Comment by lhy0403** [comment]
cc @DuckSoft

**Comment by DuckSoft** [comment]
> config.json中的routing字段
> 方便linux用户对于企业网络的地址进行直连

@Okabe-Kurisu This is already implemented in dev version. Follow the operations:
1. on your host list, locate the intended host.
2. right click on the host, choose **Edit as Complex Config**.
3. YOU ARE DONE.

pic:
![图片](https://user-images.githubusercontent.com/7822648/70968328-d875ab80-20d3-11ea-8700-e8b7817ada1f.png)

**Comment by Okabe-Kurisu** [comment]
奥，好吧。谢谢

**Comment by lhy0403** [comment]
A better route editor is coming, check this https://github.com/paceholder/nodeeditor
