### ISSUE TITLE
Obj-C API for macOS system proxy

### ISSUE THREAD

**Issue by SoumeshBanerjee** [lhy0403/Qv2ray#185]
**In MacOSX Client, `Set System Proxy` is checked but still system proxy is not set**

In MacOSX Client `Preference` > `Inbound settings` > `Set System Proxy` is checked, but still system proxy for both `Ethernet` network and `WiFi` network is not set.

Is this the desired behaviour, bug or am I missing something ?

**Comment by lhy0403** [comment]
Currently, there's no support to set up macOS system settings in version 2.
Apple only provides objective-c or swift API, but not c++.

It already on the schedule, but I didn't expect to implement this feature in the near future (I need to learn ObjC)

**Comment by SoumeshBanerjee** [comment]
> It already on the schedule, but I didn't expect to implement this feature in the near future (I need to learn ObjC)

I know bit of ObjC I could maybe help you guys with that... 🥂

**Comment by lhy0403** [comment]
Yes sure! The interfaces are here:

https://github.com/lhy0403/Qv2ray/blob/dev/src/components/QvSystemProxyConfigurator.hpp

I may write a better doc soon.

**Comment by lhy0403** [comment]
You may just send the obj-c code directly here since integrating these to Qt might be tricky.

**Comment by SoumeshBanerjee** [comment]
> You may just send the obj-c code directly here since integrating these to Qt might be tricky.

Yes Cool!

**Comment by lhy0403** [comment]
Let's reopen this for tracking.

**Comment by SoumeshBanerjee** [comment]
The code for the SetSystemProxy for MacOSX can be [located here](https://github.com/SoumeshBanerjee/MacOSX-System-Proxy)

I changed the function signature a bit, for accepting the list of `network interface` to apply these settings to and also which address is for which protocol (i am not sure how to access that, its part of `QString & address` maybe?

**Comment by lhy0403** [comment]
THanks, I will go and check your repo, since I don't have much free time recently, I might reply you in a few days.

**Comment by DuckSoft** [comment]
I may have found a relatively easy way to set system proxies on macOS:
why not run `networksetup` command on macOS, if it's hard to integrate Obj-C code?
Here's a reference:

https://richardkmiller.com/925/script-to-enabledisable-socks-proxy-on-mac-os-x

cc @lhy0403

**Comment by lhy0403** [comment]
A tricky way implementing this is to .....
> "but one thing seems to work for me … changing the permission and `chown` to root …. Then it won’t ask for a password … maybe we can ask for permission once and install that tool as root and all the future run can be run as root’s permission"

Quoted.

**Comment by lhy0403** [comment]
Yeah maybe we can set this file @DuckSoft you mentioned as `chown root:root` and call it directly?
What do you think? @DuckSoft @SoumeshBanerjee 

If so, I still need some API (or something else) that allows me to show a `sudo` password prompt.

**Comment by SoumeshBanerjee** [comment]
> If so, I still need some API (or something else) that allows me to show a sudo password prompt.

You can run this using apple script calling `with administrator privileges` .. like this [example](https://apple.stackexchange.com/questions/224629/how-can-i-run-a-shell-script-with-admin-privileges-from-applescript)

**Comment by lhy0403** [comment]
So we can embed an AppleScript and call it to set our “setProxy.sh” as owned by root:root.
Once that is done, each time we just need to call that “setProxy.sh -myArgs” without prompting current user password?

**Comment by lhy0403** [comment]
Where should we place that “setProxy.sh”?

**Comment by SoumeshBanerjee** [comment]
> Where should we place that “setProxy.sh”?

Well Apple apps are just a folder ... so in XCode you can create `Copy` Build Phase and place that file there (not sure how you're building the application though!)
or
`/Library/Application\ Support/Qv2ray` folder for the application maybe!

Merry Christmas 🎄

**Comment by lhy0403** [comment]
Merry Christmas everyone!
I'd love to put it into `"/Library/Application Support/Qv2ray"` since app folder content and permission will be replaced (and reset as well) when upgrading Qv2ray. However by using system application support path, we only need to update the script whenever needed.

So final confirmation: "setProxy" will be inside /Library/Application\ Support/Qv2ray right? 

I'll setup a VM and test this feature soon.

**Comment by lhy0403** [comment]
I tried on my VM, I'm able to call `networksetup setsocksfirewallproxystate Ethernet off` and set the proxy without root permission, I wonder if it only happen to me or it's a new feature in the recent macOS update.

macOS Catalina 10.15.3 Beta (19D49f)
cc @SoumeshBanerjee

**Comment by lhy0403** [comment]
Also need to mention, the Interface name (or Apple calls it "Service name") may be changed by user and varies in different languages (maybe?).

**Comment by lhy0403** [comment]
For ref only
```
➜  ~ networksetup -listallnetworkservices 
An asterisk (*) denotes that a network service is disabled.
Ethernetxxx
Bluetooth PAN

```

**Comment by SoumeshBanerjee** [comment]
> I tried on my VM, I'm able to call `networksetup setsocksfirewallproxystate Ethernet off` and set the proxy without root permission, I wonder if it only happen to me or it's a new feature in the recent macOS update

I am not sure but seems like `networksetup` CLI tool don't prompt for sudo permission/ password to run (at least in my user account which is a Admin account)... just like if you manually edit from the `Settings` app

**Comment by SoumeshBanerjee** [comment]
> Also need to mention, the Interface name (or Apple calls it "Service name") may be changed by user and varies in different languages (maybe?).

Yes, sorry for not making this clearer, the Interface name (service name) can be changed by the user / program
In the ObjC API program we can set the proxy for all the interfaces... [if we remove this check](https://github.com/SoumeshBanerjee/MacOSX-System-Proxy/blob/be7b2cf45762449d46f2974fcc247ec804c2ba2b/ProxyPrefManager/main.m#L66)

**Comment by lhy0403** [comment]
@SoumeshBanerjee To make it simple, I chose to directly execute the `networksetup` process.
Thanks for your contributions.

**Comment by lhy0403** [comment]
Feature added, we will enumerate all network interfaces except the disabled ones, and set proxy settings to all of the enabled ones.

**Comment by DuckSoft** [comment]
Later, maybe we can utilize this helper from @SoumeshBanerjee and include it within our macOS distribution. `networksetup` maybe too tricky for a stable release.

**Comment by lhy0403** [comment]
For information: This is temporarily fixed and will be closed.
Future migrations to use @SoumeshBanerjee 's repo will be discussed whenever needed.
