### ISSUE TITLE
[typo] prefrence -> preference

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#186]
currently this typo is found in:
* user interface translation file: translations/en-US.ts
   * note: since both keys and values are tainted, changes cannot be easily made to prevent missing translation entry key error during compilation.
* project source filename:
   * /src/ui/w_PrefrencesWindow.ui
   * /src/ui/w_PrefrencesWindow.cpp
   * /src/ui/w_PrefrencesWindow.hpp
* other files that have referenced translation and `PrefrencesWindow`.

try fix it early enough before it getting too hot to hold.

cc @lhy0403

**Comment by lhy0403** [comment]
Fixes applied, please have a try.
Language-specific translations will only be avaliable AFTER merging into `version-v2` branch

**Comment by DuckSoft** [comment]
Fix confimed in build number 1923.
Closing.
