### ISSUE TITLE
[ux] horizontal size of automatic connection combobox should grow

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#187]
Have a look at the picture below

![图片](https://user-images.githubusercontent.com/7822648/71227741-2c260600-231b-11ea-8dd0-7f1440e95acc.png)

It's normal to have a rather long name, whether it's subscription or a single host.
But the combobox of "auto connect" in preference window seems will not grow horizontally at all, while other components will grow. 

I think this should be fixed to improve user experience.
cc @lhy0403

**Comment by lhy0403** [comment]
ACK, will adjust the width.

**Comment by DuckSoft** [comment]
This problem occurs when you have nothing in auto connect.

![图片](https://user-images.githubusercontent.com/7822648/71228342-d4889a00-231c-11ea-99a5-7d864b86f6c3.png)

But it's strange that if you select any node and save, reopen the preference window, this will become normal again:
![图片](https://user-images.githubusercontent.com/7822648/71228389-fa15a380-231c-11ea-9162-cb97bb3fe698.png)

Need further inspection.

**Comment by lhy0403** [comment]
It's adapted to hold the current text length.
Anyway, I'll assign this to `expanding` so that it would take the maximum width.

**Comment by DuckSoft** [comment]
Copy that.

**Comment by lhy0403** [comment]
Please just have a try, this should be fixed.

**Comment by DuckSoft** [comment]
Proven fixed. Closing.
![图片](https://user-images.githubusercontent.com/7822648/71293511-989f1480-23b0-11ea-821b-7655704c8014.png)
