### ISSUE TITLE
v2ray在Ubuntu上无法连接failed to read config file

### ISSUE THREAD

**Issue by yaodonggggggg** [lhy0403/Qv2ray#189]
连接后出现
V2Ray v2.47 (One for all) 20171109
An unified platform for anti-censorship.
Main: failed to read config file: /home/faustino/.qv2ray/generated/config.gen.json > Ext|Tools|Conf|Serial: failed to parse json config > Ext|Tools|Conf: Router settings is not specified.

**Comment by lhy0403** [comment]
v2ray 2.47 是不是有一点点旧版了。
建议从官方下载 4.* 进行尝试

**Comment by yaodonggggggg** [comment]
> v2ray 2.47 是不是有一点点旧版了。
> 建议从官方下载 4.* 进行尝试

现在使用最新的。log显示
V2Ray 4.21.3 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
但是出不去，Google显示
无法访问此网站 www.google.com 的响应时间过长。

**Comment by lhy0403** [comment]
有没有设置浏览器代理？

**Comment by lhy0403** [comment]
或者系统代理？

**Comment by yaodonggggggg** [comment]
> 有没有设置浏览器代理？

都没有。。。，没有全局模式吗

**Comment by lhy0403** [comment]
linux 除了  GNOME 桌面之外，其他 DE 没有类似设置， 
你如果使用的是 v2 测试版，在首选项中有对于 GNOME 的设置

**Comment by yaodonggggggg** [comment]
> linux 除了 GNOME 桌面之外，其他 DE 没有类似设置，
> 你如果使用的是 v2 测试版，在首选项中有对于 GNOME 的设置

谢谢解答
