### ISSUE TITLE
[2.0] 实现多outbounds配置

### ISSUE THREAD

**Issue by lhy0403** [lhy0403/Qv2ray#19]
https://github.com/2dust/v2rayN/wiki/订阅功能说明

**Comment by lhy0403** [comment]
FYI: https://github.com/aliyuchang33/Hv2ray/pull/8

**Comment by aliyuchang33** [comment]
多outbounds gkd，导入自定义配置竟然选的是最后一个outbound，说实话导入自定义文件直接复制就好了，毕竟有写的什么特殊东西，你就直接丢了。

**Comment by lhy0403** [comment]
🔢 之前是因为不支持编辑那些格式才直接丢掉的其他内容（现在加了以后忘记更新了）（……）

**Comment by aliyuchang33** [comment]
WIP多长时间

**Comment by lhy0403** [comment]
（短期目标是像 Jack 那样的 GUI 但是我真的不会 
![image](https://user-images.githubusercontent.com/18734999/63521011-3c260880-c528-11e9-9079-c55932d02242.png)

**Comment by aliyuchang33** [comment]
别Jack了，Jack CS class上搞，先Qv

**Comment by lhy0403** [comment]
不不不不不不不不不不不不我是说这种连接配置 ui

**Comment by aliyuchang33** [comment]
能用就行，但是导入配置真的不能用啊

**Comment by lhy0403** [comment]
For future refrences, this feature will be implemented in the Qv2ray Version 2.0, see branch https://github.com/lhy0403/Qv2ray/tree/dev-multi-outbound

**Comment by lhy0403** [comment]
FYI: this feature is currently merged to the main development branch.

**Comment by lhy0403** [comment]
Automatic editor selector has been implemented.

**Comment by lhy0403** [comment]
Outbound routing editor has been implemented

**Comment by lhy0403** [comment]
Done partly. 
The only thing left is to add an in/outbound to a complex config.
(and debug btw)

**Comment by lhy0403** [comment]
DONE
