### ISSUE TITLE
[AUR] arch linux automatic core path configuration fix

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#190]
Tested. @axionl Please fix `qv2ray-dev-git` with this:

On https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=qv2ray-dev-git#n33:
> ```qmake "QV2RAY_DEFAULT_VCORE_PATH=/usr/bin/v2ray" ../```

Replace with:
> ```qmake 'DEFINES += QV2RAY_DEFAULT_VCORE_PATH=\"QString(\\\"/usr/bin/v2ray\\\")\"' 'DEFINES += QV2RAY_DEFAULT_VASSETS_PATH=\"QString(\\\"/usr/lib/v2ray\\\")\"' ../```

I know it's crazy, but it really works.
By the way, I'd be glad if you can add me (username: `DuckSoft`) to the AUR package as a co-maintainer.

That's it!

**Comment by lhy0403** [comment]
@axionl please see this.

**Comment by DuckSoft** [comment]
assignee is busy. this is expected to take a day or two.

**Comment by lhy0403** [comment]
we may use this https://github.com/archlinuxcn/repo/pull/1433

**Comment by DuckSoft** [comment]
Fix applied. Thanks @axionl for granting access.
Closing.

**Comment by lhy0403** [comment]
[OFFTOPIC]: The issue number finally drops to 1 digit.
