### ISSUE TITLE
请问linux版本中有添加vmess服务器的功能吗？

### ISSUE THREAD

**Issue by ogre25** [lhy0403/Qv2ray#192]
linux版中无法找到 添加vmess服务器和扫描二维码的选项。qv2ray版本是1.3.8.0

**Comment by DuckSoft** [comment]
所述功能仍在开发分支中，没有合并到主分支。
若您需要提前体验这些功能，可以自行构建 dev 分支，也可以报告您的 Linux 发行版及版本，向开发者索要对应的二进制包。

**Comment by DuckSoft** [comment]
@ogre25 any update?

**Comment by DuckSoft** [comment]
No response. Closing.

**Comment by YJHelloWorld** [comment]
你好，我的系统是Ubuntu 16.04, 请问有可以直接添加 vmess地址的版本吗？

**Comment by DuckSoft** [comment]
Ubuntu 16.04 可使用 snap 安装 qv2ray。有。

> 你好，我的系统是Ubuntu 16.04, 请问有可以直接添加 vmess地址的版本吗？
