### ISSUE TITLE
部分状态下右上角图标无法正常显示

### ISSUE THREAD

**Issue by Double-Wen** [lhy0403/Qv2ray#193]
在反馈 bug 之前，您可以去我们的 [Telegram Group](https://t.me/qv2ray) 寻求帮助

**如何复现这个bug：**
        我是ubuntu 18.04.2操作系统，我在gnome自带的startup applications preferences里面配置了开机自启动，启动过后可以正常连接并关闭窗口，但是右上角状态栏上面的图标会丢失看不见，然后重新点打开Appimage会提示已有一个实例在运行，在右上角图标消失的情况下便无法重新打开客户端并配置相关节点。我发现一个据我观察每次都能成功的解决办法，就是把当前用户注销重新登陆后状态栏图标能够正常显示。

**Qv2ray 本应该是怎样工作的？**
无论怎样打开客户端都应该在状态栏正常显示图标

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 

**相关截图或日志**

1. 
![image](https://user-images.githubusercontent.com/44485638/71393407-4deafa00-2647-11ea-8e3c-25404bf4d8d8.png)

2. 
![image](https://user-images.githubusercontent.com/44485638/71393415-59d6bc00-2647-11ea-878d-875a9a59800c.png)

3.下面这个是典型症状截图，注意右上角没有相关图标
![image](https://user-images.githubusercontent.com/44485638/71393572-29435200-2648-11ea-94bf-871069231f27.png)

**系统信息**
 - 系统类型（windows, linux, macos）
    - Ubuntu 18.04.2 Desktop
 - 是从release下载的还是自己编译的
    - 从release下载的
 - 首选项里的版本号：
    - v1.3.8.0

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

-我发现一个据我观察每次都能成功的解决办法，就是把当前用户注销重新登陆后状态栏图标能够正常显示。

**Comment by DuckSoft** [comment]
您可以考虑尝试一下我们的 dev 分支上的最新版本。
可在 GItHub Action 上下载 AppImage，或者从源码进行编译。

我手头上没有 Ubuntu，也没有 GNOME 桌面环境，无法进行复现。
需要进一步调查。

**Comment by DuckSoft** [comment]
很可能是上游问题，可以参考一下其他应用有无类似问题。
附送：
https://askubuntu.com/questions/1080632/missing-system-tray-icons-ubuntu-gnome-18-04

**Comment by Double-Wen** [comment]
确实是ubuntu本身存在的问题，我已经解决了，多谢啦

**Comment by xiao-ma-nong** [comment]
> 确实是ubuntu本身存在的问题，我已经解决了，多谢啦

怎么解决的。
重启一下就有了，但是有时候就消失了。
ubuntu20
