### ISSUE TITLE
支持 Windows 开机自启切换

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#194]

**Comment by lhy0403** [comment]
@DuckSoft Should we set the REG key or placing a `lnk` into the `startup` folder?

**Comment by DuckSoft** [comment]
> @DuckSoft Should we set the REG key or placing a `lnk` into the `startup` folder?

I think the latter is better. This will be more transparent to user.

**Comment by lhy0403** [comment]
Cool

**Comment by DuckSoft** [comment]
Reference: https://docs.microsoft.com/en-us/windows/win32/shell/links
https://stackoverflow.com/questions/3906974/how-to-programmatically-create-a-shortcut-using-win32

**Comment by lhy0403** [comment]
Ack

**Comment by lhy0403** [comment]
By carefully read the docs and the docs and discussions, I decided to store that info into REG.
It's easy for centralized management. and prevent user renaming the lnk file accidently.

**Comment by lhy0403** [comment]
`HKCU\Software\Microsoft\Windows\CurrentVersion\Run`

**Comment by lhy0403** [comment]
It's easy to implement and prevent nasty WINAPI calls.

**Comment by DuckSoft** [comment]
Tested with no problem.

**Comment by lhy0403** [comment]
Closing.
