### ISSUE TITLE
v2ray core failed with errcode:255

### ISSUE THREAD

**Issue by gsg360** [lhy0403/Qv2ray#195]
在反馈 bug 之前，您可以去我们的 [Telegram Group](https://t.me/qv2ray) 寻求帮助

**如何复现这个bug：**
1. 
2. 
3. 
4. 

**Qv2ray 本应该是怎样工作的？**
?

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 
x

**相关截图或日志**
x
**系统信息**
 - 系统类型（windows, linux, macos）
    - deepin
 - 是从release下载的还是自己编译的
    - release
 - 首选项里的版本号：
    - 1.99.3

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

-x

**Comment by lhy0403** [comment]
We need more detail

**Comment by lhy0403** [comment]
Another comfirmation, is this account a bot?
cc @DuckSoft ?

**Comment by DuckSoft** [comment]
It's critical for us to know how to reproduce the bug rather than the bug itself.
Please, provide with us the steps to reproduce.

**Comment by DuckSoft** [comment]
No further response, closing.
