### ISSUE TITLE
关于QT界面在高分屏下的适配问题

### ISSUE THREAD

**Issue by Double-Wen** [lhy0403/Qv2ray#200]
在反馈 bug 之前，您可以去我们的 [Telegram Group](https://t.me/qv2ray) 寻求帮助

**如何复现这个bug：**
1. 使用Ubuntu 18.04.3 Desktop amd64版本，原生gnome桌面
2. 拥有一个屏幕分辨率为4K的电脑

**Qv2ray 本应该是怎样工作的？**
界面正常显示

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 

**相关截图或日志**
![image](https://user-images.githubusercontent.com/44485638/71545031-343c1080-29c1-11ea-8de0-efcd14019000.png)

**系统信息**
 - 系统类型（windows, linux, macos）
    - NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

 - 是从release下载的还是自己编译的
    - 从release里面下载的
 - 首选项里的版本号：
    - 1.3.8.0

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

-我也下载过你们的最新发布的release非稳定版本，4K分辨率下依然有如图所示的异常。在系统设置里面调整放大系数是没有作用的。
异常主要集中在入站设置这个地方，不过我大致摸清楚了你们的配置文件我可以不依靠这个界面也能正常配置，但是希望你们弄一下高分屏适配。另外，我在/etc/profile中设置变量export QT_SCALE_FACTOR=2.00并source和重新登录，确实可以放大，但是对于如图所示的这个界面的异常还是无能为力的。

**Comment by lhy0403** [comment]
你好，理论上不支持高分屏的程序在高分屏下的显示结果应该是字体偏小，
不知道您这是什么情况，为什么字体变得这么大

**Comment by DuckSoft** [comment]
参考一下：
https://wiki.archlinux.org/index.php/HiDPI_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)#Qt_5

**Comment by DuckSoft** [comment]
您可能错误地使用了环境变量。
同为高分屏(13.3in, 1080p)，`QT_SCALE_FACTOR=2.00`的效果：
![图片](https://user-images.githubusercontent.com/7822648/71546171-14abe480-29cf-11ea-8f46-353a96052461.png)

设置`QT_AUTO_SCREEN_SCALE_FACTOR=1`的效果：
![图片](https://user-images.githubusercontent.com/7822648/71546184-415ffc00-29cf-11ea-9cae-00bd24b217e6.png)

设置`QT_SCREEN_SCALE_FACTORS=2.0`的效果：
![图片](https://user-images.githubusercontent.com/7822648/71546207-78361200-29cf-11ea-8804-c590525a801e.png)

**Comment by DuckSoft** [comment]
您可以参考文中所述对 DPI 进行手动调整。
https://www.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6

**Comment by Double-Wen** [comment]
你好，我可能确实错误地使用了环境变量，但是与我第一次提到的设置放大倍数无关，请听我慢慢说，我把这个Qv2ray放在了我的开机启动项里面，然后它能自动启动，如图
![image](https://user-images.githubusercontent.com/44485638/71546314-9ea87d00-29d0-11ea-9cc1-afc640ea17d6.png)
通过自启来启动的程序它的表现非常正常，就像这个样子，
![image](https://user-images.githubusercontent.com/44485638/71546333-d0214880-29d0-11ea-834d-9d0c48142898.png)
但是手动打开程序就如我issue中提到的那样有有问题，重点不是字体大小，而是出站设置和入站设置那一块异常，这一块肯定语法啥的有跟其他地方有不一样的地方导致了它的不完美，虽然我已经通过开机自启解决了我的问题，但是希望你们精益求精，做得更好。
最后要表达的是能跟你们这些优秀的开发者交流我深感荣幸。

**Comment by DuckSoft** [comment]
个人认为是因为设置了一些奇怪的环境变量导致的。
方便的话，请在终端执行命令 `export`，然后将输出贴上来，我们排查一下。

**Comment by Double-Wen** [comment]
declare -x ALL_PROXY="socks://127.0.0.1:1080/"
declare -x CLUTTER_IM_MODULE="xim"
declare -x COLORTERM="truecolor"
declare -x DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"
declare -x DESKTOP_SESSION="ubuntu-communitheme-snap"
declare -x DISPLAY=":1"
declare -x GDMSESSION="ubuntu-communitheme-snap"
declare -x GJS_DEBUG_OUTPUT="stderr"
declare -x GJS_DEBUG_TOPICS="JS ERROR;JS LOG"
declare -x GNOME_DESKTOP_SESSION_ID="this-is-deprecated"
declare -x GNOME_SHELL_SESSION_MODE="ubuntu-communitheme"
declare -x GNOME_TERMINAL_SCREEN="/org/gnome/Terminal/screen/2e1be891_cd03_4451_8d51_2b075d151862"
declare -x GNOME_TERMINAL_SERVICE=":1.79"
declare -x GPG_AGENT_INFO="/run/user/1000/gnupg/S.gpg-agent:0:1"
declare -x GTK2_RC_FILES="/snap/communitheme/current/share/themes/Communitheme/gtk-2.0/gtkrc"
declare -x GTK_IM_MODULE="ibus"
declare -x GTK_MODULES="gail:atk-bridge"
declare -x HOME="/home/ubuntu"
declare -x HTTPS_PROXY="http://127.0.0.1:1081/"
declare -x HTTP_PROXY="http://127.0.0.1:1081/"
declare -x IM_CONFIG_PHASE="2"
declare -x LANG="en_US.UTF-8"
declare -x LANGUAGE="en_US:en"
declare -x LC_ADDRESS="en_US.UTF-8"
declare -x LC_IDENTIFICATION="en_US.UTF-8"
declare -x LC_MEASUREMENT="en_US.UTF-8"
declare -x LC_MONETARY="en_US.UTF-8"
declare -x LC_NAME="en_US.UTF-8"
declare -x LC_NUMERIC="en_US.UTF-8"
declare -x LC_PAPER="en_US.UTF-8"
declare -x LC_TELEPHONE="en_US.UTF-8"
declare -x LC_TIME="en_US.UTF-8"
declare -x LESSCLOSE="/usr/bin/lesspipe %s %s"
declare -x LESSOPEN="| /usr/bin/lesspipe %s"
declare -x LOGNAME="ubuntu"
declare -x LS_COLORS="rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:"
declare -x NO_PROXY="localhost,127.0.0.0/8,172.17.0.0/12,192.168.0.0/16,::1"
declare -x OLDPWD
declare -x PAPERSIZE="letter"
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
declare -x PWD="/home/ubuntu"
declare -x QT4_IM_MODULE="xim"
declare -x QT_ACCESSIBILITY="1"
declare -x QT_IM_MODULE="xim"
declare -x QT_SCALE_FACTOR="3.00"
declare -x SESSION_MANAGER="local/debian:@/tmp/.ICE-unix/11706,unix/debian:/tmp/.ICE-unix/11706"
declare -x SHELL="/bin/bash"
declare -x SHLVL="1"
declare -x SSH_AGENT_PID="1404"
declare -x SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"
declare -x TERM="xterm-256color"
declare -x TEXTDOMAIN="im-config"
declare -x TEXTDOMAINDIR="/usr/share/locale/"
declare -x USER="ubuntu"
declare -x USERNAME="ubuntu"
declare -x VTE_VERSION="5202"
declare -x WINDOWPATH="2"
declare -x XAUTHORITY="/run/user/1000/gdm/Xauthority"
declare -x XDG_CONFIG_DIRS="/etc/xdg/xdg-ubuntu-communitheme-snap:/etc/xdg/xdg-ubuntu:/etc/xdg"
declare -x XDG_CURRENT_DESKTOP="communitheme:ubuntu:GNOME"
declare -x XDG_DATA_DIRS="/snap/communitheme/current/share/:/usr/share/ubuntu-communitheme-snap:/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop"
declare -x XDG_MENU_PREFIX="gnome-"
declare -x XDG_RUNTIME_DIR="/run/user/1000"
declare -x XDG_SEAT="seat0"
declare -x XDG_SESSION_DESKTOP="ubuntu-communitheme-snap"
declare -x XDG_SESSION_ID="10"
declare -x XDG_SESSION_TYPE="x11"
declare -x XDG_VTNR="2"
declare -x XMODIFIERS="@im=ibus"
declare -x all_proxy="socks://127.0.0.1:1080/"
declare -x http_proxy="http://127.0.0.1:1081/"
declare -x https_proxy="http://127.0.0.1:1081/"
declare -x no_proxy="localhost,127.0.0.0/8,172.17.0.0/12,192.168.0.0/16,::1"

**Comment by DuckSoft** [comment]
问题原因应该就出在 QT_SCALE_FACTOR="3.00" 这一行上。
您是否将其放置在了 `/etc/profile` 中？若有，可以考虑将其去掉，并换成：
`QT_AUTO_SCREEN_SCALE_FACTOR=1`
使 Qt 自动检查您的屏幕缩放比率。

**Comment by Double-Wen** [comment]
还有上次那个部分桌面右上角图标不显示的问题的最完美的解决方案是
`nohup gnome-shell --replace &`
这个确实是上游ubuntu的问题，但是希望你们贴出来一下帮助更多的人

**Comment by DuckSoft** [comment]
> 还有上次那个部分桌面右上角图标不显示的问题的最完美的解决方案是
> `nohup gnome-shell --replace &`
> 这个确实是上游ubuntu的问题，但是希望你们贴出来一下帮助更多的人

Noted. 将写入 Wiki 的 FAQ 中。

**Comment by Double-Wen** [comment]
你好，我就是因为刚开始显示异常才设置了QT_SCALE_FACTOR="3.00"，我刚才研究了一会，设置QT_SCALE_FACTOR="3.00"只会导致放大与否，与异常没有关系，至少坏的原因不是这个3.00导致的。但是按您所说的设置QT_AUTO_SCREEN_SCALE_FACTOR=1确实可以完美解决问题。无论是自启还是手动启动。

**Comment by DuckSoft** [comment]
设置界面的部分文本框没有设置自动纵向占满，应属 UI 设计问题，稍后将单独开启一个 Issue。
除了这个问题之外，还有其他与本 Issue 标题有关的问题吗？
若问题已经解决，您可 Close 本 Issue。
