### ISSUE TITLE
Linux 开机自动启动支持

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#204]
方法：在 `$HOME/.config/autostart` 文件夹中放置/清除本应用程序的 `.desktop` 文件即可。
应该不难实现。

**Comment by lhy0403** [comment]
（可以从nextcloud客户端上抄一个）

**Comment by lhy0403** [comment]
Fixed in some previous commits.

**Comment by DuckSoft** [comment]
Tested in v1.99.4.2525. 
Closing.
