### ISSUE TITLE
间歇性连不上谷歌，但却可以连上油管

### ISSUE THREAD

**Issue by lfxx** [lhy0403/Qv2ray#206]
在反馈 bug 之前，您可以去我们的 [Telegram Group](https://t.me/qv2ray) 寻求帮助

**如何复现这个bug：**
1. 打开软件，配置好账号，刚开始可以连上谷歌，然后突然就连不上了，报This site can’t be reached错误

**Qv2ray 本应该是怎样工作的？**

1.可以正常浏览谷歌

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 
1.使用另外一个开源项目v2rayN可以正常连接

**相关截图或日志**
![image](https://user-images.githubusercontent.com/27956643/71567214-440a4080-2af8-11ea-94eb-0ebce4a4a734.png)
![image](https://user-images.githubusercontent.com/27956643/71567325-24bfe300-2af9-11ea-96a4-fa07217ec727.png)

**系统信息**
 - 系统类型（windows, linux, macos）
    - ubuntu18.04
 - 是从release下载的还是自己编译的
    - release
 - 首选项里的版本号：
    - v1.99.4.2405

**其他信息**
连接油管一直都是正常的，使用谷歌搜东西就会出现这种错误

-

**Comment by lhy0403** [comment]
Possible upstream
检查一下 DNS 设置，怀疑 DNS 污染

**Comment by lfxx** [comment]
本机dns还是,可否详细一点，如果dns被污染了，在qv2ray软件首选项的网络连接设置处的自定义dns列表处增加dns是否有效

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/71567611-5b96f880-2afb-11ea-8796-9f83f83595ce.png)
在首选项的连接设置中关闭使用本机DNS。保存，重启软件。

**Comment by lhy0403** [comment]
@DuckSoft 不需要重启软件，Qv2ray 会自动重新应用设置重新连接

**Comment by lfxx** [comment]
如您所言，已修复＠lhy0403
