### ISSUE TITLE
使用pac功能时，连接速度缓慢，网页加载不全，手动设置代理无此问题

### ISSUE THREAD

**Issue by lfxx** [lhy0403/Qv2ray#207]
在反馈 bug 之前，您可以去我们的 [Telegram Group](https://t.me/qv2ray) 寻求帮助

**如何复现这个bug：**
1. qv2ray选中使用pac,代理模式选择socks，因为选择http直接无法连接，系统代理处选择启用系统代理
2. 可以浏览油管，但是速度极慢

**Qv2ray 本应该是怎样工作的？**

可以正常使用pac功能

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 

在开源项目v2rayN上可以正常使用pac

**相关截图或日志**

![image](https://user-images.githubusercontent.com/27956643/71567585-28546980-2afb-11ea-82db-d72153f3c9a3.png)
![image](https://user-images.githubusercontent.com/27956643/71567595-3dc99380-2afb-11ea-9a53-bd33f4a7566e.png)
![image](https://user-images.githubusercontent.com/27956643/71567606-4e7a0980-2afb-11ea-98e3-591610a39639.png)
![image](https://user-images.githubusercontent.com/27956643/71567674-be888f80-2afb-11ea-8601-368213d6a204.png)
当使用手动设置时，如下图：
![image](https://user-images.githubusercontent.com/27956643/71567735-44a4d600-2afc-11ea-8d65-b13cec67dd6d.png)
则速度极快

**系统信息**
 - 系统类型（windows, linux, macos）
    - ubuntu18.04
 - 是从release下载的还是自己编译的
    - release
 - 首选项里的版本号：
    - 1.99.4.2405

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

-

**Comment by lhy0403** [comment]
你好，请问 Qv2ray 配置文件夹中的 GFWList 有下载过吗

**Comment by lhy0403** [comment]
或者，您可以提供以下 Qv2ray 和 v2rayN 中生成的不同  PAC 文件

**Comment by lfxx** [comment]
下面是qv2ray的gfwlist:
[gfwList.txt](https://github.com/lhy0403/Qv2ray/files/4009021/gfwList.txt)

**Comment by lhy0403** [comment]
请确认一下是不是 DNS 的问题，经过测试并没有感觉出速度慢的现象

#206

**Comment by lhy0403** [comment]
PAC 仅作为判断一个给定域名是否需要进行代理的脚本，理论上不会出现网速瓶颈

**Comment by lfxx** [comment]
> PAC 仅作为判断一个给定域名是否需要进行代理的脚本，理论上不会出现网速瓶颈

观察了一下，启用pac后，网页加载速度还是挺快，只是图片加载不出来，是因为dns问题吗

**Comment by lhy0403** [comment]
您可以在 首选项窗口中的 连接设置  页面
去掉勾选 “使用本地 DNS”
然后在下面手动添加一个可信的 DNS 
![image](https://user-images.githubusercontent.com/18734999/71570476-221cb800-2b10-11ea-8161-5a8cf5b3a8dd.png)

**Comment by lfxx** [comment]
好的，建议作者大大增加一个用户pac功能，因为github这种网站不在pac上名单上却访问缓慢，增加该功能可以有效解决该问题

**Comment by lhy0403** [comment]
好的

**Comment by DuckSoft** [comment]
Case closed?

**Comment by lhy0403** [comment]
Waiting to confirm the workaround @lfxx

**Comment by lfxx** [comment]
图片加载缓慢问题在更换dns后依然存在，我自己再看看吧，谢谢你＠lhy0403

**Comment by charles-sun0v0** [comment]
资源加载不全我也偶尔遇到，感觉是 cdn 因素引起的，虽然我不懂其原因

**Comment by DuckSoft** [comment]
> 资源加载不全我也偶尔遇到，感觉是 cdn 因素引起的，虽然我不懂其原因
这都0202年了，PAC功能早已不推荐使用。
![图片](https://user-images.githubusercontent.com/7822648/77145078-896c5780-6ac2-11ea-9df4-09873fce6612.png)
欢迎体验最新版本中的自定义分流功能～
