### ISSUE TITLE
Suggestion: dns resolution pass proxy as a default

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#208]
To prevent local DNS pollution.
And to defend your browsing privacy.

**Comment by DuckSoft** [comment]
> Referenced from #201:
请修复取消勾选“绕过中国大陆”时DNS仍然不通过代理直接查询的问题
解决方案：与绕过大陆与否无关，与是否使用本地 DNS 有关。
![图片](https://user-images.githubusercontent.com/7822648/71582618-f74d5680-2b45-11ea-8bbe-3647c99e9af7.png)

建议：默认不使用本地 DNS。

**Comment by lhy0403** [comment]
Fixed but will only affect the newly generated config, existing config will not be changed.

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/71623244-203d1c80-2c16-11ea-8b06-ebc6a84328ca.png)
Proven fixed. Closing.
