### ISSUE TITLE
关于v0.9.9b

### ISSUE THREAD

**Issue by ZLplLQc** [lhy0403/Qv2ray#21]
* 添加服务器时uuid留空，再点下那个服务器，程序会崩溃。
* 添加服务器 `1.1.1.1:1` 然后再添加 `1.1.1.1:2` 前一个被后一个取代了。有时同一个服务器会在不同端口上提供不同配置的v2ray服务。
* 首选项窗口每点一次弹一个新的，有点乱。
* 我把v2ray-core所有文件放到 `./qv2ray.d/core/`，尝试启动`1.1.1.1`的时候提示找不到`qv2ray.d\geoip.dat`点完OK，状态显示已启动但实际上并没有v2ray.exe的进程（没错，我在用windows）。
* 启动`1.1.1.1`后启动`1.1.1.2`，除了日志清空了好像什么也没发生。
* 添加、移除非运行中的配置时，v2ray-core重启了。
* 托盘图标的重启和停止好像反了。

暂时只发现这些。

**Comment by lhy0403** [comment]
> 添加服务器时uuid留空，再点下那个服务器，程序会崩溃。

是JSON解析问题

> 添加服务器 1.1.1.1:1 然后再添加 1.1.1.1:2 前一个被后一个取代了。有时同一个服务器会在不同端口上提供不同配置的v2ray服务。

是配置文件名问题，目前按照服务器地址（没包含端口号）保存配置

> 首选项窗口每点一次弹一个新的，有点乱。

是模态对话框设置问题 

> 我把v2ray-core所有文件放到 ./qv2ray.d/core/，尝试启动1.1.1.1的时候提示找不到qv2ray.d\geoip.dat点完OK，状态显示已启动但实际上并没有v2ray.exe的进程（没错，我在用windows）。

是 UI 逻辑问题，这个在 v0.9.9a 里面就有，没有来得及修改

> 启动1.1.1.1后启动1.1.1.2，除了日志清空了好像什么也没发生。

在启动一个配置后单击另一个配置并再次点击启动时，不会修改当前选择的配置文件，你可以双击配置或停止后单击选择配置再启动

> 添加、移除非运行中的配置时，v2ray-core重启了。

触发了重载配置函数，这个尽量想办法修复

> 托盘图标的重启和停止好像反了。

Sorry 这个是纯翻译问题

Thanks for your contribution 💗!

**Comment by lhy0403** [comment]
Done fixing, can you please build and test it?

**Comment by lhy0403** [comment]
> 添加、移除非运行中的配置时，v2ray-core重启了。

现在移除非运行配置时不会重启，但是添加时仍然会出现这种情况
现在 配置文件名默认包含端口号，即使不写hostname 也会生成一个 _0 文件（ 下划线为分隔符，0是默认端口）

**Comment by ZLplLQc** [comment]
> Done fixing, can you please build and test it?

这些都是功能性的问题，你那边测试没问题就行了。

**Comment by lhy0403** [comment]
Released, so close.

**Comment by lhy0403** [comment]
FYI: Fixed in Release v1 RC1
