### ISSUE TITLE
[ux] problematic configuration ui size 

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#210]
![图片](https://user-images.githubusercontent.com/7822648/71623825-15848680-2c1a-11ea-8017-cb2eb5d52b91.png)

**Comment by lhy0403** [comment]
Redesign of this panel is in progress

**Comment by lhy0403** [comment]
Some redesigns are finished, but not fully completed, 16b9841

**Comment by lhy0403** [comment]
Is it better in 1.99.5 ?

**Comment by DuckSoft** [comment]
Improved. 
![图片](https://user-images.githubusercontent.com/7822648/72463509-5c739e00-380e-11ea-89f1-8a355839926b.png)

Still, there are problems.
