### ISSUE TITLE
[AUR] remove makeshift QString wrapper for default paths

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#212]
Tested in newer version.

**Comment by lhy0403** [comment]
@DuckSoft @DuckSoft 这是啥/

**Comment by DuckSoft** [comment]
> 
> 
> @DuckSoft @DuckSoft 这是啥/

dev 上的新版本关于 qmake 参数不需要加 `QString()` 的 commit 已经测试过了。
准备更新到 AUR。


给我自己看的。

**Comment by lhy0403** [comment]
受到

**Comment by DuckSoft** [comment]
https://aur.archlinux.org/cgit/aur.git/commit/?h=qv2ray-dev-git&id=859cf6ae0476eb47aacf4dea0034742032477327

Fixed.
