### ISSUE TITLE
定制客户端 接不接啊 我有个V2RAY 有几处BUG electron 做的

### ISSUE THREAD

**Issue by ilovebamboo** [lhy0403/Qv2ray#215]
在反馈 bug 之前，您可以去我们的 [Telegram Group](https://t.me/qv2ray) 寻求帮助

**如何复现这个bug：**
1. 
2. 
3. 
4. 

**Qv2ray 本应该是怎样工作的？**

TG号：https://t.me/Superx007
**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 

**相关截图或日志**

**系统信息**
 - 系统类型（windows, linux, macos）
    - 
 - 是从release下载的还是自己编译的
    - 
 - 首选项里的版本号：
    - 

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

-

**Comment by lhy0403** [comment]
No, Thanks.
