### ISSUE TITLE
[ux] considering adding "configuration" into tray menu

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#218]
![图片](https://user-images.githubusercontent.com/7822648/71764853-45889e00-2f28-11ea-8b27-e4d84823d73c.png)

**Comment by lhy0403** [comment]
"Configuration?"
Did you mean `Preference Window`?

**Comment by DuckSoft** [comment]
> "Configuration?"
> Did you mean `Preference Window`?

That's correct.

**Comment by lhy0403** [comment]
Fix applied, please download and have a try!

**Comment by DuckSoft** [comment]
Fix confirmed.
