### ISSUE TITLE
出现 255错误

### ISSUE THREAD

**Issue by liangpu597** [lhy0403/Qv2ray#222]
1. 点击连接 出现 cannot start v2ray 错误代码 255

 - 系统类型（windows, linux, macos）
    -  ubuntu 16.04

**Comment by DuckSoft** [comment]
@liangpu597 rcvd。请提供细节，方便复现。

**Comment by lhy0403** [comment]
Possible caused by #223

**Comment by BigaMachine** [comment]
Ubuntu 19.10
v2ray核心错误255

我的解决方法：先用旧版本，导入v2ray-core，再用新版本，即可正常使用。

**Comment by DuckSoft** [comment]
Closed and fixed by #233.
Will blame on UX.

**Comment by JialingRichard** [comment]
这个错误我也遇到了，先是报错255，然后软件里面有检查v2ray核心的功能。我的问题是v2ray核心文件没有可执行权限，只需要chmod +x /某某/* 就可以了，别忘了把appimage文件的权限也给了。感谢开发者为我们考虑这么周到，谢谢
