### ISSUE TITLE
v2ray core file detection defect

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#223]
When Qv2ray tries to detect v2ray cores, under Linux and macOS, the executable file called `v2ray` may actually be a folder, due to wrong operation of users. Qv2ray mistake that the core exists and tries to execute a folder, causing a fatal 255 exit code.

**Comment by lhy0403** [comment]
@DuckSoft 收到

**Comment by lhy0403** [comment]
Fixed, please have a test.

**Comment by DuckSoft** [comment]
Tested in Linux. macOS shall work as the same.
Closing.
