### ISSUE TITLE
Qv2ray prevents shutdown

### ISSUE THREAD

**Issue by RigoLigoRLC** [lhy0403/Qv2ray#224]
If I had Qv2ray start with the OS, it would prevent the OS to be shut down.

**Screenshots**
![IMG_20200111_232718](https://user-images.githubusercontent.com/49363666/72206765-ae45bc80-34cc-11ea-8ce4-bf8cc2e34b66.jpg)

**System Information**

 Linux (Manjaro), KDE Plasma 5.17.
 Program built from Arch User Repository. Did not remember the version and will try to check that out later

**Comment by DuckSoft** [comment]
This is due to the missing of system shutdown/logout handlers in Qv2ray.
Assigned to @lhy0403.

**Comment by DuckSoft** [comment]
Developer Reference:

https://doc.qt.io/qt-5/qguiapplication.html#setFallbackSessionManagementEnabled
https://doc.qt.io/qt-5/qguiapplication.html#commitDataRequest

**Comment by DuckSoft** [comment]
Fix applied. Please have a test using the most recent build.
@RigoLigoRLC

**Comment by DuckSoft** [comment]
Closing for now. If problem persists, reopen this issue.

**Comment by RigoLigoRLC** [comment]
Issue fixed in 1.99.4.2713, built from Arch User Repository. Thank you.
