### ISSUE TITLE
[ux] intuitive v2ray core configuration

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#225]
Currently in Qv2ray v2 release candidate versions (with version number v1.99.4 and as latest as v1.99.4.2707), we have two important concepts, **V2ray Core Path** and **V2ray Assets Path** in our application. 

As of the feedback we have, quite a few users just get confused figuring out how the heck to fill in these two parameters, for example, not knowing V2ray Core is a single executable file and not knowing V2ray Assets is a folder of files, which in fact, shows a major lack in basic concepts of how are operating systems working behind the scene. As a result, issue #222 arises and #223 defect is found.

But us developers **cannot** blame users for not having the knowledge to use the software. As is stated in User Experience, if many users do it wrong, developers shall reflect on themselves. Here I propose a more transparent, user-friendly modification to get this thing right:

We shall add a "test v2ray core configuration" button in the general settings user-interface, which, once clicked, should check the configuration by *actually executing the specified v2ray file*, for example, `v2ray -version` and *actually check the assets*, for example, existence for `v2ctl`, `geosite.dat` and `geoip.dat`. If anything breaks in the process, abort and give the users a quick response on what's going on and wrong. Experience proves that knowing *why* something is broken is much more important than knowing something *is* broken.

Besides, we may also develop the ability to suggest and execute possible fixes for user. Imagine if user extract his/her core files inside `/home/user/.qv2ray/core/` **with an automatically created sub-folder** named whatever, unexperienced users will simply ignore the sub-folder and fill in the configurations as if that folder does not exist. But this is very close to a good configuration. In this case, we shall provide with user the ability to detect and automatically correct this behaviour, for example, modifying Core and Assets paths according to sub-folder name, with just one click on "automatic fix" button on our user-interface.

**Comment by lhy0403** [comment]
Automatically fixing the file location settings should not be part of the Qv2ray, however we can test the settings in the preference window

**Comment by lhy0403** [comment]
Just uploaded a fix, please have a test.

**Comment by DuckSoft** [comment]
Fixed in v1.99.5.2830. Closing
![图片](https://user-images.githubusercontent.com/7822648/72600325-600e3e80-394e-11ea-8b82-f986490425c2.png)
