### ISSUE TITLE
[ux] improve selection accessibility

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#227]
Sometimes users want to copy information displayed on Qv2ray directly, but soon they go frustrated since information is not selectable at all.

A couple of possible positions are listed below:

![图片](https://user-images.githubusercontent.com/7822648/72211406-cb4ab180-3505-11ea-8613-42256fc96601.png)
![图片](https://user-images.githubusercontent.com/7822648/72211419-f503d880-3505-11ea-8d12-6c40d30c28cb.png)

**Comment by lhy0403** [comment]
ACK

**Comment by DuckSoft** [comment]
Working on it.

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/72217512-e51de000-3569-11ea-8738-3ed9a7141874.png)

Finally we can select and copy version in About tab!
:fireworks: 

Closing!

**Comment by DuckSoft** [comment]
PS: This is fixed by a8cc59b42e16cb981f709fce798d63da184888df.
