### ISSUE TITLE
启动过程失败

### ISSUE THREAD

**Issue by Dickxia** [lhy0403/Qv2ray#23]
v2ray core faqt5ct: using qt5ct plugin
Loaded config file.
Loaded translations zh-CN
qt5ct: D-Bus system tray: yes
QMetaObject::connectSlotsByName: No matching signal for on_clbutton_clicked()
Now start a connection: 香港 1 * 2
v2ray core failed with exit code  255
Now start a connection: 香港 2 * 1.5
v2ray core failed with exit code  255

iled with exit code  255

**Comment by lhy0403** [comment]
Can you provide your config file and Qv2ray settings `Qv2ray.conf` in your folder (`~/.qv2ray` for *nix, `./qv2ray.d` for Windows) please? I'll try to re-trigger the bug.
It seems the final configuration generated is corrupted.

**Comment by Dickxia** [comment]
{
    "v": "1",
    "runAsRoot": false,
    "logLevel": 2,
    "language": "zh-CN",
    "v2CorePath": "/bin/v2ray",
    "v2AssetsPath": "/etc/v2ray",
    "proxyDefault": true,
    "proxyCN": false,
    "withLocalDNS": true,
    "dnsList": [
        "8.8.8.8",
        "1.1.1.1",
        "4.4.4.4"
    ],
    "inBoundSettings": {
        "listenip": "127.0.0.1",
        "socks_port": 1080,
        "socks_useAuth": false,
        "socksAccount": {
            "user": "",
            "pass": ""
        },
        "http_port": 8000,
        "http_useAuth": false,
        "httpAccount": {
            "user": "",
            "pass": ""
        }
    },
    "mux": {
        "enabled": false,
        "concurrency": 1
    },
    "configs": [
        "香港 1 * 2",
        "香港 2 * 1.5",
        "香港 3* 1.5",
        "香港 4* 1.5",
        "香港 5* 1.5",
        "香港 6* 1.5",
        "香港 7* 1.5",
        "香港 8* 1.5",
        "香港 9* 1.5",
        "台湾 1* 1.5",
        "台湾 2* 1.5",
        "日本 1* 1.5",
        "日本 2* 1.5",
        "日本 3* 1.5",
        "美国 1* 1.5",
        "美国 2* 2",
        "美国 3* 1.5",
        "美国 4* 1.5"
    ]
}

**Comment by lhy0403** [comment]
Can you please provide your OS type? It's Linux, macOS or Windows?

**Comment by Dickxia** [comment]
> Can you please provide your OS type? It's Linux, macOS or Windows? As well as your config file ( one of those named `香港 5* 1.5.qv2ray.json`)
> **Please hide your server address and UUID with `*`**

 The OS I use is manjaro gnome(a linux OS)
This problem only happen when I use the offical edition,it's well perform when I use the package in the AUR
-----------------------------------------------------------------------------------------------------------------------
{
    "outbounds": [
        {
            "mux": {
                "concurrency": 1,
                "enabled": false
            },
            "protocol": "vmess",
            "sendThrough": "0.0.0.0",
            "settings": {
                "vnext": [
                    {
                        "address": "****************",
                        "port": 443,
                        "users": [
                            {
                                "alterId": 2,
                                "id": "**************************************",
                                "level": 0,
                                "security": "auto"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "dsSettings": {
                    "path": "/"
                },
                "httpSettings": {
                    "host": [
                        ""
                    ],
                    "path": ""
                },
                "kcpSettings": {
                    "congestion": false,
                    "downlinkCapacity": 20,
                    "header": {
                        "type": "none"
                    },
                    "mtu": 1350,
                    "readBufferSize": 1,
                    "tti": 20,
                    "uplinkCapacity": 5,
                    "writeBufferSize": 1
                },
                "network": "tcp",
                "quicSettings": {
                    "header": {
                        "type": "none"
                    },
                    "key": "",
                    "security": ""
                },
                "security": "tls",
                "sockopt": {
                    "mark": 0,
                    "tcpFastOpen": false,
                    "tproxy": "off"
                },
                "tcpSettings": {
                    "header": {
                        "request": {
                            "headers": {
                            },
                            "method": "GET",
                            "path": [
                            ],
                            "version": "1.1"
                        },
                        "response": {
                            "headers": {
                            },
                            "reason": "OK",
                            "status": "200",
                            "version": "1.1"
                        },
                        "type": "none"
                    }
                },
                "tlsSettings": {
                    "allowInsecure": false,
                    "alpn": [
                    ],
                    "certificates": [
                    ],
                    "disableSystemRoot": false,
                    "serverName": ""
                },
                "wsSettings": {
                    "headers": {
                        "Host": ""
                    },
                    "path": ""
                }
            },
            "tag": "outBound_PROXY"
        }
    ]
}

**Comment by lhy0403** [comment]
I'm sorry, I tried replacing your file content and the same file name, however, I could not re-generate the same bug. It seems strange.
```
$ v2ray --version          
V2Ray 4.20.0 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
```
You said:
> This problem only happen when I use the offical edition,it's well perform when I use the package in the AUR

Do you mean you install the `v2ray-bin` in AUR and start the connection in `Qv2ray` and it works?

If so that should be an upstream bug. Because what `Qv2ray` does is simply generate a complete v2ray connection config and send it to the v2ray kernel *(the `/bin/v2ray` as in your config file)*.

BTW, did you see any error messages (like some message pop-ups) before the ` v2ray core failed with exit code 255` appears in the terminal ?

**Comment by lhy0403** [comment]
Qv2ray creates a final config.json inside the folder `~/.qv2ray/genrerated/config.gen.json`
Please run v2ray self config test by inputting the commands below, **AFTER you click Start in Qv2ray**
`v2ray --test --config ~/.qv2ray/genrerated/config.gen.json`
And give me the output/

**Comment by lhy0403** [comment]
Did you have `v2ray-domain-list-community` and `v2ray-geoip` packages installed? They provide contents of `/etc/v2ray`, and it's required by Qv2ray.

FYI: 
those two packages are at:
https://www.archlinux.org/packages/community/any/v2ray-domain-list-community/
https://www.archlinux.org/packages/community/any/v2ray-geoip/

**Comment by lhy0403** [comment]
Is this thread still active?

**Comment by copurxia** [comment]
> Is this thread still active?

I use the package in AUR instead of offical.So that I haven't  care about it.

**Comment by lhy0403** [comment]
So closed and mark as solved. There are already an update in README explaining this issue.
