### ISSUE TITLE
[master] [ci] linux build failed at generating FS Struture

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#233]
https://github.com/lhy0403/Qv2ray/runs/385496906
Erroneous Stage: `Generate FS Structure for AppImage`
https://github.com/lhy0403/Qv2ray/blob/983fafe386dc6aa2858e109283073e8ef48ab02f/.github/workflows/build-push.yml#L105-L106

**Comment by DuckSoft** [comment]
CI for Linux at master branch is problematic. Please fix that.

cc @lhy0403

**Comment by lhy0403** [comment]
Ah just wait for the dev merge into version-v2 which will be merging into the master, which will fix this issue.
Qv2ray v2 was not using the Github Action thus it should not be maintained.

**Comment by DuckSoft** [comment]
Roger that. That is, 
**v1 releases are no longer available from GitHub Action and it's discontinued.**

Am I Correct? If so, please kindly close this issue, and attach a `wontfix`.

**Comment by lhy0403** [comment]
Yes it was my typo, sorry.

**Comment by DuckSoft** [comment]
Roger that. Marking as wontfix and closing.
