### ISSUE TITLE
[refactor] separate credit html from hardcoding

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#234]
For now the green-boxed stuff below is hard-coded directly in form files, which makes it very hard to maintain, and risks being unconsciously modified by Qt Creator and other IDEs.
![图片](https://user-images.githubusercontent.com/7822648/72217570-d7b52580-356a-11ea-9327-283023513cf0.png)

This issue is to track the refactor process of these stuff.

**Comment by lhy0403** [comment]
It's fixed in https://github.com/lhy0403/Qv2ray/commit/1d2f6f91c1a20a54dbfae53a9345af7ca59881e3 closing.
