### ISSUE TITLE
QSharedMemoryPrivate方法错误 unable to set key on lock

### ISSUE THREAD

**Issue by Neboer** [lhy0403/Qv2ray#235]
**如何复现这个bug：**
1. Ubuntu系统，安装Qv2ray，命令行下使用超级用户打开
2.关闭Qv2ray，但程序并没有终止，仅仅是窗口关闭了而已。
3. 以普通用户身份打开Qv2ray
4. 显示如下错误信息。
```
[INIT]: v1.99.4.2405
SingleApplication: Unable to attach to shared memory block.
"QSharedMemoryPrivate::initKey: unable to set key on lock"
```
然后，Qv2ray会立即退出。如果使用超级用户打开Qv2ray，则不会出现这个问题。

**Qv2ray 本应该是怎样工作的？**
正常情况下，关闭窗口应该立即退出程序，并且无论是什么用户，都应该可以打开自己配置好的Qv2ray客户端，而不是报错后立即退出程序。
**相关截图或日志**

**系统信息**
 - 系统类型（windows, linux, macos）
    - linux Ubuntu 19.10
 - 是从release下载的还是自己编译的
    - ppa源。
`
Package: qv2ray
Version: 1.99.4-1~ubuntu19.10.1~ppa1
Priority: optional
Section: net
Maintainer: guobang <ymshenyu@gmail.com>
Installed-Size: 3,401 kB
Depends: libc6 (>= 2.14), libgcc1 (>= 1:3.0), libgrpc++1, libgrpc6, libprotobuf17, libqt5charts5 (>= 5.12.2-1~), libqt5core5a (>= 5.12.2+dfsg-4~), libqt5gui5 (>= 5.12.2+dfsg-4~) | libqt5gui5-gles (>= 5.12.2+dfsg-4~), libqt5network5 (>= 5.12.2+dfsg-4~), libqt5widgets5 (>= 5.12.2+dfsg-4~), libstdc++6 (>= 9)
Download-Size: 1,277 kB
APT-Manual-Installed: yes
APT-Sources: http://ppa.launchpad.net/ymshenyu/qv2ray/ubuntu eoan/main amd64 Packages
Description: v2ray linux Windows macOS GUI
`
 - 首选项里的版本号：
    - 1.99.4.2405

**Comment by lhy0403** [comment]
Running Qv2ray may lead to unexpected results

**Comment by lhy0403** [comment]
It's been fixed. Anyone can carry out a test?

**Comment by DuckSoft** [comment]
Test & fixed. Closing.

**Comment by Neboer** [comment]
Thanks
