### ISSUE TITLE
[suggestion] deprecate running Qv2ray as root user

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#236]
explicitly deprecate running Qv2ray using root.
even if user really want to run it as root, use some long command line parameter, such as: `--i-really-want-to-run-as-root`.

**Comment by lhy0403** [comment]
Good idea

**Comment by DuckSoft** [comment]
This may work as a solution for #235

**Comment by lhy0403** [comment]
It's been fixed. Anyone can carry out a test?

**Comment by DuckSoft** [comment]
Tested. Fixed. Closing.
