### ISSUE TITLE
v2ray core failed with errcode:255

### ISSUE THREAD

**Issue by touwoyimuli** [lhy0403/Qv2ray#237]
在反馈 bug 之前，您可以去我们的 [Telegram Group](https://t.me/qv2ray) 寻求帮助

**如何复现这个bug：**
1. 在uos20系统里面（是deepin15.11的下一个版本）环境下；
2. 运行`Qv2ray-refs.tags.v1.99.4-linux.AppImage`在`~/softIns/`目录下运行
3. 添加Subscription，成功之后，点击connect失败；提示如下,
4. 然后查看目录文件结构
![image](https://user-images.githubusercontent.com/33887845/72307172-6c776a80-36b4-11ea-9b48-b60d9cd38f88.png)

5.自己创建两个空的文件夹`vcore/v2ray/`，将下载的`v2ray-linux-arm64.zip`里面的全部解压到自己自己创建的文件夹下，如图；
![image](https://user-images.githubusercontent.com/33887845/72308592-c168b000-36b7-11ea-8862-98e1fcf810c6.png)

6.再次点击`connect`就会报错`v2ray core failed with errcode:255`

**Qv2ray 本应该是怎样工作的？**
按照预想，这个是可以工作的；但其实并没有成功的运行

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 
没有，该订阅在`win10`系统里面，在v2rayN里面能够成功google

**相关截图或日志**
截图如上，日志的话，如要如何提供？

**系统信息**
 - 系统类型（windows, linux, macos）
    - Linux（OS: Uos 20 buster   Kernel: x86_64 Linux 4.19.0-6-amd64）；我猜在deepin 15.11的版本也会出现相同的问题。很抱歉，我无法提供uos20的直接的下载包，请谅解；
 - 是从release下载的还是自己编译的
    - 都是从官网下载的，已经编译好的版本（具体的版本，参见上面的重现步骤）
    - https://github.com/v2ray/v2ray-core/releases/tag/v4.22.1
    - https://lhy0403.github.io/Qv2ray/zh-CN/
    - https://github.com/lhy0403/Qv2ray/releases
 - 首选项里的版本号：
    - [RC1] Qv2ray v2.0 RC1 预览版1

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*
我在另外一台uos20 （Linux）里面也重现了该问题；但是在deepin15系类没有提供尝试；
附：uos20是deepin20的新名称；是deepin15的下一个大的版本；
如果还需要其他的帮助（提供日志之类的），请继续保持联系

-

**Comment by lhy0403** [comment]
你好，

**Comment by huyizheng** [comment]
vcore/v2ray应该放v2ray的二进制，而不是放名为v2ray的文件夹

**Comment by lhy0403** [comment]
正确的目录格式应该是这样的：
![image](https://user-images.githubusercontent.com/18734999/72308472-91211180-36b7-11ea-8d89-b6ec3fb5319a.png)

**Comment by lhy0403** [comment]
这个在 dev 分支已经进行了修复，暂没有发布

**Comment by touwoyimuli** [comment]
好的，我刚刚尝试过了，仍然会出现写个错误`v2ray core failed with errcode:255`；不过非常感谢，能够如此之快得到帮助的回答，十分感谢你/你们；
![image](https://user-images.githubusercontent.com/33887845/72309068-d7c33b80-36b8-11ea-87b3-20796a0f311e.png)

**Comment by lhy0403** [comment]
有没有 chmod +x

**Comment by touwoyimuli** [comment]
没有，玩Linux的时间不算很长，我这会尝试一下（这会没有表情表就很气）；

我等待你们的新版本发布，我在网络方面还只是一个新手；如果有c++方面的项目需要帮助，我很愿意为开源软件提交代码

**Comment by lhy0403** [comment]
Thx！

**Comment by touwoyimuli** [comment]
我刚刚尝试一下了的，仍然不可以；
![image](https://user-images.githubusercontent.com/33887845/72309599-57053f00-36ba-11ea-98bd-de65916d58f5.png)

这会有点忙碌了，回聊

**Comment by lhy0403** [comment]
Please wait while RC2 is releasing.

**Comment by lhy0403** [comment]
This issue is marked as solved inside the telegram group. closing.

**Comment by xgdgsc** [comment]
错误提示可以友好一点，谁知道255什么意思

**Comment by DuckSoft** [comment]
@xgdgsc 您还别说，我还真就不知道255是什么意思，请您赐教。

**Comment by zpr1g** [comment]
请问现在解决了吗，我装的 2.1.2 也报这个错

**Comment by DuckSoft** [comment]
> 请问现在解决了吗，我装的 2.1.2 也报这个错

您注意看前文。原因是因为 v2ray core 没有赋予可执行权限。对 v2ray 文件 chmod +x 问题解决。
