### ISSUE TITLE
git clone 默认不会递归克隆

### ISSUE THREAD

**Issue by BlurryLight** [lhy0403/Qv2ray#24]
`git clone https://github.com/lhy0403/Qv2ray && cd Qv2ray
`
在README里你的Usage是这样的，但是git不会递归克隆`3rd party`文件夹内的`x2struct`，所以会导致编译失败, 找不到依赖。
可以改成
`git clone --recursive https://github.com/lhy0403/Qv2ray && cd Qv2ray`
或者改成

```
git clone https://github.com/lhy0403/Qv2ray && cd Qv2ray
lrelease ./Qv2ray.pro
```

**Comment by lhy0403** [comment]
Received, Thanks

**Comment by lhy0403** [comment]
It should now be changed to `--recursive`. Thanks for mentioning that! :heart:

**Comment by hailinzeng** [comment]
Wiki 也需要更新：https://github.com/Qv2ray/Qv2ray/wiki/Manually-Build-Qv2ray_zh

**Comment by DuckSoft** [comment]
> Wiki 也需要更新：https://github.com/Qv2ray/Qv2ray/wiki/Manually-Build-Qv2ray_zh

cc Chinese wiki maintainer @Neboer
