### ISSUE TITLE
[ui] ping button shall not be clickable until done or timeout

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#240]
Theoretically, you can click the button for infinite times to crash Qv2ray.

![图片](https://user-images.githubusercontent.com/7822648/72350111-bbef8200-3718-11ea-86fb-c2f046635fc0.png)

**Comment by lhy0403** [comment]
I personally don't think it's a bug, but a suggestion instead.
Probably will fix, but not in the RC2 for sure.

**Comment by DuckSoft** [comment]
roger that.

**Comment by lhy0403** [comment]
It doesn’t impact the performance too much, however adding this feature might involve some other issue, that is, lots of tcping handler instances will be created for each connection, just to track the tcping data.

It’s not a serious issue if a user rapidly click that ping button, the tcping handler is in asynchronous mode so it would not block....

**Comment by DuckSoft** [comment]
Rcvd. Closing.
