### ISSUE TITLE
[ux] rearrange host context menu

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#242]
![图片](https://user-images.githubusercontent.com/7822648/72399943-9d25d580-3782-11ea-8747-250a2f1ec697.png)

**Comment by lhy0403** [comment]
Will fix ASAP

**Comment by DuckSoft** [comment]
1. Connect
2. Share
3. Rename
4. Edit as JSON
5. Edit as Complex

**Comment by DuckSoft** [comment]
Fixed in v1.99.5.2803.
Closing.
