### ISSUE TITLE
机场订阅返回 vmess 的混淆方式 type 为 auto 导致 v2ray 无法正常启动

### ISSUE THREAD

**Issue by Refuel-ZL** [lhy0403/Qv2ray#243]
`main: failed to read config file: /home/zl/.config/qv2ray/generated/config.gen.json > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: v2ray.com/core/infra/conf/command: failed to parse json config > v2ray.com/core/infra/conf/serial: failed to parse json config > v2ray.com/core/infra/conf: Failed to build TCP config. > v2ray.com/core/infra/conf: invalid TCP header config > v2ray.com/core/infra/conf: unknown config id: auto`
` > exit status 255`

**Comment by lhy0403** [comment]
@Refuel-ZL 请确认您是手动导入的vmess吗？

**Comment by Refuel-ZL** [comment]
@lhy0403 某机场的订阅  三个连接报此错误 其他正常

**Comment by DuckSoft** [comment]
您可将出错的配置关键信息打码贴到这里，也可加入我们的 telegram 群组，私戳群主讨论。

https://t.me/qv2ray

**Comment by DuckSoft** [comment]
```json
{"id":"***************","port":"443","ps":"\u7f8e\u56fd","tls":"tls","aid":0,"v":2,"path":"","type":"auto","host":"","net":"tcp","add":"***.*****.net"}
```

拿到的配置文件。问题出在混淆方式字段 `type` 的值 `auto` 无效。
话说这是什么神奇的服务器，竟然能自动选择混淆方式。

**Comment by DuckSoft** [comment]
进一步实验表明，`auto` 混淆方式实际可为 `none`。
Qv2ray 将采取措施处理此类 vmess。

**Comment by DuckSoft** [comment]
await #244. 感谢您的反馈。

**Comment by DuckSoft** [comment]
@lhy0403 #244 的修复 c286d256066904dcaa3c99305f6256983bd5adef 又引入了新的问题。
这家机场的 `path` 和 `host` 都留了空字符串，其具体的处理措施有待讨论，但直接 fail 无疑会引起用户体验急剧下降。

将 fork 出两个 issue 分别解决。
