### ISSUE TITLE
[vmess] 将混淆方式 type 为 auto 的 vmess 处理为 none

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#244]
在 vmess 批量导入以及订阅导入 vmess 时，若遇混淆类型为 auto 的 vmess，直接将其替换为 none，以避免 v2ray 解析配置时崩溃。

批量导入时可以考虑显示警告。

@lhy0403

**Comment by lhy0403** [comment]
@DuckSoft ack

**Comment by lhy0403** [comment]
Tracker of #109 #243

**Comment by lhy0403** [comment]
Should be fixed in the latest `dev` branch. Please have a try.

**Comment by DuckSoft** [comment]
This is fixed. Closing.
