### ISSUE TITLE
关于 Qv2ray 安装的问题

### ISSUE THREAD

**Issue by zjy5755202** [lhy0403/Qv2ray#245]
你好 请问下我是按照这个教程进行安装的
https://lhy0403.github.io/Qv2ray/zh-CN/

我在下载完之后文件存储位置是这样子的

![image](https://user-images.githubusercontent.com/32031556/72415565-a4170d00-37af-11ea-9bd8-c2a2085cd38a.png)

但是我看文中写的哪个自动打开的文件夹  我这儿没有自动打开文件夹  就不知道应该解压到哪

设置的时候是这样设置的 
![image](https://user-images.githubusercontent.com/32031556/72415704-fce6a580-37af-11ea-9537-fd43948f1bf5.png)

虽然能够连接上 但是报了这个错
![image](https://user-images.githubusercontent.com/32031556/72415655-db85b980-37af-11ea-8064-3cad00d8d8f3.png)

也不能翻墙   请问下是什么问题

**Comment by Refuel-ZL** [comment]
![image](https://user-images.githubusercontent.com/22957560/72415789-391a0600-37b0-11ea-8abb-7d46dc489f40.png)

**Comment by lhy0403** [comment]
你好，首先 github page 上的 教程已经过时了，最新的教程在这里： https://github.com/lhy0403/Qv2ray/wiki/Getting-Started-step0

获取数据失败的情况，请确认您没有其他的 v2ray 程序在运行

请尝试一下昨天发布的  1.99.5 https://github.com/lhy0403/Qv2ray/releases/latest

**Comment by zjy5755202** [comment]
好的！&nbsp;
十分感谢&nbsp;
我去试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Leroy.H.Y"<notifications@github.com&gt;; 
发送时间: 2020年1月15日(星期三) 下午4:01
收件人: "lhy0403/Qv2ray"<Qv2ray@noreply.github.com&gt;; 
抄送: "朱江源"<1181370590@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lhy0403/Qv2ray] 关于QV2ray安装的问题 (#245)




你好，首先 github page 上的 教程已经过时了，最新的教程在这里： https://github.com/lhy0403/Qv2ray/wiki/Getting-Started-step0
 
获取数据失败的情况，请确认您没有其他的 v2ray 程序在运行
 
请尝试一下昨天发布的  1.99.5 https://github.com/lhy0403/Qv2ray/releases/latest

**Comment by DuckSoft** [comment]
@zjy5755202 进展如何？若已经解决，您可 close 本 issue。
若仍未解决，建议加入 Telegram 交流群 https://t.me/qv2ray 讨论解决。

**Comment by zjy5755202** [comment]
您好，昨天出了点问题，就没有及时回复。
今天早上重新试了一下，能够连接上了。
也能看到有网速，但是我的浏览器还是无法访问被墙的网站。
我主要是想翻墙然后拉取docker镜像配置k8s环境。
前辈请问下这样的需求还需要做什么样的配置呢？







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"DuckSoft"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月16日(星期四) 凌晨3:16
收件人:&nbsp;"lhy0403/Qv2ray"<Qv2ray@noreply.github.com&gt;;
抄送:&nbsp;"朱江源"<1181370590@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [lhy0403/Qv2ray] 关于QV2ray安装的问题 (#245)




@zjy5755202 进展如何？若已经解决，您可 close 本 issue。
 若仍未解决，建议加入 Telegram 交流群 https://t.me/qv2ray 讨论解决。

**Comment by zjy5755202** [comment]
前辈 我重新调了一下VPN的设置 ，已经解决问题了
十分感谢您的帮助！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"DuckSoft"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月16日(星期四) 凌晨3:16
收件人:&nbsp;"lhy0403/Qv2ray"<Qv2ray@noreply.github.com&gt;;
抄送:&nbsp;"朱江源"<1181370590@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [lhy0403/Qv2ray] 关于QV2ray安装的问题 (#245)




@zjy5755202 进展如何？若已经解决，您可 close 本 issue。
 若仍未解决，建议加入 Telegram 交流群 https://t.me/qv2ray 讨论解决。

**Comment by zjy5755202** [comment]
前辈 我重新调了一下VPN的设置 ，已经解决问题了
十分感谢您的帮助！
还有一个问题想请教您。
我使用命令行拉取镜像的时候好像还是不能够拉取国外的镜像
请问下是还需要怎么操作才能在命令行中也使用代理来进行网络连接呢？


------------------ 原始邮件 ------------------
发件人:&nbsp;"DuckSoft"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月16日(星期四) 凌晨3:16
收件人:&nbsp;"lhy0403/Qv2ray"<Qv2ray@noreply.github.com&gt;;
抄送:&nbsp;"朱江源"<1181370590@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [lhy0403/Qv2ray] 关于QV2ray安装的问题 (#245)




@zjy5755202 进展如何？若已经解决，您可 close 本 issue。
 若仍未解决，建议加入 Telegram 交流群 https://t.me/qv2ray 讨论解决。

**Comment by lhy0403** [comment]
你可以使用 proxychains-ng 具体方法请参照 Google。

**Comment by zjy5755202** [comment]
好的！十分感谢前辈！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Leroy.H.Y"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月16日(星期四) 上午9:50
收件人:&nbsp;"lhy0403/Qv2ray"<Qv2ray@noreply.github.com&gt;;
抄送:&nbsp;"朱江源"<1181370590@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [lhy0403/Qv2ray] 关于 Qv2ray 安装的问题 (#245)




你可以使用 proxychains-ng 具体方法请参照 Google。
