### ISSUE TITLE
pac模式下无法访问wiki百科

### ISSUE THREAD

**Issue by Dyuzz** [lhy0403/Qv2ray#248]
PAC 模式下下载的 GFWList 文件，无法访问 Wikipedia

**Comment by Neboer** [comment]
是gitlab上的pac吗

**Comment by Dyuzz** [comment]
是的，github也是，GFWList则一直下载错误，有bug，会一直弹出文件内对话框













在 2020-01-16 10:31:16，"Neboer" <notifications@github.com> 写道：

是gitlab上的pac吗

**Comment by DuckSoft** [comment]
烦请告知出问题的客户端的版本号。

**Comment by Dyuzz** [comment]
v1.99.5.2781













在 2020-01-16 11:00:44，"DuckSoft" <notifications@github.com> 写道：

烦请告知出问题的客户端的版本号。

**Comment by DuckSoft** [comment]
收到。正在建立环境，准备重现。

**Comment by DuckSoft** [comment]
测试表明，Firefox 在配置 PAC 地址后非常正常。Chromium 正在实验中。
![图片](https://user-images.githubusercontent.com/7822648/72499612-51038f80-386d-11ea-8c61-062dd85a541a.png)
![图片](https://user-images.githubusercontent.com/7822648/72499617-56f97080-386d-11ea-86a0-06672a30a3dc.png)

**Comment by DuckSoft** [comment]
测试表明，Chromium 不认 KDE 的 PAC 设定，也不认 gsettings 的 PAC 设定。
目前因维护 PAC 费时费力，且成效不高，上游维护者可能已经歇菜或喝茶了。

Qv2ray 在 PAC 功能上的正确性已经测试成功。剩下的问题，可能只是您是否决定继续使用过时的 PAC 了。

**Comment by DuckSoft** [comment]
@ymshenyu 已经在 GNOME 上测试成功。
您出现的问题大概率是因为配置不当导致的。

您可考虑加入 Telegram 群组 https://t.me/qv2ray 与我们进行详细讨论。

**Comment by DuckSoft** [comment]
@ymshenyu 已经在 GNOME 上测试成功。
您出现的问题大概率是因为配置不当导致的。

您可考虑加入 Telegram 群组 https://t.me/qv2ray 与我们进行详细讨论。

**Comment by DuckSoft** [comment]
因无法得到有效反馈，暂时关闭本 issue。
若您确有困难加入 Telegram 群组进行交流，可重新开启本 issue。

感谢。
