### ISSUE TITLE
[ui] give a hint on PAC serving address

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#250]
![图片](https://user-images.githubusercontent.com/7822648/72515091-499eaf00-388a-11ea-9e00-66133718cb60.png)

If I don't read the source code, I won't even know that PAC serves at `http://<host>/pac`.
Try give user a hint, in case they want to manually configure PAC instead.

**Comment by lhy0403** [comment]
There used to be a label..... It might be accidentally removed, will add it back.

**Comment by lhy0403** [comment]
Just uploaded a fix, please have a test.

**Comment by DuckSoft** [comment]
![图片](https://user-images.githubusercontent.com/7822648/72600325-600e3e80-394e-11ea-8b82-f986490425c2.png)
Good. Fixed in v1.99.5.2830. Closing.
