### ISSUE TITLE
[cleanup] replace `Stringify` with `QStringList::join`

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#257]
https://github.com/lhy0403/Qv2ray/blob/69a9c23100fdc8e403b912acbb587256afe7caf2/src/main.cpp#L92-L95

https://github.com/lhy0403/Qv2ray/blob/69a9c23100fdc8e403b912acbb587256afe7caf2/src/main.cpp#L167

https://doc.qt.io/qt-5/qstringlist.html#join

---
Also, consider using an initializer list:

```cpp
QStringList configFilePaths({
    QDir::homePath() + "/.qv2ray" QV2RAY_CONFIG_DIR_SUFFIX,
    QDir::homePath() + "/.config/qv2ray" QV2RAY_CONFIG_DIR_SUFFIX,
    QDir::currentPath() + "/config" QV2RAY_CONFIG_DIR_SUFFIX
});
```

**Comment by lhy0403** [comment]
fixed

**Comment by DuckSoft** [comment]
AK. Closing.
