### ISSUE TITLE
订阅节点显示

### ISSUE THREAD

**Issue by updater1234** [lhy0403/Qv2ray#260]
你好，请问订阅的节点是有显示限制吗？为什么Windows下只能显示10个节点？

**Comment by DuckSoft** [comment]
v2 版本发布在即，攒了比较多的 bug 修复，您可尝试最新版本试一下看看还有无此问题。
传送门在这里：
https://github.com/lhy0403/Qv2ray/commit/526f74a7fbd1e0fe7039b8ba441a2ade959c8f66/checks?check_suite_id=407923862

找到右上角的 Artifacts，打开选 Windows 版本即可。
![图片](https://user-images.githubusercontent.com/7822648/72674075-88f91580-3aad-11ea-9e0c-0bf174fc32da.png)

另外，希望提出相关问题时能按照模板要求，写明相关环境信息，如所使用软件的版本号、问题的截图、出错的日志等。这将非常有助于我们重现并锁定问题。

**Comment by DuckSoft** [comment]
> 你好，请问订阅的节点是有显示限制吗？为什么Windows下只能显示10个节点？

理论上是不会出现此限制的。

若使用新版软件仍出现此问题，请考虑加入 https://t.me/qv2ray Telegram 群组与我们取得联系，私聊临时发送一下订阅链接以助调试使用，因 GitHub 上不适合发布此类内容。

开发人员保证不会滥用您的订阅链接。若您不放心，在调试之后，您可自行前往机场设定，将先前的订阅链接作废并更换。

**Comment by Qv2ray** [comment]
Should be fixed, please test from the Github Action..

**Comment by DuckSoft** [comment]
This is resolved. Checkout the newest version.
