### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by rubyKC** [lhy0403/Qv2ray#27]
Application: Qv2ray (Qv2ray), signal: Aborted
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f830b7e7c80 (LWP 2913))]

Thread 6 (Thread 0x7f82f8895700 (LWP 2918)):
#0  0x00007f830d9d9479 in g_mutex_lock () at /usr/lib/libglib-2.0.so.0
#1  0x00007f830da28979 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007f830da28b51 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007f830f0ef9bc in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#4  0x00007f830f0965ec in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#5  0x00007f830eec92f5 in QThread::exec() () at /usr/lib/libQt5Core.so.5
#6  0x00007f830eeca520 in  () at /usr/lib/libQt5Core.so.5
#7  0x00007f830edf057f in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007f830eb1c0e3 in clone () at /usr/lib/libc.so.6

Thread 5 (Thread 0x7f82f98db700 (LWP 2917)):
#0  0x00007f830edf6415 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f82f9be4e9c in  () at /usr/lib/dri/i965_dri.so
#2  0x00007f82f9be4a98 in  () at /usr/lib/dri/i965_dri.so
#3  0x00007f830edf057f in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f830eb1c0e3 in clone () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7f8301f69700 (LWP 2916)):
#0  0x00007f830eb11667 in poll () at /usr/lib/libc.so.6
#1  0x00007f830da28a80 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007f830da28b51 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007f830f0ef9bc in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#4  0x00007f830f0965ec in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#5  0x00007f830eec92f5 in QThread::exec() () at /usr/lib/libQt5Core.so.5
#6  0x00007f830eeca520 in  () at /usr/lib/libQt5Core.so.5
#7  0x00007f830edf057f in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007f830eb1c0e3 in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7f830317a700 (LWP 2915)):
#0  0x00007f830da092e0 in g_thread_self () at /usr/lib/libglib-2.0.so.0
#1  0x00007f830da28b41 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#2  0x00007f830f0ef9bc in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#3  0x00007f830f0965ec in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#4  0x00007f830eec92f5 in QThread::exec() () at /usr/lib/libQt5Core.so.5
#5  0x00007f830af74b37 in  () at /usr/lib/libQt5DBus.so.5
#6  0x00007f830eeca520 in  () at /usr/lib/libQt5Core.so.5
#7  0x00007f830edf057f in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007f830eb1c0e3 in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7f830a3e7700 (LWP 2914)):
#0  0x00007f830eb11667 in poll () at /usr/lib/libc.so.6
#1  0x00007f830b83c630 in  () at /usr/lib/libxcb.so.1
#2  0x00007f830b83e2db in xcb_wait_for_event () at /usr/lib/libxcb.so.1
#3  0x00007f830b0ab049 in  () at /usr/lib/libQt5XcbQpa.so.5
#4  0x00007f830eeca520 in  () at /usr/lib/libQt5Core.so.5
#5  0x00007f830edf057f in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f830eb1c0e3 in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7f830b7e7c80 (LWP 2913)):
[KCrash Handler]
#6  0x00007f830ea5a755 in raise () at /usr/lib/libc.so.6
#7  0x00007f830ea45851 in abort () at /usr/lib/libc.so.6
#8  0x00007f830ec9481f in __gnu_cxx::__verbose_terminate_handler() () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#9  0x00007f830eca130a in __cxxabiv1::__terminate(void (*)()) (handler=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:47
#10 0x00007f830eca1367 in std::terminate() () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:57
#11 0x00007f830eca15bd in __cxxabiv1::__cxa_throw(void*, std::type_info*, void (*)(void*)) (obj=<optimized out>, tinfo=0x7f830edd94a0 <typeinfo for std::runtime_error>, dest=0x7f830ecb77e0 <std::runtime_error::~runtime_error()>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:95
#12 0x00005564c147dfef in x2struct::JsonReader::child(char const*, x2struct::JsonReader*) ()
#13 0x00005564c14a3f4f in void Qv2ray::V2ConfigModels::TransferSettingObjects::TCPObject::__x_to_struct<x2struct::JsonReader>(x2struct::JsonReader&) ()
#14 0x00005564c14a5232 in void Qv2ray::V2ConfigModels::StreamSettingsObject::__x_to_struct<x2struct::JsonReader>(x2struct::JsonReader&) ()
#15 0x00005564c14a62bd in Qv2ray::V2ConfigModels::StreamSettingsObject Qv2ray::Utils::StructFromJSONString<Qv2ray::V2ConfigModels::StreamSettingsObject>(QString const&) ()
#16 0x00005564c1495337 in ConnectionEditWindow::ConnectionEditWindow(QJsonObject, QString, QWidget*) ()
#17 0x00005564c1485899 in MainWindow::on_editConfigButton_clicked() ()
#18 0x00005564c14ba911 in MainWindow::qt_metacall(QMetaObject::Call, int, void**) ()
#19 0x00007f830f0c3acd in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#20 0x00007f830fd01663 in QAbstractButton::clicked(bool) () at /usr/lib/libQt5Widgets.so.5
#21 0x00007f830fd0188c in  () at /usr/lib/libQt5Widgets.so.5
#22 0x00007f830fd02c92 in  () at /usr/lib/libQt5Widgets.so.5
#23 0x00007f830fd02e56 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/libQt5Widgets.so.5
#24 0x00007f830fdf7ceb in QToolButton::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/libQt5Widgets.so.5
#25 0x00007f830fc4bcb6 in QWidget::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#26 0x00007f830fdf7d95 in QToolButton::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#27 0x00007f830fc084d5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#28 0x00007f830fc11c6c in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#29 0x00007f830f0979c2 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#30 0x00007f830fc10d4b in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /usr/lib/libQt5Widgets.so.5
#31 0x00007f830fc68211 in  () at /usr/lib/libQt5Widgets.so.5
#32 0x00007f830fc6b154 in  () at /usr/lib/libQt5Widgets.so.5
#33 0x00007f830fc084d5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#34 0x00007f830fc11a21 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#35 0x00007f830f0979c2 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#36 0x00007f830f5ee789 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/libQt5Gui.so.5
#37 0x00007f830f5f005b in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/libQt5Gui.so.5
#38 0x00007f830f5c837c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Gui.so.5
#39 0x00007f830b0abfec in  () at /usr/lib/libQt5XcbQpa.so.5
#40 0x00007f830da26cf4 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#41 0x00007f830da28b11 in  () at /usr/lib/libglib-2.0.so.0
#42 0x00007f830da28b51 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#43 0x00007f830f0ef9a3 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#44 0x00007f830f0965ec in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#45 0x00007f830f09e326 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#46 0x00005564c14649ce in main ()
[Inferior 1 (process 2913) detached]

**Comment by lhy0403** [comment]
？

**Comment by lhy0403** [comment]
So, what actually happened here?
