### ISSUE TITLE
Linux版，建议用linuxdeployqt打包依赖库

### ISSUE THREAD

**Issue by nescirem** [lhy0403/Qv2ray#28]
系统：Debian9 （未安装QT5）

缺少运行时库Libqt5core.so.5，而完整安装Qt5耗费成本高。

另外，如果可以的话，能请您以完整的.deb包或.rpm包释出Linux版release吗？😄

**Comment by lhy0403** [comment]
个人使用的是 ArchLinux 不知道 AppImage 可不可以接受？
deb 或 rpm 是个好想法

**Comment by nescirem** [comment]
看起来 AppImage 非常强大，以前我只知道 Docker ！

如果能够直接针对各个平台的包管理器进行打包当然更好不过啦，但是这样可能会浪费您比较多的时间（＞人＜；）

如果您在项目上加上"Sponsorships"的话我是很乐意赞助您一杯咖啡的~

**Comment by aliyuchang33** [comment]
aur我打了一个，其他发行版我觉得appimage就行了

**Comment by lhy0403** [comment]
最新版本的 v1.3.5 包含了打包好的 AppImage，内置 Qt 库，可以下载运行
（目前处于初期阶段如有bug请反馈❤️谢谢）

**Comment by lhy0403** [comment]
SORRY 这个最新版本有一个影响使用的 bug……

**Comment by lhy0403** [comment]
你可以试一下最新的 v1.3.5.2 版本， https://github.com/lhy0403/Qv2ray/releases/tag/v1.3.5.2

**Comment by NoOne-hub** [comment]
> 系统：Debian9 （未安装QT5）
> 
> 缺少运行时库Libqt5core.so.5，而完整安装Qt5耗费成本高。
> 
> 另外，如果可以的话，能请您以完整的.deb包或.rpm包释出Linux版release吗？

。。。前几天qt就是太大了不想安装，自己写了个
https://github.com/NoOne-hub/v2ray_client

**Comment by lhy0403** [comment]
至少现在有了  AppImage 的release版本，有没有可以帮忙测试一下的？

**Comment by NoOne-hub** [comment]
> 至少现在有了 AppImage 的release版本，有没有可以帮忙测试一下的？

很抱歉
└──╼ $./Qv2ray-v1.3.5.2-Linux.AppImage 
./Qv2ray-v1.3.5.2-Linux.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Qv2rayR2Nvya/lib/libQt5Widgets.so.5)
./Qv2ray-v1.3.5.2-Linux.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Qv2rayR2Nvya/lib/libQt5Gui.so.5)
./Qv2ray-v1.3.5.2-Linux.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Qv2rayR2Nvya/lib/libQt5Core.so.5)
./Qv2ray-v1.3.5.2-Linux.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Qv2rayR2Nvya/lib/libharfbuzz.so.0)
./Qv2ray-v1.3.5.2-Linux.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Qv2rayR2Nvya/lib/libicui18n.so.64)
./Qv2ray-v1.3.5.2-Linux.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Qv2rayR2Nvya/lib/libicuuc.so.64)

**Comment by lhy0403** [comment]
看起来是 glibC 的问题

**Comment by lhy0403** [comment]
@NoOne-hub  刚刚上传了一个包含完整  GLIBC 的 AppImage, 如果您有时间的话可以再帮忙测试一下
谢谢
[Qv2ray-5d40c43-x86_64.GLIBC.AppImage.tar.gz](https://github.com/lhy0403/Qv2ray/releases/download/v1.3.5.2/Qv2ray-5d40c43-x86_64.GLIBC.AppImage.tar.gz)

**Comment by NoOne-hub** [comment]
> @NoOne-hub 刚刚上传了一个包含完整 GLIBC 的 AppImage, 如果您有时间的话可以再帮忙测试一下
> 谢谢
> [Qv2ray-5d40c43-x86_64.GLIBC.AppImage.tar.gz](https://github.com/lhy0403/Qv2ray/releases/download/v1.3.5.2/Qv2ray-5d40c43-x86_64.GLIBC.AppImage.tar.gz)

还是不行
./Qv2ray-5d40c43-x86_64.AppImage: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or director

**Comment by lhy0403** [comment]
，，，，，，，我下午再看看

**Comment by nescirem** [comment]
> 至少现在有了 AppImage 的release版本，有没有可以帮忙测试一下的？

这两天在忙项目，可能得等到周末

**Comment by nescirem** [comment]
这是 v1.3.5.2 Qv2ray-v1.3.5.2-Linux.AppImage 的运行结果
```shell
$ ./Qv2ray-v1.3.5.2-Linux.AppImage 
./Qv2ray-v1.3.5.2-Linux.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Qv2ray6Cg0ke/lib/libQt5Widgets.so.5)
./Qv2ray-v1.3.5.2-Linux.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Qv2ray6Cg0ke/lib/libQt5Gui.so.5)
./Qv2ray-v1.3.5.2-Linux.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Qv2ray6Cg0ke/lib/libQt5Core.so.5)
./Qv2ray-v1.3.5.2-Linux.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_Qv2ray6Cg0ke/lib/libQt5Core.so.5)
./Qv2ray-v1.3.5.2-Linux.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_Qv2ray6Cg0ke/lib/libQt5Core.so.5)
./Qv2ray-v1.3.5.2-Linux.AppImage: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /tmp/.mount_Qv2ray6Cg0ke/lib/libpng16.so.16)
./Qv2ray-v1.3.5.2-Linux.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Qv2ray6Cg0ke/lib/libharfbuzz.so.0)
./Qv2ray-v1.3.5.2-Linux.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_Qv2ray6Cg0ke/lib/libcrypto.so.1.1)
./Qv2ray-v1.3.5.2-Linux.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_Qv2ray6Cg0ke/lib/libsystemd.so.0)
./Qv2ray-v1.3.5.2-Linux.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_Qv2ray6Cg0ke/lib/libsystemd.so.0)
./Qv2ray-v1.3.5.2-Linux.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.26' not found (required by /tmp/.mount_Qv2ray6Cg0ke/lib/libsystemd.so.0)
./Qv2ray-v1.3.5.2-Linux.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /tmp/.mount_Qv2ray6Cg0ke/lib/libsystemd.so.0)
./Qv2ray-v1.3.5.2-Linux.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Qv2ray6Cg0ke/lib/libicui18n.so.64)
./Qv2ray-v1.3.5.2-Linux.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Qv2ray6Cg0ke/lib/libicuuc.so.64)
```

这是[Qv2ray-5d40c43-x86_64.GLIBC.AppImage.tar.gz](https://github.com/lhy0403/Qv2ray/releases/download/v1.3.5.2/Qv2ray-5d40c43-x86_64.GLIBC.AppImage.tar.gz) 的运行结果
```shell
$ ./Qv2ray-5d40c43-x86_64.AppImage 
./Qv2ray-5d40c43-x86_64.AppImage: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory
```

**Comment by lhy0403** [comment]
收到，这两天会处理 glibc 的依赖问题

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lhy0403** [comment]
最新版 [Qv2ray-1568386382.003b985-Build49.1.glibc2.14-x86_64.zip](https://github.com/lhy0403/Qv2ray/files/3611027/Qv2ray-1568386382.003b985-Build49.1.glibc2.14-x86_64.zip)

晚上好，各位有没有能帮忙测试一下最新的 AppImage, 
鼓捣了一整天，不知道成果如何
OpenBuildService 项目： https://build.opensuse.org/package/show/home:Leroy_HY/Qv2ray

**Comment by nescirem** [comment]
It Worked! 
> OS: Debian GNU/Linux 9.9 (stretch) x86_64
> Kernel: 4.9.0-9-amd64

**Comment by lhy0403** [comment]
nice

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lhy0403** [comment]
如果有条件的话能不能帮忙测试一下其他的发行版呢？谢谢

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by aliyuchang33** [comment]
jenkins更新了一下，放到ubuntu的5.7.1的qt容器下编译了，应该足够老了

**Comment by aliyuchang33** [comment]
你这语言文件怎么放的

**Comment by lhy0403** [comment]
This issue is should actually be closed as solved. 
Further discussion about translations will be at: #45

**Comment by aliyuchang33** [comment]
对了，你要觉得不方便的话appimage也可以写个脚本我放docker里编译，依赖杠杠的

**Comment by lhy0403** [comment]
https://build.opensuse.org/package/show/home:Leroy_HY/Qv2ray 
想个办法把这个 移植过去，OBS 不支持自动化

**Comment by aliyuchang33** [comment]
我那边应该配置好了，desktop有点问题，你把我的pr并一下

**Comment by aliyuchang33** [comment]
再megre一下，，，

**Comment by lhy0403** [comment]
Please try the development branch !
 I change the building infrastructure on the branch and all the things are different from the master branch.
 Development branch failed to build on the Travis Server, nor the Appveyor.
 I think it needs a higher version of Qt, with some extensions from Qt Linguist required.

**Comment by lhy0403** [comment]
It is building on my machine in but I don’t know why.
Qmake -d gives nothing  valuable

**Comment by aliyuchang33** [comment]
问题是为了保证之后的版本能用，我qt是5.11，其他库应该够老，话说库需要打包么，还是让用户动态链接到新版本库

**Comment by aliyuchang33** [comment]
你指的是appimage么，try build

**Comment by lhy0403** [comment]
现在的问题是主分支可以编译成功
但是开发分支，因为改了编译逻辑，需要在编译的时候自动生成资源文件。
不知道缺哪个mkspec还是版本号的问题。

**Comment by aliyuchang33** [comment]
那我改build哪个，dev普通还是appimage改分支build

**Comment by lhy0403** [comment]
最新开发分支的改动内容是：
build的时候检测翻译文件并自动加载到资源里面。
…………问题是
某些版本的Qt不会自动生成资源文件。

**Comment by aliyuchang33** [comment]
...

**Comment by lhy0403** [comment]
> 那我该build哪个，dev普通还是appimage改分支build

下一个version号，要用现在的dev，所以应该换到dev然后试一下build Appimage。

**Comment by aliyuchang33** [comment]
ok，你推吧，我appimage切到dev

**Comment by lhy0403** [comment]
如果build的时候没能把translation加到资源里面的话，运行的时候会报一条错误。

**Comment by lhy0403** [comment]
> ok，你推吧，我appimage切到dev

我现在这个功能还没实现，不能merge到master啊😂

**Comment by aliyuchang33** [comment]
我觉着其实要考虑的顶多是appimage，其他情况都是开发者编译，开发者应该能自主解决编译问题

**Comment by aliyuchang33** [comment]
我已经切到dev了，要现在build一次么

**Comment by lhy0403** [comment]
更严重的问题macOS Windows 都失败了

**Comment by lhy0403** [comment]
> 我已经切到dev了，要现在build一次么

对现在开发分之里面的东西也是我在我电脑上可以编译的，
得想办法找个方法让他能build出Appimage。

**Comment by aliyuchang33** [comment]
哔了犬科动物了，网络不行

**Comment by lhy0403** [comment]
qq
