### ISSUE TITLE
为嘛我的 manjaro 里是 1.3.4-1 的版本？

### ISSUE THREAD

**Issue by haw-haw** [lhy0403/Qv2ray#32]
而这里最新的才到 1.3.2

**Comment by lhy0403** [comment]
呃，，这是这两天的一个打包问题，已经和AUR作者联系了 @aliyuchang33 
因为目前的分支和文件修改比较复杂
See #28
本周会统一版本号和 AUR 的规范

**Comment by lhy0403** [comment]
已经同步更新到 v1.3.5

**Comment by haw-haw** [comment]
> Sorry
> 
> 呃，，这是这两天的一个打包问题，已经和AUR作者联系了 @aliyuchang33
> 因为目前的分支和文件修改比较复杂
> See #28
> 本周会统一版本号和 AUR 的规范
> 
> FYI: AUR 当前版本用的是 master 分支的最新文件，比 release 中的要新一点点 （修复了一个小的列表问题）

厉害！
：）
