### ISSUE TITLE
Help pls. Error Make

### ISSUE THREAD

**Issue by thebadgateway** [lhy0403/Qv2ray#33]
Help me figure out why the error.

```
sony@desktop:~/test/Qv2ray/build$ qmake ../
sony@desktop:~/test/Qv2ray/build$ make
g++ -m64 -Wl,-O1 -o Qv2ray     -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
Makefile:102: recipe for target 'Qv2ray' failed
make: *** [Qv2ray] Error 1
sony@desktop:~/test/Qv2ray/build$ 
```

**Comment by lhy0403** [comment]
Can you please attach the full output of `make` and `ls --recursive`? 
It should not produce any error unless this is a Qt issue.

BTW can you show me the version of your:
- GCC version by using `g++ --version` 
- make version by using `make --version`
- QMake version by using `qmake --version`

Are you cloning the `master` branch?

**Comment by thebadgateway** [comment]
> Can you please attach the full output of `make` and `ls --recursive`?
> It should not produce any error unless this is a Qt issue.
> 
> BTW can you show me the version of your:
> 
> * GCC version by using `g++ --version`
> * make version by using `make --version`
> * QMake version by using `qmake --version`
> 
> Are you cloning the `master` branch?

```
sony@sony-desktop:~/test/Qv2ray/build$ ls --recursive
.:
Makefile
sony@desktop:~/test/Qv2ray/build$ g++ --version
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

sony@desktop:~/test/Qv2ray/build$ make --version
GNU Make 4.1
Copyright (C) 1988-2014 Free Software Foundation, Inc.
sony@desktop:~/test/Qv2ray/build$ qmake --version
QMake version 2.01a
Using Qt version 4.8.7 in /usr/lib/x86_64-linux-gnu
sony@desktop:~/test/Qv2ray/build$ 
sony@desktop:~/test/Qv2ray/build$ cd ..
sony@desktop:~/test/Qv2ray$ ls
3rdparty  build  _config.yml  docs  icons  ignored_cpp_structs.hpp  libs  LICENSE  Makefile  Qv2ray.pro  README.md  resources.qrc  src  translations

```

**Comment by lhy0403** [comment]
> Using Qt version 4.8.7 in /usr/lib/x86_64-linux-gnu
Unfortunately, Qt4 is not supported, Sorry about the inconvenience. Qv2ray is using Qt5.

**Comment by thebadgateway** [comment]
```
sony@desktop:~/test/Qv2ray/build$ qmake --version
QMake version 3.1
Using Qt version 5.9.5 in /usr/lib/x86_64-linux-gnu
sony@desktop:~/test/Qv2ray/build$ make
g++ -Wl,-O1 -o Qv2ray    -lQt5Gui -lQt5Core -lGL -lpthread 
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
Makefile:137: recipe for target 'Qv2ray' failed
make: *** [Qv2ray] Error 1
```
Please tell me what I'm doing wrong.

**Comment by lhy0403** [comment]
Well, it’s recommended that you read the docs at https://lhy0403.gighub.io/Qv2ray

**Comment by lhy0403** [comment]
Download the released core files from the v2ray repo. Then set core file path in the Preferences window.

**Comment by thebadgateway** [comment]
> Well, it’s recommended that you read the docs at https://lhy0403.github.io/Qv2ray

Thank. The application is working. Annoyingly you can’t add node with vmess links.
Make detailed readme instructions for stupid ones like me)

**Comment by lhy0403** [comment]
Well there actrually is.... Try "Import" connection please. 
The docs will be updated soon.

**Comment by lhy0403** [comment]
As the problem is solved, is issue will be closed.
