### ISSUE TITLE
config.gen.json中inbounds一直为空数组

### ISSUE THREAD

**Issue by scolia** [lhy0403/Qv2ray#36]
如题, 无论在首选项中如果修改入站设置, 生成的inbounds中一直都为空数组

**Comment by lhy0403** [comment]
请确认你是不是使用的  v1.3.5 ( 首选项 > 关于 ) 
如果是，请更新到 v1.3.5.2

**Comment by lhy0403** [comment]
FYI: 参考昨天 (2019-09-03) 的错误 v1.3.5 版本 https://github.com/lhy0403/Qv2ray/releases/tag/v1.3.5
Issue: #35

**Comment by scolia** [comment]
这是基于当前master分支编译的, 另外, 提供的release包中, 第三方库目录为空, 无法进行编译

**Comment by lhy0403** [comment]
master 分支现已更新，试试现在的 1.3.5.2 可不可以正常build

**Comment by scolia** [comment]
已可以使用

**Comment by lhy0403** [comment]
Close as solved, sorry about the inconvenience and the bug yesterday.
