### ISSUE TITLE
[2.0] Please add the field "Name" 

### ISSUE THREAD

**Issue by lhy0403** [lhy0403/Qv2ray#37]
Please add the field "Name" [PIC](https://pixs.ru/images/2019/09/04/Desktop.png)

_Originally posted by @thebadgateway in https://github.com/lhy0403/Qv2ray/issues/34#issuecomment-527854901_

**Comment by thebadgateway** [comment]
What do you think about it? [PIC](https://pixs.ru/images/2019/09/04/Desktop1.png)

**Comment by lhy0403** [comment]
> What do you think about it? PIC

Well this may bring some ambiguity that there are multiple outbounds in a connection config, in this case the table layout will not be very convinent to display the data.
Oppositely, I prefer the current UI scheme. Which will allow us to set a short description of the selected config.
However I still agree with you that a `Name` field shold be added to the "Connection Editor" popup.

**Comment by lhy0403** [comment]
This commit https://github.com/lhy0403/Qv2ray/commit/348f928acd5a392a2cdb15a867b6aa73515716ba added the suggested text for storing aliases, but the functionality is not ready yet.
This comment here is just for a reference.

**Comment by lhy0403** [comment]
Changes have been made to the new outbound editor UI, when manually adding a connection, alias (the name of the connection) will be generated from the `tag` field, or from the `host` and `port` if the tag is empty.
However, editing an existing connection will not change the `alias` of it because `Tag` and `name of the connection` are two different things.

**Comment by lhy0403** [comment]
Well actually, renaming a connection can only be done in the Main Window because the Outbound Editor is re-used by the Route Editor, thus the main propose of the Outbound Editor is simply edit an outbound. Not to change the name of a connection..

**Comment by lhy0403** [comment]
As this feature has been implemented, this issue will be closed, 
Thanks a lot for your contributions !
