### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by lhy0403** [lhy0403/Qv2ray#45]
在线翻译平台：Crowdin

**Comment by lhy0403** [comment]
最新这个 build 全平台挂了……

**Comment by aliyuchang33** [comment]
你看看我的编译，打包出来就一个Qv2ray，我没弄其他翻译文件，但是直接改语言不能用

**Comment by lhy0403** [comment]
最新dev编译出来就是这样，正在处理跟 Crowdin 的集成

**Comment by aliyuchang33** [comment]
你慢慢搞

**Comment by lhy0403** [comment]
最新的一个build把全平台都搞炸了……

**Comment by lhy0403** [comment]
The latest commit on `dev` branch could be the next release, there's a logic fix on selecting connection and logo update.
Please try to fix the OpenSSL error ASAP

**Comment by aliyuchang33** [comment]
我不知道你改了啥，但是现在能用了

**Comment by aliyuchang33** [comment]
可以吧AppImage的位置也写上了

**Comment by lhy0403** [comment]
现在就再等 #51 的 CI, Merge 进去以后你看看你的 AppImage 能不能工作，
如果可以的话我会版本号更到 1.3.6 然后 merge 到 master

**Comment by lhy0403** [comment]
那你就 dev 和 master 每次都build好了

**Comment by aliyuchang33** [comment]
过一会来几个conflict

**Comment by lhy0403** [comment]
👋 不会的😂

**Comment by aliyuchang33** [comment]
能用是能用，但是为啥我这边每次都构建了两次，，

**Comment by lhy0403** [comment]
我刚刚同时推了一个 commit

**Comment by aliyuchang33** [comment]
ok

**Comment by aliyuchang33** [comment]
我AppImage回master?

**Comment by lhy0403** [comment]
都build吧，master是用来release的，dev就给测试吧

**Comment by aliyuchang33** [comment]
想起一个问题，现在是放在opt，但是aur的话，放opt检测不到.desktop啊

**Comment by lhy0403** [comment]
在你AUR里面cp一下不就好了

**Comment by lhy0403** [comment]
在你AUR里面cp一下不就好了

**Comment by aliyuchang33** [comment]
太沙雕了，还有master的几个文件merge一下，不然这边百分百failed

**Comment by lhy0403** [comment]
https://github.com/SoneWinstone
PLEASE CHECK HIS/HER NAME @aliyuchang33

**Comment by aliyuchang33** [comment]
日了犬科动物了，他id有毒，你rebase一下？

**Comment by lhy0403** [comment]
…… git reset HEAD^1  done

**Comment by lhy0403** [comment]
Is you AppImage build finished ?

**Comment by aliyuchang33** [comment]
yep

**Comment by lhy0403** [comment]
Merging
