### ISSUE TITLE
已从文件导入配置但不能使用

### ISSUE THREAD

**Issue by aliyuchang33** [lhy0403/Qv2ray#57]
![图片](https://user-images.githubusercontent.com/22322294/65144689-6943d900-da4a-11e9-834f-87cf05fbc837.png)

**Comment by lhy0403** [comment]
这个是主窗口的点击逻辑问题，，，，，，
大概会跟着 v2.0 前的最后一个版本一起修复

**Comment by lhy0403** [comment]
临时解决方案是右键连接

**Comment by lhy0403** [comment]
```

 --> getcap ./v2ray

 --> ./v2ray                                      
V2Ray 4.20.0 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
main: failed to load config:  > v2ray.com/core/main/confloader/external: config file not readable > open : no such file or directory

 --> sudo setcap CAP_NET_ADMIN,CAP_NET_RAW,CAP_NET_BIND_SERVICE=eip ./v2ray

 --> getcap ./v2ray
./v2ray = cap_net_bind_service,cap_net_admin,cap_net_raw+eip

 --> ./v2ray                                      
[1]    75971 segmentation fault  ./v2ray
```

**Comment by lhy0403** [comment]
Things become strange after running `setcap` on the v2ray core file. @aliyuchang33

**Comment by lhy0403** [comment]
Running `sudo ./v2ray` after setcap fixed this issue, it seems to be a kernal limit.

**Comment by aliyuchang33** [comment]
你的Arch是假的，盗版Arch

**Comment by aliyuchang33** [comment]
不要raw试试

**Comment by aliyuchang33** [comment]
Definitely runs well on both my laptop and server.

**Comment by lhy0403** [comment]
你的文件权限和内核参数呢？

**Comment by aliyuchang33** [comment]
```
-r-xr-xr-x 1 hork users  21M  7月 15 12:01 v2ray

╰─$ getcap v2ray
v2ray = cap_net_bind_service,cap_net_admin+eip

无特殊内核参数
```

**Comment by lhy0403** [comment]
The application with `setcap` can only run with `sudo`.
However normal user failed to launch it.

**Comment by lhy0403** [comment]
But for sudo-ed application, it becomes useless to set a capability for it.

**Comment by aliyuchang33** [comment]
Your arch is fake. Try a vm, should works fine.

**Comment by lhy0403** [comment]
You may setup a vm and try.
If a feature is not working for everyone, then drop.

**Comment by aliyuchang33** [comment]
I confirmed on two devices, its your computer's fault.

**Comment by lhy0403** [comment]
Then just suggest a solution to solve this.

**Comment by aliyuchang33** [comment]
Confirming on my opensuse vm, just wait.

**Comment by lhy0403** [comment]
OK, if it's working, I'll commit a patch, oppositely, I'll use `sudo`.

**Comment by aliyuchang33** [comment]
sudo sucks

**Comment by lhy0403** [comment]
Please also check, by the way, if `pkexec` is available on every platform.

**Comment by aliyuchang33** [comment]
```
╭─hork@openSUSE ~/v2ray  
╰─$ sudo getcap v2ray                                                             127 ↵
v2ray = cap_net_bind_service,cap_net_admin,cap_net_raw+eip
╭─hork@openSUSE ~/v2ray  
╰─$ ls
conf         config.json.example  geosite.dat  Hv2ray       Qv2ray  v2ctl
config.json  geoip.dat            Himeki.ico   __pycache__  utils   v2ray
╭─hork@openSUSE ~/v2ray  
╰─$ ./v2ray 
V2Ray 4.20.0 (V2Fly, a community-driven edition of V2Ray.) Custom
A unified platform for anti-censorship.
2019/09/19 19:06:45 [Warning] v2ray.com/core: V2Ray 4.20.0 started

```

**Comment by aliyuchang33** [comment]
works on opensuse

**Comment by lhy0403** [comment]
OK, I'll use `setcap` then

**Comment by aliyuchang33** [comment]
Your system have too many shoes.

**Comment by lhy0403** [comment]
Can you please add another Jenkins building service on the `version-v1` branch?
All bug fixes will be on this branch before Qv2.0 is released.

**Comment by aliyuchang33** [comment]
k

**Comment by aliyuchang33** [comment]
Jenkins挂了，frp过不去，得等到unblock，你先自己编译吧

**Comment by lhy0403** [comment]
那你把编译环境给我啊，，我这里没有环境

**Comment by aliyuchang33** [comment]
就等着吧，这段时间也没人用这客户端的

**Comment by lhy0403** [comment]
The in-progress version of v1.3.7 has just fixed this bug, and I need an AppImage Build server.

**Comment by lhy0403** [comment]
I'll use openbuildservice then,

**Comment by aliyuchang33** [comment]
https://jenkins.himeki.net/job/Qv2ray-AppImage-version-v1/

**Comment by aliyuchang33** [comment]
昨天服务器崩了，不是网崩了

**Comment by aliyuchang33** [comment]
https://jenkins.himeki.net/job/Qv2ray-AppImage-version-v1/badge/icon
你可以给编译加badge了

**Comment by lhy0403** [comment]
在 v1.3.7.1 版本中修复了这个问题，请查看 release
