### ISSUE TITLE
添加导入vemss字符串,点OK后奔溃

### ISSUE THREAD

**Issue by juvevood** [lhy0403/Qv2ray#58]
希望下个2.0版本修复. 目前只能手动添加的节点

**Comment by lhy0403** [comment]
好的

**Comment by aliyuchang33** [comment]
请详细描述相关情况，包括使用版本，操作系统以及使用的字符串以进行调试

**Comment by juvevood** [comment]
@aliyuchang33 
系统:archlinux
版本:1.3.6.1
奔溃日志如下:
`
[NETWORK]: Current OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
QMetaObject::connectSlotsByName: No matching signal for on_pushButton_clicked()
[VCORE]: Connecting to: 03.static.hk.qianglie.xyz_543
[NETWORK]: Network request errcode: 0
[UPDATE]: Received update info, Latest: 1.3.6.1 Current: 1.3.6.1 Ignored: 
terminate called after throwing an instance of 'std::runtime_error'
  what():  IsString()[v]
[1]    18895 abort (core dumped)  /opt/Qv2ray/bin/Qv2ray
`

**Comment by lhy0403** [comment]
收到，已经定位问题所在

**Comment by lhy0403** [comment]
你好，可以提供以下你的 vmess 字符串格式吗？
是一下哪种类型？
1. `vmess://base64`
2. 纯 base64

**Comment by juvevood** [comment]
> 你好，可以提供以下你的 vmess 字符串格式吗？
> 是一下哪种类型？
> 
> 1. `vmess://base64`
> 2. 纯 base64

第一种

**Comment by lhy0403** [comment]
即将发布的 v1.3.7 包含了这个 bug 修复，大概会在一到两天内发布

**Comment by lhy0403** [comment]
在 v1.3.7.1 版本中修复了这个问题，请查看 release
