### ISSUE TITLE
Segmentation Fault occured after calling setcap to v2ray

### ISSUE THREAD

**Issue by lhy0403** [lhy0403/Qv2ray#59]
```
getcap ./v2ray
----> (no output)

./v2ray                                      
----> V2Ray 4.20.0 (V2Fly, a community-driven edition of V2Ray.) Custom
----> A unified platform for anti-censorship......
----> (blablablabla.............)

sudo setcap CAP_NET_ADMIN,CAP_NET_RAW,CAP_NET_BIND_SERVICE=eip ./v2ray

getcap ./v2ray
----> ./v2ray = cap_net_bind_service,cap_net_admin,cap_net_raw+eip

./v2ray                                      
----> [1]    75971 segmentation fault  ./v2ray
```

_Originally posted by @lhy0403 in https://github.com/lhy0403/Qv2ray/issues/57#issuecomment-533037971_

**Comment by lhy0403** [comment]
解决方案： 
```
sudo sysctl fs.suid_dumpable=1
```

**Comment by lhy0403** [comment]
For future refrence: https://github.com/yggdrasil-network/yggdrasil-go/issues/403#issuecomment-480363616

**Comment by aliyuchang33** [comment]
Write this into doc.

**Comment by lhy0403** [comment]
> After a short talk on IRC, we came to this conclusion:
> 
> This is caused by `vsyscall=none` being passed to the kernel command line, and the go runtime relying on the legacy vsyscall table being present.
> 
> The go runtime is attempting to call `gettimeofday()` using the vdso page.
> 
> ```
> 278  LEAQ 0(SP), DI
> 279  MOVQ $0, SI
> 280  MOVQ runtime·vdsoGettimeofdaySym(SB), AX
> 281  CALL AX
> 282  MOVQ 0(SP), AX // sec
> ```
> 
> However, since the legacy vsyscall table is disabled in the kernel, this ends up failing and causing a segfault.
> 
> ```
> [559159.574164] yggdrasil[1562] vsyscall attempted with vsyscall=none ip:ffffffffff600000 cs:33 sp:7ffd6f0c3e78 ax:ffffffffff600000 si:0 di:7ffd6f0c3e80
> [559159.574174] yggdrasil[1562]: segfault at ffffffffff600000 ip ffffffffff600000 sp 00007ffd6f0c3e78 error 15
> [559159.574178] Code: Bad RIP value.
> ```
> 
> Modern programs shouldn't rely on the vsyscall table being present and should link to linux-vdso.so.1
> 
> Edit:
> The normal output of `ldd yggdrasil`should be something like this
> 
> ```
> linux-vdso.so.1 (0x00007ffc3eeef000)   //this should be present 
> ibpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f5df3a01000)
> libc.so.6 => /usr/lib/libc.so.6 (0x00007f5df383d000)
> /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f5df3fd8000)
> ```

Error analyzed from: https://github.com/yggdrasil-network/yggdrasil-go/issues/403#issuecomment-480381167
