### ISSUE TITLE
Ubuntu 14.04 无法启动

### ISSUE THREAD

**Issue by wesley0314** [lhy0403/Qv2ray#60]
**简单描述这个 bug：**
给予运行权限后双击无反应，使用命令行启动报错：
`version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference`

**相关截图**
![image](https://user-images.githubusercontent.com/6896949/65369952-3f76f600-dc86-11e9-9366-a2bdfcb6e1ac.png)

**系统信息**
 - 系统类型（windows, linux, macos）：Ubuntu 14.04
 - 是从release下载的还是自己编译的：release下载
 - 首选项里的版本号：1.3.6.1

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

**Comment by lhy0403** [comment]
Possible solution, but it may not working: https://github.com/typora/typora-issues/issues/504
大概是 glibc 的依赖问题 see: https://stackoverflow.com/q/36816570
你可以尝试升级系统（你当然不想😂）
下个版本可能会针对旧版系统进行兼容

如果着急的话，临时解决方案是手动安装qt并自己编译

**Comment by lhy0403** [comment]
Can you add another AppImgae env for building old versions of GLIBC? @aliyuchang33 
By adding this macro into the .pro file:
`-D_GLIBCXX_USE_CXX11_ABI=0`

**Comment by aliyuchang33** [comment]
14.04都不支持了，，，linuxdeployqt那边都建议是16.04，你要搞就自己fork个分支，我临时改一下dev apimage的构建

**Comment by lhy0403** [comment]
> 14.04都不支持了，，，linuxdeployqt那边都建议是16.04，你要搞就自己fork个分支，我临时改一下dev apimage的构建

@wesley0314 对不起我们无法为 Ubuntu 14 提供支持。
Ubuntu 14.04 已经在 2019 年 4月 停止标准支持
https://askubuntu.com/a/505894/914401
建议升级到更新版本的 Ubuntu 16

**Comment by Qv2ray-dev** [comment]
时隔半年，这个问题终于被修复
