### ISSUE TITLE
不支持 srtp 混淆？

### ISSUE THREAD

**Issue by xflcx1991** [lhy0403/Qv2ray#63]
**简单描述这个 bug：**
导入 VMess 字符串，连接时报错，最后几句错误提示
”unknown config id: srtp“
\> exit status 255
**如何复现这个bug：**
1. 导入连接
2. 导入源选择 VMess 字符串
3. 选中刚导入的主机，点击连接就会出现报错提示

**Qv2ray 本应该是怎样工作的？**
本应该正常工作提供 socks 代理

**相关截图**
如果合适的话，可以在这里粘贴截图
![image](https://user-images.githubusercontent.com/3775351/65383098-80344500-dd42-11e9-8d14-b60acb1b3b6c.png)

**系统信息**
 - 系统类型（windows, linux, macos）：
Ubuntu 16.04.6
 - 是从release下载的还是自己编译的：
release
 - 首选项里的版本号：
1.3.6.1
**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

**Comment by lhy0403** [comment]
这个问题我在昨天换vpn的时候也发现了，将会处理

**Comment by lhy0403** [comment]
Version v1 分支里的最新版大概是修复了这个 bug, 你可以在 这里 https://jenkins.himeki.net/job/Qv2ray-AppImage-version-v1/4/ 下载 AppImage 测试一下

**Comment by xflcx1991** [comment]
@lhy0403 好了，:smile:。不过直接打开新版本就有就有原有配置了，直接连接还是报错，重新导入一遍字符串就好了。

**Comment by lhy0403** [comment]
嗯好的，这个确实需要重新导入一下

**Comment by lhy0403** [comment]
This issue will be marked as solved.
