### ISSUE TITLE
国内ip分流似乎不完整，有部分国内ip走了代理

### ISSUE THREAD

**Issue by huyizheng** [lhy0403/Qv2ray#64]
**简单描述这个 bug：**
国内ip分流似乎不完整，有部分国内ip走了代理。
比如www.inspur.com，我在终端里ping它或tcping它的80端口，解析出来的都是222.28.152.178这个ip，这个ip属于国内ip。
但软件日志里显示访问这个网站时走了代理。

**如何复现这个bug：**
1. 开启代理，不要勾选“为国内地址启用代理”
2. 访问www.inspur.com，查看日志
3. 访问www.baidu.com，查看日志

**Qv2ray 本应该是怎样工作的？**

**相关截图**

$ ping www.inspur.com
PING www.inspur.com.wscdns.com (222.28.152.178) 56(84) bytes of data.
64 bytes from 222.28.152.178 (222.28.152.178): icmp_seq=1 ttl=54 time=1.32 ms
64 bytes from 222.28.152.178 (222.28.152.178): icmp_seq=2 ttl=54 time=1.67 ms

$ tcping www.inspur.com 80
Ping tcp://www.inspur.com:80(222.28.152.178:80) - Connected - time=6.833239ms
Ping tcp://www.inspur.com:80(222.28.152.178:80) - Connected - time=3.888434ms

软件日志节选
2019/09/22 15:34:12 [Info] [143033988] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.inspur.com:80
2019/09/22 15:34:12 tcp:127.0.0.1:50294 accepted tcp:www.inspur.com:80 
2019/09/22 15:34:12 [Info] [143033988] v2ray.com/core/app/dispatcher: taking detour [outBound_PROXY] for [tcp:www.inspur.com:80]
……
2019/09/22 15:46:19 [Info] [1434805457] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.baidu.com:443
2019/09/22 15:46:19 [Info] [1434805457] v2ray.com/core/app/dispatcher: taking detour [outBound_DIRECT] for [tcp:www.baidu.com:443]
2019/09/22 15:46:19 [Info] [1434805457] v2ray.com/core/proxy/freedom: opening connection to tcp:www.baidu.com:443

**系统信息**
 - 系统类型（windows, linux, macos）：Archlinux，源里v2ray相关的包都装了。
 - 是从release下载的还是自己编译的：自己编译的
 - 首选项里的版本号：1.3.7.0

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

**Comment by lhy0403** [comment]
sorry 这个问题可能不在 Qv2ray 的管辖范围内，Qv2ray 当前只是使用 GUI 生成 config, 其他路由相关操作在 v2ray 执行。
这可能是一个来自于 [domain-list-community](https://github.com/v2ray/domain-list-community) 或 [GeoIP](https://github.com/v2ray/geoip) 的 Bug

**Comment by lhy0403** [comment]
您可以尝试使用其他的 v2ray 客户端进行测试，如果确定是 Qv2ray 的问题，欢迎您继续汇报这个bug
Issue 在五天之内不会关闭

**Comment by huyizheng** [comment]
我又测试了一下，发现用systemctl start v2ray.service启动的v2ray是可以正确分流www.inspur.com这个地址的。
我的/etc/v2ray/config.json如下：
{
  "log": {
    "access": "xxxxxx/v2ray.log",
    "error": "xxxxxx/v2ray.err",
    "loglevel": "debug"
  },
  "inbounds": [{
    "port": 1081,  // SOCKS 代理端口，在浏览器中需配置代理并指向这个端口
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "udp": true
    }
  }],
  "outbounds": [{
    "protocol": "vmess",
    "tag": "proxy",
    "settings": {
      "vnext": [{
        "address": "xxxxxx", // 服务器地址，请修改为你自己的服务器 ip 或域名
        "port": xxx,  // 服务器端口
        "users": [{
             "alterId": x,
              "id": "xxxxxxxx"
         }]
      }]
    }
  },{
    "protocol": "freedom",
    "tag": "direct",
    "settings": {}
  }],
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [{
      "type": "field",
      "ip": ["geoip:private"],
      "outboundTag": "direct"
    },{
      "type": "field",
      "ip": ["geoip:cn"],
      "outboundTag": "direct"
    },{
      "type": "field",
      "domain": ["geosite:cn"],
      "outboundTag": "direct"
    }]
  }
}
之后使用systemctl start v2ray.service。
访问www.inspur.com走的是直连，日志记录：
2019/09/22 16:37:55 [Info] [2585534190] v2ray.com/core/proxy/socks: TCP Connect request to tcp:www.inspur.com:80
2019/09/22 16:37:55 [Info] [2585534190] v2ray.com/core/app/dispatcher: taking detour [direct] for [tcp:www.inspur.com:80]
2019/09/22 16:37:55 [Info] [2585534190] v2ray.com/core/proxy/freedom: opening connection to tcp:www.inspur.com:80
2019/09/22 16:37:55 [Info] [2585534190] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:www.inspur.com:80
我的浏览器是firefox，用switchyomega插件使用socks5代理。

**Comment by lhy0403** [comment]
因为要上学，，我可能会晚两到三天修复

**Comment by huyizheng** [comment]
我又测试了一下，似乎发现问题所在了。
Qv2ray在$HOME/.qv2ray/generated里自动生成的配置文件里的路由策略里最后有这样一段：
{
                "domain": [
                    "regexp:.*"
                ],
                "outboundTag": "outBound_PROXY",
                "type": "field"
            }
我不是很清楚这一段的含义，但是我发现如果我把这一段加到我的/etc/v2ray/config.json里，那么systemctl start v2ray.service启动的v2ray的行为就和Qv2ray一样了，www.inspur.com走了代理。

**Comment by lhy0403** [comment]
我刚刚也在测试，确实是这一行的问题

**Comment by lhy0403** [comment]
不过值得注意的是，配置文件顶部的 DNS array 也对 route 的决策有影响，因为外国 DNS 解析出来的 IP 就是 www.inspur.com 的外国站，国内 DNS 解析是中国站，两者  IP 不一样引发了以上问题
我认为 DNS 是更根本的问题

**Comment by lhy0403** [comment]
> 我又测试了一下，似乎发现问题所在了。
> Qv2ray在$HOME/.qv2ray/generated里自动生成的配置文件里的路由策略里最后有这样一段：
> `{`
> ` "domain": [`
> ` "regexp:.*"`
> ` ],`
> ` "outboundTag": "outBound_PROXY",`
> ` "type": "field"`
> ` }`
> 我发现如果我把这一段加到我的/etc/v2ray/config.json里，那么systemctl start v2ray.service启动的v2ray的行为就和Qv2ray一样了，www.inspur.com走了代理。

最终确定的解决方案是去掉这一项

**Comment by lhy0403** [comment]
Thanks For Your Contribution.
