### ISSUE TITLE
[2.0] 希望 Vmess 链接导入可以支持多行

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#72]
1. 希望可以在 Vmess 链接导入页面支持同时导入多行
2. 若导入时某个链接 parse 出错，希望可以在日志中报警告并跳过该链接

**Comment by lhy0403** [comment]
你好，这个建议可以在v2.0 中实现，可以在 #69 下面留言一下吗？

**Comment by lhy0403** [comment]
？？对不起我啥时候关的这个 issue

**Comment by lhy0403** [comment]
This issue will be closed as done.
