### ISSUE TITLE
主机列表为空时删除按钮仍可用

### ISSUE THREAD

**Issue by DuckSoft** [lhy0403/Qv2ray#76]
**简单描述这个 bug：**
主机列表为空时，删除按钮仍然可用，甚至还问你要不要删除。

**如何复现这个bug：**
1. 空主机列表
2. 点删除按钮
3. 出 bug 了

**Qv2ray 本应该是怎样工作的？**
空列表时不要启用删除按钮。

**相关截图或日志**
![图片](https://user-images.githubusercontent.com/7822648/65567271-2f159280-df88-11e9-837e-9ba22ced0fe7.png)

**Comment by lhy0403** [comment]
Will fix in v1.3.7.2
