### ISSUE TITLE
深度系统-appimage

### ISSUE THREAD

**Issue by lookforkivi** [lhy0403/Qv2ray#79]
**简单描述这个 bug：**
./Qv2ray-v1.3.7.1-linux.AppImage
![深度截图_选择区域_20190926093423](https://user-images.githubusercontent.com/46741463/65651647-a1967900-e041-11e9-89df-ca44e437c199.png)

**如何复现这个bug：**
1. 
2. 
3. 
4. 

**Qv2ray 本应该是怎样工作的？**

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 

**相关截图或日志**

```
日志：

```

**系统信息**
 - 系统类型（windows, linux, macos）
    - 
 - 是从release下载的还是自己编译的
    - 
 - 首选项里的版本号：
    - 

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

-

**Comment by aliyuchang33** [comment]
somebody help him

**Comment by lhy0403** [comment]
你好，请先阅读一下 document : https://lhy0403.github.io/Qv2ray/FirstTime/Windows-macOS.html

**Comment by DuckSoft** [comment]
这不是 bug。我按照文档做了一次之后，没有问题。

**Comment by lhy0403** [comment]
This is a non-bug issue and will be closed after 3 days if it's not active.

**Comment by lookforkivi** [comment]
可以了，感谢！

**Comment by lhy0403** [comment]
好的
