### ISSUE TITLE
添加新的配置之后在编辑为空

### ISSUE THREAD

**Issue by TheWanderingCoel** [lhy0403/Qv2ray#86]
**简单描述这个 bug：**
手动点击加号添加一个服务器,完成之后服务器列表多出来一个为空的一个Host。点击编辑所有东西都是空的,手动进入``.qv2ray``文件夹发现此配置文件不存在。

**如何复现这个bug：**
1. 点击加号
2. 粘贴Alias, Host, Port, UUID 和 Alter ID
3. 点击OK
4. BUG出现

**Qv2ray 本应该是怎样工作的？**
正常的配置文件，显示为名字并且点编辑有内容

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 

**相关截图或日志**
![Free-Converter com-20190929073016-803356845](https://user-images.githubusercontent.com/39617891/65826786-6dc78780-e2bd-11e9-96c1-9195c9e2d2d7.jpg)
![Free-Converter com-20190929073110-533787845](https://user-images.githubusercontent.com/39617891/65826787-7324d200-e2bd-11e9-85e2-2614b28bcf5d.jpg)

```
日志：

```

**系统信息**
 - 系统类型（windows, linux, macos）
    - Manjaro KDE 18.1
 - 是从release下载的还是自己编译的
    - 自己编译
 - 首选项里的版本号：
    - origin分支最新版

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

-

**Comment by TheWanderingCoel** [comment]
重新编译了下好了,不好意思打扰大佬了

**Comment by lhy0403** [comment]
你在用 dev 版本吗？

**Comment by lhy0403** [comment]
有关 dev 版本的问题欢迎到 #69 里面进行讨论（bug肯定很多 issue 可能会炸）

**Comment by TheWanderingCoel** [comment]
dev 和 origin都是这样, Alias没有用,配置文件写不了。之后在列表右键重命名才行。重编译没有解决，希望大佬能看一下

**Comment by lhy0403** [comment]
我记得 master 分支里面没有 Alias 这个选项的啊，请确认一下你是不是 master 或者 version-v1 分支？

**Comment by lhy0403** [comment]
目测你应该使用的是 `dev` 或者 `version-v2`，是当前正在开发的版本，如果作为日常使用的话建议使用 `version-v1` 或 `master`

**Comment by TheWanderingCoel** [comment]
我看了一下,master的确没有。不好意思记错了,感谢大佬,我切换到master去

**Comment by lhy0403** [comment]
Keep it open till tonight, If nothing goes wrong, I'll close it.

**Comment by lhy0403** [comment]
Ok, now close as solved.
