### ISSUE TITLE
找不到核心文件

### ISSUE THREAD

**Issue by SettingDust** [lhy0403/Qv2ray#87]
**简单描述这个 bug：**
提示 `v2ray 核心文件未能在这里找到：/home/***/.qv2ray/vcore/v2ray`
但是我已经修改了 v2ray asset 路径，却还是在默认路径下寻找，而且安装了也没有如文档所说的默认是 `/bin/v2ray 和 /etc/v2ray `
我尝试过修改路径为 `/bin` `/bin/` `/bin/v2ray`，都无效
/bin/下确实有 v2ray & v2ctl 存在
请问改怎么解决？

**系统信息**
 - 系统类型（windows, linux, macos）
    - Linux
 - 是从release下载的还是自己编译的
    - Arch
 - 首选项里的版本号：
    - 1.3.7.1

**Comment by lhy0403** [comment]
哎呀看起来是 doc 好长时间没更新了，，，，，，，，，
现在需要 `cp /bin/v2ray` 和 `v2ctl` 到 `$HOME/.qv2ray/vcore` 然后首选项 assets 设置成 `/etc/v2ray/`
做出这个更改的原因是需要支持 tProxy 的 `setcap`

**Comment by SettingDust** [comment]
> 哎呀看起来是 doc 好长时间没更新了，，，，，，，，，
> 现在需要 `cp /bin/v2ray` 和 `v2ctl` 到 `$HOME/.qv2ray/vcore` 然后首选项 assets 设置成 `/etc/v2ray/`
> 做出这个更改的原因是需要支持 tProxy 的 `setcap`

我自己发现了，我以为是bug，就报告一下。

**Comment by lhy0403** [comment]
好的，我会尽快更新文档

**Comment by huangyanxiong01** [comment]
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```
同样的问题
```
Please put your v2ray.exe and assets here!
```
为什么不做成自动检测？

**Comment by lhy0403** [comment]
> ```
> Distributor ID:	Ubuntu
> Description:	Ubuntu 16.04.6 LTS
> Release:	16.04
> Codename:	xenial
> ```
> 
> 同样的问题
> 
> ```
> Please put your v2ray.exe and assets here!
> ```
> 
> 为什么不做成自动检测？

因为目前为止全平台只有 Arch 系列有相关 v2ray 包，目前没有自动识别的必要

**Comment by lhy0403** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=908921
