### ISSUE TITLE
找不到openssl库

### ISSUE THREAD

**Issue by NoOne-hub** [lhy0403/Qv2ray#90]
└──╼ $./Qv2ray-v1.3.7.1-linux.AppImage 
[LICENCE]: 
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.

Qv2ray Current Developer Copyright (C) 2019 Leroy.H.Y (@lhy0403)
Hv2ray Initial Idea and Designs Copyright (C) 2019 Hork (@aliyuchang33)
Hv2ray/Qv2ray HTTP Request Helper (partial) Copyright 2019 (C) SOneWinstone (@SoneWinstone)
Qv2ray ArtWork Done By ArielAxionL (@axionl)

Qv2ray v1.3.7.1 running on Parrot GNU/Linux 4.6 x86_64

[UI]: Found Translator: :/translations/en-US.qm
[UI]: Found Translator: :/translations/ru-RU.qm
[UI]: Found Translator: :/translations/zh-CN.qm
[INIT]: Loaded config file.
[UI]: Loaded Translator zh-CN
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_num_locks
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_id_callback
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_locking_callback
qt.network.ssl: QSslSocket: cannot resolve ERR_free_strings
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_cleanup
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_init
qt.network.ssl: QSslSocket: cannot resolve sk_new_null
qt.network.ssl: QSslSocket: cannot resolve sk_push
qt.network.ssl: QSslSocket: cannot resolve sk_free
qt.network.ssl: QSslSocket: cannot resolve sk_num
qt.network.ssl: QSslSocket: cannot resolve sk_pop_free
qt.network.ssl: QSslSocket: cannot resolve sk_value
qt.network.ssl: QSslSocket: cannot resolve SSL_library_init
qt.network.ssl: QSslSocket: cannot resolve SSL_load_error_strings
qt.network.ssl: QSslSocket: cannot resolve SSL_get_ex_new_index
qt.network.ssl: QSslSocket: cannot resolve SSLv3_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv3_server_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_server_method
qt.network.ssl: QSslSocket: cannot resolve X509_STORE_CTX_get_chain
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
qt.network.ssl: QSslSocket: cannot resolve SSLeay
qt.network.ssl: Incompatible version of OpenSSL
[NETWORK]: Current OpenSSL version: 
[NETWORK]: Required OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
[NETWORK]: OpenSSL library MISSING, Quitting.

**Comment by lhy0403** [comment]
见 #65

**Comment by lhy0403** [comment]
Closed doe to inactive, 如果有类似 OpenSSL 问题的请参阅  #90
