### ISSUE TITLE
首选项里更改HTTP端口时闪退

### ISSUE THREAD

**Issue by lpzzz** [lhy0403/Qv2ray#92]
**简单描述这个 bug：**
用backspace键删除端口号，在只剩一位的时候继续删除，会闪退

**如何复现这个bug：**
1. 用backspace键删除端口号
2. 
3. 
4. 

**Qv2ray 本应该是怎样工作的？**

**如果是连接问题，在其他 v2ray 客户端里出现过吗？** 

**相关截图或日志**

```
日志：

```

**系统信息**
 - 系统类型（windows, linux, macos）
    - windows10
 - 是从release下载的还是自己编译的
    - release
 - 首选项里的版本号：
    - v1.3.7.1

**其他信息**
你认为对我们修复bug有帮助的任何信息都可以在这里写出来：
*在提供自己的vmess或者配置文件时，注意隐藏好服务器地址和uuid*

-

**Comment by lhy0403** [comment]
收到

**Comment by lhy0403** [comment]
你好，新版本将会修复了此 bug，在此之前可以暂时使用补丁版本：
下载地址  https://jenkins.lhy0403.top/job/Qv2ray-Win32-Version1/lastSuccessfulBuild/artifact/build/

**Comment by lpzzz** [comment]
谢谢

**Comment by lhy0403** [comment]
问题解决了吗？
