### ISSUE TITLE
VMess String Check Some internal error occurred

### ISSUE THREAD

**Issue by lhy0403** [lhy0403/Qv2ray#93]
---------------------------
VMess String Check
---------------------------
Some internal error occurred
---------------------------
OK   
---------------------------
![TIM图片20191003102700](https://user-images.githubusercontent.com/5364709/66095610-b2f3fe00-e5ca-11e9-8d55-44d2e0721e0e.png)

下面是我的连接，我导入到安卓端完全没问题。

> `VMESS STRING HIDDEN`

_Originally posted by @leoxxx in https://github.com/lhy0403/Qv2ray/issues/69#issuecomment-537758321_

**Comment by lhy0403** [comment]
经检查，是你的 `vmess://` 连接没有完全遵守相关规范：
[https://github.com/2dust/v2rayN/wiki/分享链接格式说明(ver-2)](https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2))

![image](https://user-images.githubusercontent.com/18734999/66096227-e59ef600-e5cc-11e9-94c9-67b3de41664b.png)

缺少 Path 项，请联系vmess提供商

**Comment by lhy0403** [comment]
v1.3.7.2 将会修复此问题
如果着急的话请麻烦自己编辑 `QvCoreConfigOperations_Verification.cpp` 文件，删除第 23 行的 `C("Path")` 然后即可通过检查

**Comment by lhy0403** [comment]
噢对了我可以问题下您使用的是什么系统吗？

**Comment by leoxxx** [comment]
WIN7 经典皮。

**Comment by lhy0403** [comment]
https://jenkins.lhy0403.top/job/Qv2ray-Win32-Version1/lastSuccessfulBuild/artifact/build/

**Comment by leoxxx** [comment]
已测，可正常导入。
这个连接是我网上找的，我也不知道这项是干啥的。

**Comment by lhy0403** [comment]
好的，谢谢

**Comment by aliyuchang33** [comment]
可以考虑把vmess解析模块做一个模板，提取关键信息，同时方便自定义vmess规则

**Comment by lhy0403** [comment]
?没听懂？
