### ISSUE TITLE
点击删连接后，JSON文件依然存在

### ISSUE THREAD

**Issue by leoxxx** [lhy0403/Qv2ray#94]
如题，对应的JSON文件并没有被删除。

**Comment by lhy0403** [comment]
这个问题有待讨论，暂时还没有想好要不要删除文件

**Comment by leoxxx** [comment]
不删难道还要手动清理？那么如果我再导入一个同名的VMESS连接，只是变一下端口和密码的话这个新的JSON怎么算？

**Comment by lhy0403** [comment]
会替换掉原来的文件
