### ISSUE TITLE
A typo on version-v1 branch.

### ISSUE THREAD

**Issue by lhy0403** [lhy0403/Qv2ray#98]
@lhy0403 
On Debian Buster:
```
找不到 OpenSSL 库
This could be caused by a missing of `openssl` package in your system.
Please refer to Github Issue #65 to check for solutions.
Github Issue Link: https://github.com/lhy0403/Qv2ray/issues/65

Technical Details
OSsl.Rq.V=OpenSSL 1.0.2g  1 Mar 2016
OSsl.Cr.V=OpenSSL 1.0.2g  1 Mar 2016
```

_Originally posted by @SiqingYu in https://github.com/lhy0403/Qv2ray/issues/65#issuecomment-538723650_

**Comment by lhy0403** [comment]
https://github.com/lhy0403/Qv2ray/blob/c40e47c589e33970e8f01adc83e8a764dcbc52e5/src/main.cpp#L144

**Comment by lhy0403** [comment]
This was introduced from commit: https://github.com/lhy0403/Qv2ray/commit/f1f91f0537043f4beeb4510b8d98189b28c3d506

**Comment by aliyuchang33** [comment]
somebody noob

**Comment by lhy0403** [comment]
> somebody noob

I'm noob

**Comment by aliyuchang33** [comment]
lmao
